// src/views/components/calendar-popout/demo/DisabledDate.vue
<template>
  <s-calendar-popout
    v-model="value"
    v-model:visible="visible"
    title="请选择日期"
    :disabled-date="disabledDate"
    value-format="YYYY-MM-DD"
  />

  <s-list card>
    <s-list-item
      title="请选择日期"
      arrow
      hover
      :value="JSON.stringify(value)"
      @click="visible = true"
    />
  </s-list>
</template>

<script setup lang="ts">
import { ref } from 'vue'

const value = ref<Date>()
const visible = ref(false)

const disabledDate = (date: Date) => {
  return /0|6/.test(String(date.getDay()))
}
</script>

// packages/sard-taro-demo/src/packageA/pages/calendar/demo/DisabledDate.tsx
import { Calendar, List, PopoutInput } from 'sard-taro'

export default () => {
  // 禁用周末
  const disabledDate = (date: Date) => {
    return /0|6/.test(String(date.getDay()))
  }

  return (
    <List card>
      <List.Item>
        <PopoutInput
          title="请选择日期"
          inputProps={{ placeholder: '请选择日期' }}
        >
          <Calendar disabledDate={disabledDate} />
        </PopoutInput>
      </List.Item>
    </List>
  )
}
