// src/views/components/steps/index.vue
<template>
  <doc-page gray title="Steps 步骤条">
    <doc-demo title="基础使用">
      <Basic />
    </doc-demo>

    <doc-demo title="居中">
      <Center />
    </doc-demo>

    <doc-demo title="文字在上">
      <Reverse />
    </doc-demo>

    <doc-demo title="垂直步骤条">
      <Vertical />
    </doc-demo>

    <doc-demo title="垂直居中">
      <VerticalCenter />
    </doc-demo>

    <doc-demo title="自定义图标">
      <Icon />
    </doc-demo>

    <doc-demo title="自定义颜色">
      <Color />
    </doc-demo>

    <doc-demo title="当前步骤状态">
      <Status />
    </doc-demo>

    <doc-demo title="错误步骤">
      <ErrorStatus />
    </doc-demo>

    <doc-demo title="自定义各步骤状态">
      <StepStatus />
    </doc-demo>

    <doc-demo title="默认插槽">
      <Slot />
    </doc-demo>
  </doc-page>
</template>

<script setup lang="ts">
import Basic from './demo/Basic.vue'
import Center from './demo/Center.vue'
import Reverse from './demo/Reverse.vue'
import Vertical from './demo/Vertical.vue'
import VerticalCenter from './demo/VerticalCenter.vue'
import Icon from './demo/Icon.vue'
import Color from './demo/Color.vue'
import Status from './demo/Status.vue'
import ErrorStatus from './demo/ErrorStatus.vue'
import StepStatus from './demo/StepStatus.vue'
import Slot from './demo/Slot.vue'
</script>

// packages/SardDemo/src/packageA/pages/steps/index.tsx
import Demo from '@/components/demo'
import Page from '@/components/page'

import Basic from './demo/Basic'
import Center from './demo/Center'
import Vertical from './demo/Vertical'
import VerticalCenter from './demo/VerticalCenter'
import Icon from './demo/Icon'
import Status from './demo/Status'
import ErrorStatus from './demo/ErrorStatus'
import StepStatus from './demo/StepStatus'
import Clickable from './demo/Clickable'
import Disabled from './demo/Disabled'
import Color from './demo/Color'

export default () => {
  return (
    <Page>
      <Demo title="基础使用">
        <Basic />
      </Demo>

      <Demo title="居中">
        <Center />
      </Demo>

      <Demo title="垂直步骤条">
        <Vertical />
      </Demo>

      <Demo title="垂直居中">
        <VerticalCenter />
      </Demo>

      <Demo title="自定义图标">
        <Icon />
      </Demo>

      <Demo title="自定义颜色">
        <Color />
      </Demo>

      <Demo title="当前步骤状态">
        <Status />
      </Demo>

      <Demo title="错误步骤">
        <ErrorStatus />
      </Demo>

      <Demo title="自定义各步骤状态">
        <StepStatus />
      </Demo>

      <Demo title="可点击的">
        <Clickable />
      </Demo>

      <Demo title="禁用">
        <Disabled />
      </Demo>
    </Page>
  )
}
