// packages/sard-taro/src/empty/index.tsx
import { FC, ReactNode } from 'react'
import { View } from '@tarojs/components'
import classNames from 'classnames'
import { Icon, IconProps } from '../icon'
import useTranslate from '../locale/useTranslate'
import { BaseProps } from '../base'
import { isNullish } from '../utils'
import { useBem } from '../use'

export interface EmptyProps extends BaseProps {
  icon?: ReactNode
  iconProps?: IconProps
  description?: ReactNode
}

export const Empty: FC<EmptyProps> = (props) => {
  const [t] = useTranslate('empty')

  const {
    className,
    children,
    icon,
    iconProps,
    description = t('noData'),
    ...restProps
  } = props

  const [bem] = useBem('empty')

  const emptyClass = classNames(bem.b(), className)

  return (
    <View {...restProps} className={emptyClass}>
      <View className={bem.e('icon')}>
        {icon ?? <Icon name="empty" {...iconProps}></Icon>}
      </View>
      {!isNullish(description) && (
        <View className={bem.e('description')}>{description}</View>
      )}
      {!isNullish(children) && (
        <View className={bem.e('extra')}>{children}</View>
      )}
    </View>
  )
}

export default Empty

// packages/sard/components/empty/empty.vue
<template>
  <div :class="emptyClass">
    <div :class="bem.e('icon')" :style="iconStyle">
      <slot name="icon">
        <Empty />
      </slot>
    </div>
    <slot name="description">
      <div :class="bem.e('description')">
        {{ description || t('noData') }}
      </div>
    </slot>
    <div v-if="slots.default" :class="bem.e('extra')">
      <slot></slot>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { addUnit, createBem } from '../../utils'
import { useTranslateWithPrefix } from '../../locale'
import { type EmptyProps, type EmptySlots, defaultEmptyProps } from './common'
import { Empty } from '@sard/icons'

const { t } = useTranslateWithPrefix('empty')

const props = withDefaults(defineProps<EmptyProps>(), defaultEmptyProps)

const slots = defineSlots<EmptySlots>()

const bem = createBem('empty')

// ============================ style ============================

const emptyClass = computed(() => {
  return [bem.b(), bem.m(props.size)]
})

const iconStyle = computed(() => {
  return {
    fontSize: addUnit(props.iconSize),
  }
})
</script>
