// packages/sard-taro-demo/src/packageA/pages/toast/demo/Placement.tsx
import { List, Toast } from 'sard-taro'

export default () => {
  return (
    <List card>
      <List.Item
        linkable
        title="顶部位置"
        onClick={() => {
          Toast.show('顶部位置', {
            placement: 'top',
          })
        }}
      />
      <List.Item
        linkable
        title="底部位置"
        onClick={() => {
          Toast.show('底部位置', {
            placement: 'bottom',
          })
        }}
      />
    </List>
  )
}

// src/views/components/toast/demo/Placement.vue
<template>
  <s-list card>
    <s-list-item hover arrow title="顶部位置" @click="onTopToast" />
    <s-list-item hover arrow title="底部位置" @click="onBottomToast" />
  </s-list>
</template>

<script setup lang="ts">
import { toast } from 'sard'

const onTopToast = () => {
  toast('顶部位置', {
    position: 'top',
  })
}

const onBottomToast = () => {
  toast('底部位置', {
    position: 'bottom',
  })
}
</script>
