// src/views/components/list/demo/Slot.vue
<template>
  <s-list>
    <s-list-item title="标题">
      <template #value>
        <s-switch :model-value="true" />
      </template>
    </s-list-item>
    <s-list-item arrow hover title="标题">
      <template #value>
        <s-badge :value="20" />
      </template>
    </s-list-item>
    <s-list-item title="音量">
      <template #value>
        <s-slider style="width: 260px" :value="50" />
      </template>
    </s-list-item>

    <s-list-item>
      <div
        style="display: flex; flex-direction: column; align-items: center; padding: 20; gap: 5px"
      >
        <img :src="logo" style="width: 48px; height: 48px" />
        <div style="font-size: 20px">这是标题</div>
        <div>
          这是一段很长的描述这是一段很长的描述这是一段很长的描述这是一段很长的描述这是一段很长的描述这是一段很长的描述...
        </div>
      </div>
    </s-list-item>
    <s-list-item>
      <s-input v-model="name" inlaid placeholder="请输入用户名" />
    </s-list-item>
    <s-list-item>
      <s-input v-model="pwd" inlaid type="password" placeholder="请输入密码" />
    </s-list-item>
  </s-list>
</template>

<script setup lang="ts">
import logo from '@/assets/logo.svg'
import { ref } from 'vue'

const name = ref('')
const pwd = ref('')
</script>

// packages/SardDemo/src/packageA/pages/list/demo/Slot.tsx
import { Image, View } from '@tarojs/components'
import { List, Input, Slider, Space, Switch } from 'sard'

export default () => {
  return (
    <List bodyStyle={{ width: 60, flexGrow: 0 }}>
      <List.Item
        bodyStyle={{ width: 90 }}
        title="无线局域网"
        value={<Switch defaultChecked />}
      />
      <List.Item
        title="音量"
        footer={<Slider style={{ width: '100%' }} defaultValue={50} />}
      />
      <List.Item>
        <Space align="center" style={{ padding: 20 }}>
          <Image
            src="https://unpkg.com/@sard/assets@1.2.0/images/logo.png"
            style={{ width: 48, height: 48 }}
          />
          <View style={{ fontSize: 20 }}>这是标题</View>
          <View>
            这是一段很长的描述这是一段很长的描述这是一段很长的描述这是一段很长的描述这是一段很长的描述这是一段很长的描述...
          </View>
        </Space>
      </List.Item>
      <List.Item
        title="用户名"
        footer={<Input inlaid placeholder="请输入用户名" />}
      />
      <List.Item
        title="密码"
        footer={<Input inlaid type="password" placeholder="请输入密码" />}
      />
    </List>
  )
}
