// packages/sard-taro-demo/src/packageA/pages/action-sheet/index.tsx
import Demo from '@/components/demo'
import Page from '@/components/page'

import Basic from './demo/Basic'
import NoAgent from './demo/NoAgent'
import Explicit from './demo/Explicit'
import Cancel from './demo/Cancel'
import Status from './demo/Status'
import Description from './demo/Description'

export default () => {
  return (
    <Page>
      <Demo title="基础使用" full>
        <Basic />
      </Demo>

      <Demo title="不使用代理" full>
        <NoAgent />
      </Demo>

      <Demo title="显式声明动作项组件" full>
        <Explicit />
      </Demo>

      <Demo title="取消按钮" full>
        <Cancel />
      </Demo>

      <Demo title="自定义操作状态" full>
        <Status />
      </Demo>

      <Demo title="描述" full>
        <Description />
      </Demo>
    </Page>
  )
}

// src/views/components/action-sheet/index.vue
<template>
  <doc-page title="ActionSheet 动作面板">
    <doc-demo title="基础使用">
      <Basic />
    </doc-demo>

    <doc-demo title="取消按钮">
      <Cancel />
    </doc-demo>

    <doc-demo title="描述信息">
      <Description />
    </doc-demo>

    <doc-demo title="动作状态">
      <Status />
    </doc-demo>

    <doc-demo title="命令式">
      <Imperative />
    </doc-demo>

    <doc-demo title="插槽">
      <Slot />
    </doc-demo>
  </doc-page>
</template>

<script setup lang="ts">
import Basic from './demo/Basic.vue'
import Cancel from './demo/Cancel.vue'
import Description from './demo/Description.vue'
import Status from './demo/Status.vue'
import Imperative from './demo/Imperative.vue'
import Slot from './demo/Slot.vue'
</script>
