// packages/SardDemo/src/packageA/pages/input/demo/Slot.tsx
import { Button, Icon, Input, Space } from 'sard'

export default () => {
  return (
    <Space>
      <Input placeholder="请输入" prepend={<Icon name="search" />} />
      <Input
        placeholder="请输入"
        append={<Button size="small">发送验证码</Button>}
        clearable
      />
    </Space>
  )
}

// src/views/components/input/demo/Slot.vue
<template>
  <s-input v-model="value" placeholder="请输入">
    <template #prepend>
      <demo-icon name="search" />
    </template>
  </s-input>
  <s-input v-model="value" placeholder="请输入" clearable>
    <template #append>
      <s-button variant="link" size="small" compact>发送验证码</s-button>
    </template>
  </s-input>
</template>

<script setup lang="ts">
import { ref } from 'vue'

const value = ref('')
</script>
