// packages/sard/src/components/grid/Col.tsx
import { CSSProperties, FC, ReactNode, useContext } from 'react'
import classNames from 'classnames'

import { RowContext } from './Row'

export interface ColProps {
  className?: string
  style?: CSSProperties
  children?: ReactNode
  span?: number | 'auto' | 'none'
  offset?: number
  order?: number
}

export const Col: FC<ColProps> = (props) => {
  const { children, className, style, span, offset, order, ...restProps } =
    props

  const colClass = classNames(
    's-col',
    {
      ['s-col-' + span]: span,
      ['s-col-offset-' + offset]: offset,
    },
    className,
  )

  const context = useContext(RowContext)

  const colStyle = {
    ...(order != null
      ? {
          order,
        }
      : null),
    ...(context.gutter
      ? {
          paddingLeft: context.gap[0] + context.gap[1],
          paddingRight: context.gap[0] + context.gap[1],
        }
      : null),
    ...style,
  }

  return (
    <div {...restProps} className={colClass} style={colStyle}>
      {children}
    </div>
  )
}

export default Col

// packages/sard/components/layout/col.vue
<template>
  <div :class="colClass" :style="colStyle">
    <slot></slot>
  </div>
</template>

<script setup lang="ts">
import { computed, inject } from 'vue'
import { type ColProps, type ColSlots, rowSymbol } from './common'
import { createBem } from '../../utils'

const props = withDefaults(defineProps<ColProps>(), {})

defineSlots<ColSlots>()

const context = inject(rowSymbol)

if (!context) {
  throw new Error('Col must be included in Row.')
}

const bem = createBem('col')

// ============================ style ============================

const colClass = computed(() => {
  return [
    bem.b(),
    bem.m(props.span, props.span !== undefined),
    bem.m(`offset-${props.offset}`, props.offset !== undefined),
  ]
})

const colStyle = computed(() => {
  const gutter = context.gutter

  return [
    props.order !== undefined
      ? {
          order: props.order,
        }
      : null,
    context.gap
      ? {
          paddingLeft: gutter[0] + gutter[1],
          paddingRight: gutter[0] + gutter[1],
        }
      : null,
  ]
})
</script>
