// packages/sard-taro-demo/src/packageA/pages/mesh/demo/Border.tsx
import { Mesh } from 'sard-taro'

export default () => {
  return (
    <Mesh border={false}>
      {Array(8)
        .fill(0)
        .map((_, index) => (
          <Mesh.Item
            key={index}
            text="文字"
            iconProps={{ name: 'image' }}
          ></Mesh.Item>
        ))}
    </Mesh>
  )
}

// src/views/components/grid/demo/Border.vue
<template>
  <s-grid bordered>
    <s-grid-item v-for="i in 8" :key="i" text="文字" #icon>
      <Image />
    </s-grid-item>
  </s-grid>

  <s-grid bordered :gap="10" class="mt-4">
    <s-grid-item v-for="i in 8" :key="i" text="文字" #icon>
      <Image />
    </s-grid-item>
  </s-grid>
</template>

<script setup lang="ts">
import { Image } from '@sard/icons'
</script>
