// packages/sard-taro-demo/src/packageA/pages/mesh/demo/Reverse.tsx
import { Mesh } from 'sard-taro'

export default () => {
  return (
    <>
      <Mesh direction="horizontal" reverse>
        {Array(8)
          .fill(0)
          .map((_, index) => (
            <Mesh.Item
              key={index}
              text="文字"
              iconProps={{ name: 'image' }}
            ></Mesh.Item>
          ))}
      </Mesh>

      <Mesh direction="vertical" reverse style={{ marginTop: 20 }}>
        {Array(8)
          .fill(0)
          .map((_, index) => (
            <Mesh.Item
              key={index}
              text="文字"
              iconProps={{ name: 'image' }}
            ></Mesh.Item>
          ))}
      </Mesh>
    </>
  )
}

// src/views/components/grid/demo/Reverse.vue
<template>
  <s-grid direction="horizontal" reverse>
    <s-grid-item v-for="i in 4" :key="i" text="文字" #icon>
      <Image />
    </s-grid-item>
  </s-grid>

  <s-grid direction="vertical" reverse class="mt-4">
    <s-grid-item v-for="i in 4" :key="i" text="文字" #icon>
      <Image />
    </s-grid-item>
  </s-grid>
</template>

<script setup lang="ts">
import { Image } from '@sard/icons'
</script>
