// packages/SardDemo/src/packageA/pages/mesh/demo/Reverse.tsx
import { Mesh, Space } from 'sard'

export default () => {
  return (
    <Space gap="large">
      <Mesh direction="horizontal" reverse>
        {Array(4)
          .fill(0)
          .map((_, index) => (
            <Mesh.Item key={index} text="文字" iconProps={{ name: 'image' }} />
          ))}
      </Mesh>

      <Mesh direction="vertical" reverse>
        {Array(4)
          .fill(0)
          .map((_, index) => (
            <Mesh.Item key={index} text="文字" iconProps={{ name: 'image' }} />
          ))}
      </Mesh>
    </Space>
  )
}

// src/views/components/grid/demo/Reverse.vue
<template>
  <s-grid direction="horizontal" reverse>
    <s-grid-item v-for="i in 4" :key="i" text="文字" #icon>
      <Image />
    </s-grid-item>
  </s-grid>

  <s-grid direction="vertical" reverse class="mt-4">
    <s-grid-item v-for="i in 4" :key="i" text="文字" #icon>
      <Image />
    </s-grid-item>
  </s-grid>
</template>

<script setup lang="ts">
import { Image } from '@sard/icons'
</script>
