// src/views/components/navbar/demo/Flow.vue
<template>
  <s-navbar title="发现" flow>
    <template #start>
      <s-navbar-item #icon>
        <demo-icon name="list-task" />
      </s-navbar-item>
    </template>
    <template #end>
      <s-navbar-item #icon>
        <demo-icon name="share" />
      </s-navbar-item>
      <s-navbar-item #icon>
        <demo-icon name="star" />
      </s-navbar-item>
      <s-navbar-item #icon>
        <demo-icon name="heart" />
      </s-navbar-item>
    </template>
  </s-navbar>
</template>

// packages/SardDemo/src/packageA/pages/navbar/demo/Flow.tsx
import { Icon, Navbar } from 'sard'

export default () => {
  return (
    <Navbar
      flow
      left={
        <Navbar.Item>
          <Icon family="demo-icons" name="list-task" size={20} />
        </Navbar.Item>
      }
      title="发现"
      right={
        <>
          <Navbar.Item>
            <Icon family="demo-icons" name="share" size={18} />
          </Navbar.Item>
          <Navbar.Item>
            <Icon family="demo-icons" name="star" size={20} />
          </Navbar.Item>
          <Navbar.Item>
            <Icon family="demo-icons" name="heart" size={18} />
          </Navbar.Item>
        </>
      }
    />
  )
}
