// src/views/components/accordion/index.vue
<template>
  <doc-page gray title="Accordion 手风琴">
    <doc-demo title="基础使用" full>
      <Basic />
    </doc-demo>

    <doc-demo title="展开多个" full>
      <Multiple />
    </doc-demo>

    <doc-demo title="禁用" full>
      <Disabled />
    </doc-demo>

    <doc-demo title="隐藏边框" full>
      <HideBorder />
    </doc-demo>

    <doc-demo title="插槽" full>
      <Slot />
    </doc-demo>
  </doc-page>
</template>

<script setup lang="ts">
import Basic from './demo/Basic.vue'
import Multiple from './demo/Multiple.vue'
import Disabled from './demo/Disabled.vue'
import HideBorder from './demo/HideBorder.vue'
import Slot from './demo/Slot.vue'
</script>

// packages/sard-taro-demo/src/packageA/pages/accordion/index.tsx
import Demo from '@/components/demo'
import Page from '@/components/page'

import Basic from './demo/Basic'
import Expand from './demo/Expand'
import MultipleExpand from './demo/MultipleExpand'
import Controllable from './demo/Controllable'
import Disabled from './demo/Disabled'
import Slot from './demo/Slot'
import Duration from './demo/Duration'

export default () => {
  return (
    <Page className="page-accordion">
      <Demo title="基础使用">
        <Basic />
      </Demo>

      <Demo title="默认展开">
        <Expand />
      </Demo>

      <Demo title="展开多个">
        <MultipleExpand />
      </Demo>

      <Demo title="受控">
        <Controllable />
      </Demo>

      <Demo title="禁用">
        <Disabled />
      </Demo>

      <Demo title="插槽">
        <Slot />
      </Demo>

      <Demo title="折叠时间">
        <Duration />
      </Demo>
    </Page>
  )
}
