// packages/sard/src/components/loading/index.tsx
import { CSSProperties, FC, ReactNode } from 'react'
import classNames from 'classnames'

export interface LoadingProps {
  className?: string
  style?: CSSProperties
  children?: ReactNode
  type?: 'spinner' | 'clock' | 'circular'
  color?: string
  size?: string | number
  text?: ReactNode
  vertical?: boolean
}

const clockIcon = Array(12)
  .fill(0)
  .map((_, i) => <div key={i} className="s-loading-scale"></div>)

const spinIcon = (
  <svg viewBox="25 25 50 50">
    <circle cx="50" cy="50" r="22" fill="none" />
  </svg>
)

export const Loading: FC<LoadingProps> = (props) => {
  const {
    className,
    style,
    children,
    type = 'spinner',
    color = '',
    size = '',
    text = '',
    vertical = false,
    ...restProps
  } = props

  const loadingClass = classNames(
    's-loading',
    {
      's-loading-vertical': vertical,
    },
    className,
  )
  const loadingStyle = {
    color,
    ...style,
  }
  const iconClass = classNames('s-loading-icon', 's-loading-' + type)
  const iconStyle = {
    fontSize: size,
  }

  const renderIcon = () => {
    return (
      <div className={iconClass} style={iconStyle}>
        {type === 'spinner' ? spinIcon : type === 'clock' ? clockIcon : null}
      </div>
    )
  }

  const renderText = () => {
    return (
      (children || text) && (
        <div className="s-loading-text">{children || text}</div>
      )
    )
  }

  return (
    <div {...restProps} className={loadingClass} style={loadingStyle}>
      {renderIcon()}
      {renderText()}
    </div>
  )
}

export default Loading

// packages/sard/components/loading/loading.vue
<template>
  <div :class="loadingClass">
    <div :class="iconClass" :style="iconStyle">
      <slot v-if="type === 'circular'" name="circular">
        <div :class="bem.e('spinner')"></div>
      </slot>
      <template v-else-if="type === 'clock'">
        <div
          v-for="i in 8"
          :key="i"
          :class="[
            bem.e('scale'),
            bem.em('scale', i),
            !props.animated
              ? {
                  [bem.em('scale', 'hidden')]: i > scaleShowNum,
                }
              : null,
          ]"
        ></div>
      </template>
    </div>

    <div
      v-if="isRenderVisible(slots.default || text)"
      :class="bem.e('text')"
      :style="loadingTextStyle"
    >
      <slot>
        {{ text }}
      </slot>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { isRenderVisible, createBem } from '../../utils'
import { type LoadingProps, type LoadingSlots, defaultLoadingProps } from './common'

const props = withDefaults(defineProps<LoadingProps>(), defaultLoadingProps)

const slots = defineSlots<LoadingSlots>()

const bem = createBem('loading')

const scaleShowNum = computed(() => {
  return Math.max(Math.floor(props.progress * 8), 1)
})

// ============================ style ============================

const loadingClass = computed(() => {
  return [bem.b(), bem.m('vertical', props.vertical)]
})

const iconClass = computed(() => {
  return [bem.e('icon'), bem.em('icon', props.type), bem.em('icon', 'animated', props.animated)]
})

const iconStyle = computed(() => {
  return [
    {
      color: props.color,
      fontSize: props.size,
    },
    props.type === 'circular' && !props.animated
      ? {
          transform: `rotate(${props.progress * 360}deg)`,
        }
      : null,
  ]
})

const loadingTextStyle = computed(() => {
  return { color: props.textColor, fontSize: props.textSize }
})
</script>
