// packages/sard-taro/src/loading/index.tsx
import { CSSProperties, FC, ReactNode, useMemo } from 'react'
import classNames from 'classnames'
import { View } from '@tarojs/components'
import { BaseProps } from '../base'
import { isNullish } from '../utils'
import { useBem } from '../use'

export interface LoadingProps extends BaseProps {
  type?: 'clock' | 'circular'
  color?: string
  size?: string | number
  text?: ReactNode
  textColor?: string
  textSize?: string | number
  vertical?: boolean
  iconStyle?: CSSProperties
  iconClass?: string
}

export const Loading: FC<LoadingProps> = (props) => {
  const {
    className,
    children,
    type = 'circular',
    color,
    size,
    text,
    textColor,
    textSize,
    vertical = false,
    iconStyle,
    iconClass,
    ...restProps
  } = props

  const [bem] = useBem('loading')

  const clockIcon = useMemo(() => {
    return Array(12)
      .fill(0)
      .map((_, i) => (
        <View
          key={i}
          className={classNames(bem.e('scale'), bem.em('scale', i + 1))}
        ></View>
      ))
  }, [bem])

  const circularIcon = useMemo(() => {
    return Array(3)
      .fill(0)
      .map((_, i) => (
        <View
          key={i}
          className={classNames(
            bem.e('circular-item'),
            bem.em('circular-item', i + 1),
          )}
        ></View>
      ))
  }, [bem])

  const loadingClass = classNames(
    bem.b(),
    bem.m('vertical', vertical),
    className,
  )

  const innerIconClass = classNames(bem.e('icon'), bem.e(type), iconClass)
  const innerIconStyle = {
    color,
    width: size,
    height: size,
    fontSize: size,
    ...iconStyle,
  }

  const renderIcon = () => {
    return (
      <View className={innerIconClass} style={innerIconStyle}>
        {type === 'circular'
          ? circularIcon
          : type === 'clock'
          ? clockIcon
          : null}
      </View>
    )
  }

  const renderText = () => {
    return (
      (!isNullish(children) || !isNullish(text)) && (
        <View
          className={classNames(
            bem.e('text'),
            bem.em('text', 'vertical', vertical),
          )}
          style={{ color: textColor, fontSize: textSize }}
        >
          {children ?? text}
        </View>
      )
    )
  }

  return (
    <View {...restProps} className={loadingClass}>
      {renderIcon()}
      {renderText()}
    </View>
  )
}

export default Loading

// packages/sard/components/loading/loading.vue
<template>
  <div :class="loadingClass">
    <div :class="iconClass" :style="iconStyle">
      <slot v-if="type === 'circular'" name="circular">
        <div :class="bem.e('spinner')"></div>
      </slot>
      <template v-else-if="type === 'clock'">
        <div
          v-for="i in 8"
          :key="i"
          :class="[
            bem.e('scale'),
            bem.em('scale', i),
            !props.animated
              ? {
                  [bem.em('scale', 'hidden')]: i > scaleShowNum,
                }
              : null,
          ]"
        ></div>
      </template>
    </div>

    <div
      v-if="isRenderVisible(slots.default || text)"
      :class="bem.e('text')"
      :style="loadingTextStyle"
    >
      <slot>
        {{ text }}
      </slot>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { isRenderVisible, createBem } from '../../utils'
import { type LoadingProps, type LoadingSlots, defaultLoadingProps } from './common'

const props = withDefaults(defineProps<LoadingProps>(), defaultLoadingProps)

const slots = defineSlots<LoadingSlots>()

const bem = createBem('loading')

const scaleShowNum = computed(() => {
  return Math.max(Math.floor(props.progress * 8), 1)
})

// ============================ style ============================

const loadingClass = computed(() => {
  return [bem.b(), bem.m('vertical', props.vertical)]
})

const iconClass = computed(() => {
  return [bem.e('icon'), bem.em('icon', props.type), bem.em('icon', 'animated', props.animated)]
})

const iconStyle = computed(() => {
  return [
    {
      color: props.color,
      fontSize: props.size,
    },
    props.type === 'circular' && !props.animated
      ? {
          transform: `rotate(${props.progress * 360}deg)`,
        }
      : null,
  ]
})

const loadingTextStyle = computed(() => {
  return { color: props.textColor, fontSize: props.textSize }
})
</script>
