// packages/sard-taro-demo/src/packageA/pages/dialog/demo/Round.tsx
import { List, Dialog } from 'sard-taro'

export default () => {
  return (
    <List card>
      <List.Item
        linkable
        title="显示提示框"
        onClick={() => {
          Dialog.alert({
            title: '提示',
            message: '此功能暂时无法使用',
            buttonType: 'round',
          })
        }}
      />
      <List.Item
        linkable
        title="显示确定框"
        onClick={() => {
          Dialog.confirm({
            title: '提示',
            message: '确定删除？',
            buttonType: 'round',
          })
        }}
      />
    </List>
  )
}

// src/views/components/dialog/demo/Round.vue
<template>
  <s-list card>
    <s-list-item arrow hover title="显示提示框" @click="showAlert" />
    <s-list-item arrow hover title="显示确定框" @click="showConfirm" />
  </s-list>
</template>

<script setup lang="ts">
import { dialog } from 'sard'

const showAlert = () => {
  dialog.alert({
    title: '提示',
    message: '此功能暂时无法使用',
    buttonType: 'round',
  })
}

const showConfirm = () => {
  dialog.confirm({
    title: '提示',
    message: '确定删除？',
    buttonType: 'round',
  })
}
</script>
