// packages/SardDemo/src/packageA/pages/upload/demo/DisabledReadOnly.tsx
import { Space, Upload } from 'sard'

export default () => {
  return (
    <Space>
      <Upload
        fileList={[
          {
            url: 'https://unpkg.com/@sard/assets@1.2.0/images/pic1.jpg',
          },
        ]}
        readOnly
      />

      <Upload
        fileList={[
          {
            url: 'https://unpkg.com/@sard/assets@1.2.0/images/pic1.jpg',
          },
        ]}
        disabled
      />
    </Space>
  )
}

// src/views/components/upload/demo/DisabledReadOnly.vue
<template>
  <doc-title>只读</doc-title>
  <s-upload
    :model-value="[
      {
        url: 'https://fastly.jsdelivr.net/npm/@sard/assets/pic1.jpg',
      },
    ]"
    readonly
  />

  <doc-title>禁用</doc-title>
  <s-upload
    :model-value="[
      {
        url: 'https://fastly.jsdelivr.net/npm/@sard/assets/pic1.jpg',
      },
    ]"
    disabled
  />
</template>
