// packages/SardDemo/src/packageA/pages/upload/demo/Status.tsx
import { useState } from 'react'
import { Upload, UploadFileItem } from 'sard'

export default () => {
  const handleAfterRead = (fileItem: UploadFileItem) => {
    console.log(fileItem)
    fileItem.status = 'uploading'
    fileItem.message = '正在上传'
    setList((list) => [...list])

    setTimeout(() => {
      fileItem.status = 'done'
      setList((list) => [...list])
    }, 1500)
  }

  const [list, setList] = useState<UploadFileItem[]>(() => [
    {
      url: 'https://unpkg.com/@sard/assets@1.2.0/images/pic1.jpg',
    },
    {
      url: 'https://unpkg.com/@sard/assets@1.2.0/images/pic2.jpg',
      status: 'uploading',
      message: '正在上传',
    },
    {
      url: 'https://unpkg.com/@sard/assets@1.2.0/images/pic3.jpg',
      status: 'failed',
      message: '上传失败',
    },
  ])

  return (
    <Upload fileList={list} onChange={setList} afterRead={handleAfterRead} />
  )
}

// src/views/components/upload/demo/Status.vue
<template>
  <s-upload v-model="fileList" :after-read="afterRead" />
</template>

<script setup lang="ts">
import type { UploadFileItem } from 'sard'
import { ref } from 'vue'

const fileList = ref<UploadFileItem[]>([
  {
    url: 'https://fastly.jsdelivr.net/npm/@sard/assets/pic1.jpg',
  },
  {
    url: 'https://fastly.jsdelivr.net/npm/@sard/assets/pic2.jpg',
    status: 'uploading',
    message: '正在上传',
  },
  {
    url: 'https://fastly.jsdelivr.net/npm/@sard/assets/pic3.jpg',
    status: 'failed',
    message: '上传失败',
  },
])

const afterRead = (fileItem: UploadFileItem) => {
  console.log(fileItem)
  fileItem.status = 'uploading'
  fileItem.message = '正在上传'

  setTimeout(() => {
    fileItem.status = 'done'
  }, 1500)
}
</script>
