// packages/sard-taro-demo/src/packageA/pages/upload/demo/Video.tsx
import { Upload } from 'sard-taro'

export default () => {
  return (
    <Upload
      accept="video"
      defaultFileList={[
        {
          url: 'https://www.runoob.com/try/demo_source/movie.mp4',
        },
        {
          url: 'https://www.runoob.com/try/demo_source/movie.mp4',
        },
        {
          url: 'https://www.runoob.com/try/demo_source/movie.mp4',
        },
      ]}
    />
  )
}

// src/views/components/upload/demo/Video.vue
<template>
  <s-upload
    media-type="video"
    :model-value="[
      {
        url: 'https://fastly.jsdelivr.net/npm/@sard/assets/video/video1.mp4',
      },
      {
        url: 'https://fastly.jsdelivr.net/npm/@sard/assets/video/video1.mp4',
      },
      {
        url: 'https://fastly.jsdelivr.net/npm/@sard/assets/video/video1.mp4',
      },
    ]"
  />
</template>
