// packages/sard-taro-demo/src/packageA/pages/calendar/demo/Formatter.tsx
import { Text } from '@tarojs/components'
import { Calendar, CalendarDay, List, PopoutInput } from 'sard-taro'

export default () => {
  const formatter = (day: CalendarDay) => {
    const year = day.date.getFullYear()
    const month = day.date.getMonth() + 1
    const date = day.date.getDate()
    const week = day.date.getDay()

    if (month === 5) {
      if (date === 1) {
        day.bottom = '劳动节'
      }
      if (date <= 3) {
        day.top = <Text style={{ color: 'tomato' }}>休</Text>
      }
      if (date === 4) {
        day.bottom = '青年节'
      }

      if (week === 0) {
        const weekOnFirstDay = new Date(year, month - 1, 1).getDay()
        const secondSunday = 15 - (weekOnFirstDay || 7)

        if (secondSunday === date) {
          day.bottom = '母亲节'
        }
      }
    }

    if (day.type === 'start') {
      day.bottom = '入店'
    } else if (day.type === 'end') {
      day.bottom = '离店'
    }

    if (week === 0 || week === 6) {
      day.style = {
        fontWeight: 'bold',
        color: 'tomato',
      }
    }
  }

  return (
    <List card>
      <List.Item>
        <PopoutInput
          title="请选择日期"
          inputProps={{ placeholder: '请选择日期' }}
        >
          <Calendar
            type="range"
            defaultCurrentDate={new Date(new Date().getFullYear(), 4, 1)}
            formatter={formatter}
          />
        </PopoutInput>
      </List.Item>
    </List>
  )
}

// src/views/components/calendar-popout/demo/Formatter.vue
<template>
  <s-calendar-popout
    v-model="value"
    v-model:visible="visible"
    title="请选择日期"
    type="range"
    :formatter="formatter"
    :current-date="new Date(new Date().getFullYear(), 4, 1)"
    value-format="YYYY-MM-DD"
  />

  <s-list card>
    <s-list-item
      title="请选择日期"
      arrow
      hover
      :value="JSON.stringify(value)"
      @click="visible = true"
    />
  </s-list>
</template>

<script setup lang="ts">
import type { CalendarDay } from 'sard'
import { ref } from 'vue'

const value = ref<Date>()
const visible = ref(false)

const formatter = (day: CalendarDay) => {
  const year = day.date.getFullYear()
  const month = day.date.getMonth() + 1
  const date = day.date.getDate()
  const week = day.date.getDay()

  if (month === 5) {
    if (date === 1) {
      day.bottom = '劳动节'
    }
    if (date <= 3) {
      day.top = '休'
    }
    if (date === 4) {
      day.bottom = '青年节'
    }

    if (week === 0) {
      const weekOnMonthStart = new Date(year, month - 1, 1).getDay()
      const secondSunday = 15 - (weekOnMonthStart || 7)

      if (secondSunday === date) {
        day.bottom = '母亲节'
      }
    }
  }

  if (day.type === 'start') {
    day.bottom = '入店'
  } else if (day.type === 'end') {
    day.bottom = '离店'
  }

  if (week === 0 || week === 6) {
    day.style = {
      fontWeight: 'bold',
      color: 'var(--s-color-danger)',
    }
  }
}
</script>
