// packages/sard/src/components/calendar/demo/MinMax.tsx
/*
### 自定义日期范围
*/

import { Popout, Calendar, Input } from 'sard'

export default function () {
  return (
    <Popout title="请选择日期">
      <Popout.Outlet>
        {({ value, setValue, setVisible }) => (
          <Input
            value={value || ''}
            onClear={() => setValue()}
            clearable
            onClick={() => setVisible(true)}
            readOnly
            placeholder="请选择日期"
          />
        )}
      </Popout.Outlet>
      <Popout.Target>
        <Calendar min={new Date(2022, 7, 25)} max={new Date(2022, 8, 28)} />
      </Popout.Target>
    </Popout>
  )
}

// src/views/components/calendar-popout/demo/MinMax.vue
<template>
  <s-calendar-popout
    v-model="value"
    v-model:visible="visible"
    title="请选择日期"
    :min="new Date(2000, 0, 7)"
    :max="new Date(2000, 0, 21)"
    value-format="YYYY-MM-DD"
  />

  <s-list card>
    <s-list-item
      title="请选择日期"
      arrow
      hover
      :value="JSON.stringify(value)"
      @click="visible = true"
    />
  </s-list>
</template>

<script setup lang="ts">
import { ref } from 'vue'

const value = ref<string>()
const visible = ref(false)
</script>
