// packages/SardDemo/src/packageA/pages/calendar/demo/MinMax.tsx
import { Calendar, List, PopoutInput } from 'sard'

export default () => {
  return (
    <List card>
      <List.Item>
        <PopoutInput
          title="请选择日期"
          inputProps={{ placeholder: '请选择日期' }}
        >
          <Calendar min={new Date(2000, 0, 7)} max={new Date(2000, 0, 21)} />
        </PopoutInput>
      </List.Item>
    </List>
  )
}

// src/views/components/calendar-popout/demo/MinMax.vue
<template>
  <s-calendar-popout
    v-model="value"
    v-model:visible="visible"
    title="请选择日期"
    :min="new Date(2000, 0, 7)"
    :max="new Date(2000, 0, 21)"
    value-format="YYYY-MM-DD"
  />

  <s-list card>
    <s-list-item
      title="请选择日期"
      arrow
      hover
      :value="JSON.stringify(value)"
      @click="visible = true"
    />
  </s-list>
</template>

<script setup lang="ts">
import { ref } from 'vue'

const value = ref<string>()
const visible = ref(false)
</script>
