// src/views/components/popout/index.vue
<template>
  <doc-page gray title="Popout 弹出框">
    <doc-demo title="基础使用">
      <Basic />
    </doc-demo>

    <doc-demo title="宽松类型">
      <Loose />
    </doc-demo>

    <doc-demo title="异步关闭">
      <BeforeClose />
    </doc-demo>
  </doc-page>
</template>

<script setup lang="ts">
import Basic from './demo/Basic.vue'
import Loose from './demo/Loose.vue'
import BeforeClose from './demo/BeforeClose.vue'
</script>

// packages/SardDemo/src/packageA/pages/popout/index.tsx
import Demo from '@/components/demo'
import Page from '@/components/page'

import Basic from './demo/Basic'
import Compact from './demo/Compact'
import WithCalendar from './demo/WithCalendar'

export default () => {
  return (
    <Page>
      <Demo title="基础使用">
        <Basic />
      </Demo>

      <Demo title="紧凑类型">
        <Compact />
      </Demo>

      <Demo title="结合日期组件">
        <WithCalendar />
      </Demo>
    </Page>
  )
}
