// packages/SardDemo/src/packageA/pages/cascader/demo/Async.tsx
import { Cascader, List, PopoutInput } from 'sard'
import { useState } from 'react'

export default () => {
  const [options, setOptions] = useState(
    Array(10)
      .fill(0)
      .map((_, i) => {
        return {
          label: 'label' + i,
          value: i,
          children: [],
        }
      }),
  )

  const handleSelect = (option, columnIndex) => {
    if (columnIndex < 2 && option.children.length === 0) {
      setTimeout(() => {
        option.children = Array(10)
          .fill(0)
          .map((_, i) => {
            return {
              label: option.label + '-label' + i,
              value: option.value + '-' + i,
              children: columnIndex < 1 ? [] : null,
            }
          })

        setOptions(options.slice())
      }, 1000)
    }
  }

  return (
    <List card>
      <List.Item>
        <PopoutInput title="请选择" inputProps={{ placeholder: '请选择' }}>
          <Cascader options={options} onSelect={handleSelect} />
        </PopoutInput>
      </List.Item>
    </List>
  )
}

// src/views/components/cascader/demo/Async.vue
<template>
  <s-list card>
    <s-list-item>
      <s-cascader
        :options="options"
        :option-keys="{ children: 'nodeList' }"
        @select="onSelect"
        @change="onChange"
      />
    </s-list-item>
  </s-list>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { toast } from 'sard'

interface Option {
  label: string
  value: number | string
  nodeList?: Option[]
}

const options = ref<Option[]>(
  Array(10)
    .fill(0)
    .map((_, i) => {
      return {
        label: 'label' + i,
        value: i,
        nodeList: [],
      }
    }),
)

const onSelect = (option: Option, columnIndex: number) => {
  if (columnIndex < 2 && option.nodeList?.length === 0) {
    setTimeout(() => {
      option.nodeList = Array(10)
        .fill(0)
        .map((_, i) => {
          return {
            label: option.label + '-label' + i,
            value: option.value + '-' + i,
            nodeList: columnIndex < 1 ? [] : undefined,
          }
        })

      options.value = options.value.slice()
    }, 1000)
  }
}

const onChange = (_: any, selectedOptions: Option[]) => {
  toast(selectedOptions.map((option) => option.label).join('/'))
}
</script>
