// src/views/components/tabs/index.vue
<template>
  <doc-page title="Tabs 标签页">
    <doc-demo title="基础使用">
      <Basic />
    </doc-demo>

    <doc-demo title="可滚动标签栏">
      <Scrollable />
    </doc-demo>

    <doc-demo title="禁用标签">
      <Disabled />
    </doc-demo>

    <doc-demo title="药丸类型">
      <Pill />
    </doc-demo>

    <doc-demo title="卡片类型">
      <Card />
    </doc-demo>

    <doc-demo title="自定义标签">
      <CustomTab />
    </doc-demo>
  </doc-page>
</template>

<script setup lang="ts">
import Basic from './demo/Basic.vue'
import Scrollable from './demo/Scrollable.vue'
import Disabled from './demo/Disabled.vue'
import Pill from './demo/Pill.vue'
import Card from './demo/Card.vue'
import CustomTab from './demo/CustomTab.vue'
</script>

// packages/SardDemo/src/packageA/pages/tabs/index.tsx
import Demo from '@/components/demo'
import Page from '@/components/page'

import Basic from './demo/Basic'
import Scrollable from './demo/Scrollable'
import Disabled from './demo/Disabled'
import Swiper from './demo/Swiper'
import CustomTab from './demo/CustomTab'
import Line from './demo/Line'

export default () => {
  return (
    <Page emphasis>
      <Demo title="基础使用">
        <Basic />
      </Demo>

      <Demo title="可滚动标签栏">
        <Scrollable />
      </Demo>

      <Demo title="禁用标签">
        <Disabled />
      </Demo>

      <Demo title="自定义线条">
        <Line />
      </Demo>

      <Demo title="自定义标签">
        <CustomTab />
      </Demo>

      <Demo title="搭配 Swiper 使用">
        <Swiper />
      </Demo>
    </Page>
  )
}
