// packages/sard/components/layout/row.vue
<template>
  <div :class="bem.b()" :style="rowStyle">
    <slot></slot>
  </div>
</template>

<script setup lang="ts">
import { computed, provide, reactive, toRef } from 'vue'
import { splitUnit, createBem } from '../../utils'
import { type RowProps, type RowSlots, rowSymbol, mapJustify, mapAlign } from './common'

const props = withDefaults(defineProps<RowProps>(), {})

defineSlots<RowSlots>()

const bem = createBem('row')

const gutter = computed(() => {
  if (props.gap) {
    const result = splitUnit(props.gap)
    return [result[0] / 2, result[1] || 'px'] as const
  }
  return [0, 'px'] as const
})

provide(
  rowSymbol,
  reactive({
    gap: toRef(() => props.gap),
    gutter,
  }),
)

// ============================ style ============================

const rowStyle = computed(() => {
  return [
    {
      justifyContent: props.justify && mapJustify[props.justify],
      alignItems: props.align && mapAlign[props.align],
    },
    props.gap
      ? {
          marginLeft: -gutter.value[0] + gutter.value[1],
          marginRight: -gutter.value[0] + gutter.value[1],
        }
      : null,
  ]
})
</script>

// packages/sard-taro/src/grid/Row.tsx
import { createContext, FC, useMemo } from 'react'
import { View } from '@tarojs/components'
import classNames from 'classnames'
import { splitUnit } from '../utils'
import { BaseProps } from '../base'
import { useBem } from '../use'

const mapJustify = {
  start: 'flex-start',
  center: 'center',
  end: 'flex-end',
  around: 'space-around',
  between: 'space-between',
  evenly: 'space-evenly',
}
const mapAlign = {
  start: 'flex-start',
  center: 'center',
  end: 'flex-end',
  stretch: 'stretch',
}

export type RowContextValue = readonly [
  merged: string | number,
  value: number,
  unit: string,
]

export const RowContext = createContext<RowContextValue>(null)

export interface RowProps extends BaseProps {
  gap?: number | string
  justify?: 'start' | 'center' | 'end' | 'around' | 'between' | 'evenly'
  align?: 'start' | 'center' | 'end' | 'stretch'
}

export const Row: FC<RowProps> = (props) => {
  const { className, style, children, gap, justify, align, ...restProps } =
    props

  const [bem] = useBem('row')

  const gutter = useMemo(() => {
    if (gap) {
      const result = splitUnit(gap)
      const value = result[0] / 2
      const unit = result[1]
      const merged = unit ? value + unit : value
      return [merged, value, unit] as const
    }
  }, [gap])

  const rowStyle = Object.assign(
    {
      justifyContent: justify && mapJustify[justify],
      alignItems: align && mapAlign[align],
    },
    gap
      ? {
          marginLeft: -gutter[0],
          marginRight: -gutter[0],
        }
      : null,
    style,
  )

  const rowClass = classNames(bem.b(), className)

  return (
    <View {...restProps} className={rowClass} style={rowStyle}>
      <RowContext.Provider value={gutter}>{children}</RowContext.Provider>
    </View>
  )
}

export default Row
