// packages/sard-taro-demo/src/packageA/pages/picker/index.tsx
import Demo from '@/components/demo'
import Page from '@/components/page'

import ObjectOption from './demo/ObjectOption'
import Multiple from './demo/Multiple'
import ObjectMultiple from './demo/ObjectMultiple'
import Cascaded from './demo/Cascaded'
import Basic from './demo/Basic'
import Alone from './demo/Alone'
import Appointment from './demo/Appointment'

export default () => {
  return (
    <Page>
      <Demo title="基础使用" full>
        <Basic />
      </Demo>

      <Demo title="对象类型" full>
        <ObjectOption />
      </Demo>

      <Demo title="多列" full>
        <Multiple />
      </Demo>

      <Demo title="对象类型多列" full>
        <ObjectMultiple />
      </Demo>

      <Demo title="级联选择" full>
        <Cascaded />
      </Demo>

      <Demo title="预约时间" full>
        <Appointment />
      </Demo>

      <Demo title="单独使用" full>
        <Alone />
      </Demo>
    </Page>
  )
}

// src/views/components/picker/index.vue
<template>
  <doc-page gray title="Picker 选择器">
    <doc-demo title="基础使用">
      <Basic />
    </doc-demo>

    <doc-demo title="对象类型">
      <ObjectOption />
    </doc-demo>

    <doc-demo title="多列">
      <Multiple />
    </doc-demo>

    <doc-demo title="对象类型多列">
      <ObjectMultiple />
    </doc-demo>

    <doc-demo title="级联选择">
      <Cascaded />
    </doc-demo>

    <doc-demo title="插槽">
      <Slot />
    </doc-demo>
  </doc-page>
</template>

<script setup lang="ts">
import Basic from './demo/Basic.vue'
import ObjectOption from './demo/ObjectOption.vue'
import Multiple from './demo/Multiple.vue'
import ObjectMultiple from './demo/ObjectMultiple.vue'
import Cascaded from './demo/Cascaded.vue'
import Slot from './demo/Slot.vue'
</script>

<style lang="scss" scoped>
:deep() {
  .s-button {
    margin-top: 10px;
  }
}
</style>
