// src/views/components/menu/demo/Dark.vue
<template>
  <s-menu theme="dark" @select="onSelect">
    <s-menu-item :value="1" label="选项1" />
    <s-menu-item :value="2" label="选项2" />
    <s-menu-item :value="3" label="选项3" />
  </s-menu>
</template>

<script setup lang="ts">
import { toast, type MenuItemProps } from 'sard'

const onSelect = (props: MenuItemProps) => {
  toast(props.label!)
}
</script>

// packages/SardDemo/src/packageA/pages/popover/demo/Dark.tsx
import { Button, Popover, Toast } from 'sard'

export default () => {
  return (
    <Popover
      theme="dark"
      options={[
        {
          text: '选项1',
        },
        {
          text: '选项2',
        },
        {
          text: '选项3',
        },
      ]}
      reference={<Button>自定义颜色</Button>}
      onSelect={({ text }) => Toast.show(text)}
    />
  )
}
