// src/views/components/menu/demo/Horizontal.vue
<template>
  <s-menu direction="horizontal" @select="onSelect">
    <s-menu-item :value="1" label="选项1" #icon>
      <demo-icon name="upc-scan" />
    </s-menu-item>
    <s-menu-item :value="2" label="选项2" #icon>
      <demo-icon name="camera" />
    </s-menu-item>
    <s-menu-item :value="3" label="选项3" />
  </s-menu>
</template>

<script setup lang="ts">
import { toast, type MenuItemProps } from 'sard'

const onSelect = (props: MenuItemProps) => {
  toast(props.label!)
}
</script>

// packages/SardDemo/src/packageA/pages/popover/demo/Horizontal.tsx
import { Button, Popover, Toast } from 'sard'

export default () => {
  return (
    <Popover
      direction="horizontal"
      options={[
        {
          text: '选项1',
          iconProps: {
            family: 'demo-icons',
            name: 'upc-scan',
          },
        },
        {
          text: '选项2',
        },
        {
          text: '选项3',
        },
      ]}
      reference={<Button>水平排列</Button>}
      onSelect={({ text }) => Toast.show(text)}
    />
  )
}
