// src/views/components/layout/demo/Justify.vue
<template>
  <s-row v-for="item in justifyTypes" :justify="item">
    <s-col v-for="i in 3" :span="3">
      <div class="layout-box">{{ item }}</div>
    </s-col>
  </s-row>
</template>

<script setup lang="ts">
const justifyTypes = ['start', 'center', 'end', 'around', 'between', 'evenly'] as const
</script>

// packages/SardDemo/src/packageA/pages/grid/demo/Justify.tsx
import { Col, Row, Space } from 'sard'

import GridBox from '../GridBox'

export default () => {
  return (
    <Space gap="large">
      <Row justify="start">
        <Col span={3}>
          <GridBox>span-3</GridBox>
        </Col>
        <Col span={3}>
          <GridBox>span-3</GridBox>
        </Col>
      </Row>

      <Row justify="center">
        <Col span={3}>
          <GridBox>span-3</GridBox>
        </Col>
        <Col span={3}>
          <GridBox>span-3</GridBox>
        </Col>
      </Row>

      <Row justify="end">
        <Col span={3}>
          <GridBox>span-3</GridBox>
        </Col>
        <Col span={3}>
          <GridBox>span-3</GridBox>
        </Col>
      </Row>
    </Space>
  )
}
