// src/views/components/layout/demo/Order.vue
<template>
  <s-row>
    <s-col>
      <div class="layout-box">col1</div>
    </s-col>
    <s-col :order="-1">
      <div class="layout-box">col2 order:-1</div>
    </s-col>
  </s-row>

  <s-row>
    <s-col :order="2">
      <div class="layout-box">col1 order:2</div>
    </s-col>
    <s-col :order="1">
      <div class="layout-box">col2 order:1</div>
    </s-col>
    <s-col>
      <div class="layout-box">col3</div>
    </s-col>
  </s-row>
</template>

// packages/SardDemo/src/packageA/pages/grid/demo/Order.tsx
import { Col, Row, Space } from 'sard'

import GridBox from '../GridBox'

export default () => {
  return (
    <Space gap="large">
      <Row>
        <Col>
          <GridBox>col1</GridBox>
        </Col>
        <Col order={-1}>
          <GridBox>col2 order:-1</GridBox>
        </Col>
      </Row>

      <Row>
        <Col order={2}>
          <GridBox>col1 order:2</GridBox>
        </Col>
        <Col order={1}>
          <GridBox>col2 order:1</GridBox>
        </Col>
        <Col>
          <GridBox>col3</GridBox>
        </Col>
      </Row>
    </Space>
  )
}
