// packages/sard/src/components/picker/demo/Multiple.tsx
/*
### 多列
*/

import { Picker } from 'sard'

export default function () {
  const columns = Array(2)
    .fill(0)
    .map((_, i) =>
      Array(10)
        .fill(0)
        .map((_, j) => ({
          value: `${i}-${j}`,
          label: `column${i}-item${j}`,
        })),
    )

  return (
    <>
      <Picker columns={columns} />
    </>
  )
}

// src/views/components/picker/demo/Multiple.vue
<template>
  <s-list card>
    <s-list-item>
      <s-picker v-model="value" :columns="columns" />
    </s-list-item>
    <s-list-item title="当前值：" :value="JSON.stringify(value) ?? 'undefined'" />
    <s-list-item title="设置为: 2003年10月" arrow hover @click="value = ['2003年', '10月']" />
    <s-list-item title="清空" arrow hover @click="value = undefined" />
  </s-list>
</template>

<script setup lang="ts">
import { ref } from 'vue'

const columns = [
  Array(10)
    .fill(0)
    .map((_, index) => 2000 + index + '年'),
  Array(12)
    .fill(0)
    .map((_, index) => 1 + index + '月'),
]

const value = ref<string[] | undefined>(['2005年', '5月'])
</script>
