// src/views/components/date-strip/demo/DisabledDate.vue
<template>
  <s-list card>
    <s-list-item>
      <s-date-strip
        v-model="value"
        :min="new Date(2024, 0, 1)"
        :max="new Date(2024, 0, 15)"
        :disabled-date="disabledDate"
      />
    </s-list-item>
    <s-list-item title="说明" value="仅开放工作日" />
    <s-list-item title="当前值" :value="value ? formatDate(value, 'YYYY-MM-DD') : 'undefined'" />
  </s-list>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { formatDate } from 'sard'

const value = ref<Date>()

const disabledDate = (date: Date) => {
  return [0, 6].includes(date.getDay())
}
</script>

// packages/SardDemo/src/packageA/pages/calendar/demo/DisabledDate.tsx
import { Calendar, List, PopoutInput } from 'sard'

export default () => {
  // 禁用周末
  const disabledDate = (date: Date) => {
    return /0|6/.test(String(date.getDay()))
  }

  return (
    <List card>
      <List.Item>
        <PopoutInput
          title="请选择日期"
          inputProps={{ placeholder: '请选择日期' }}
        >
          <Calendar disabledDate={disabledDate} />
        </PopoutInput>
      </List.Item>
    </List>
  )
}
