// packages/sard/components/share-sheet/share-sheet.vue
<template>
  <Popup
    effect="slide-bottom"
    :visible="innerVisible"
    @overlay-click="onOverlayClick"
    @visible-hook="onVisibleHook"
  >
    <div :class="shareSheetClass">
      <template v-if="showTitle || showDescription">
        <div :class="bem.e('header')">
          <div v-if="showTitle" :class="bem.e('title')">
            <slot name="title">{{ title }}</slot>
          </div>
          <div v-if="showDescription" :class="bem.e('description')">
            <slot name="description">{{ description }}</slot>
          </div>
        </div>
      </template>

      <div :class="bem.e('body')">
        <slot></slot>
      </div>

      <template v-if="mergedShowCancel">
        <div :class="bem.e('gap')"></div>
        <div :class="bem.e('cancel')" @click="onCancel">
          <slot name="cancel">
            {{ cancel || t('cancel') }}
          </slot>
        </div>
      </template>
    </div>
  </Popup>
</template>

<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import { createBem, noop, isFunction } from '../../utils'
import Popup from '../popup/popup.vue'
import {
  type ShareSheetProps,
  type ShareSheetEmits,
  type ShareSheetSlots,
  type ShareSheetItemProps,
  defaultShareSheetProps,
} from './common'
import { useShareSheet } from './context'
import { useTranslateWithPrefix } from '../../locale'
import type { MotionHookName } from '../motion/common'

const props = withDefaults(defineProps<ShareSheetProps>(), defaultShareSheetProps)

const slots = defineSlots<ShareSheetSlots>()

const emit = defineEmits<ShareSheetEmits>()

const bem = createBem('share-sheet')

const { t } = useTranslateWithPrefix('shareSheet')

const mergedShowCancel = computed(() => {
  return !!(props.showCancel || props.cancel || !!slots.cancel)
})

const showTitle = computed(() => {
  return !!(props.title || slots.title)
})

const showDescription = computed(() => {
  return !!(props.description || slots.description)
})

// ============================ visible ============================
const innerVisible = ref(props.visible)

watch(
  () => props.visible,
  () => {
    innerVisible.value = props.visible
  },
)

const perhapsClose = (type: 'close' | 'cancel' | 'select') => {
  if (isFunction(props.beforeClose)) {
    const result = props.beforeClose(type)
    if (result instanceof Promise) {
      return result
        .then(() => {
          innerVisible.value = false
          emit('update:visible', false)
        })
        .catch(noop)
    } else if (result === false) {
      return
    }
  }

  innerVisible.value = false
  emit('update:visible', false)
}

const onOverlayClick = () => {
  emit('close')
  if (props.overlayClosable) {
    perhapsClose('close')
  }
}

const onSelect = (item: ShareSheetItemProps) => {
  emit('select', { ...item })
  perhapsClose('select')
}

const onCancel = () => {
  emit('cancel')
  perhapsClose('cancel')
}

const onVisibleHook = (name: MotionHookName, el: Element) => {
  emit('visible-hook', name, el)
  emit(name as any, el)
}

// ============================ context ============================
useShareSheet({
  onSelect,
})

// ============================ style ============================
const shareSheetClass = computed(() => {
  return bem.b()
})
</script>

// packages/sard-taro-demo/src/sard-taro/share-sheet/index.tsx
import {
  ReactNode,
  FC,
  useMemo,
  ReactElement,
  cloneElement,
  Children,
} from 'react'
import classNames from 'classnames'
import { View, ITouchEvent } from '@tarojs/components'
import { useBem, useControllableValue, useEvent } from '../use'
import { Popup, PopupProps } from '../popup'
import { ShareSheetItem, ShareSheetItemProps } from './Item'
import { ShareSheetRow, ShareSheetRowProps } from './Row'
import { BaseProps } from '../base'
import { isFunction, isNullish, noop } from '../utils'
import Halfline from '../halfline'
import Pressable from '../pressable'
import SafeArea from '../safe-area'

export * from './Item'

export type ShareSheetItemList = ShareSheetItemProps[] | ShareSheetItemProps[][]

export interface ShareSheetProps extends BaseProps, PopupProps {
  itemList?: ShareSheetItemList
  title?: ReactNode
  description?: ReactNode
  cancel?: ReactNode
  onSelect?: (itemProps: ShareSheetItemProps) => void | Promise<any>
  onCancel?: () => void | Promise<any>
  onClose?: () => void | Promise<any>
  maskClosable?: boolean
  visible?: boolean
  defaultVisible?: boolean
  onVisible?: (visible: boolean) => void
}

export interface ShareSheetFC extends FC<ShareSheetProps> {
  Row: typeof ShareSheetRow
  Item: typeof ShareSheetItem
}

export const ShareSheet: ShareSheetFC = ((props) => {
  const {
    className,
    style,
    children,

    itemList,
    title,
    description,
    cancel,
    onSelect,
    onCancel,
    onClose,
    maskClosable = true,
    onMaskClick,
    visible,
    defaultVisible,
    onVisible,
    ...restProps
  } = props

  const [bem] = useBem('share-sheet')

  const [innerVisible, setInnerVisible] = useControllableValue({
    value: visible,
    defaultValue: defaultVisible,
    trigger: onVisible,
    initialValue: false,
  })

  const perhapsClose = (callback?: () => void | Promise<any>) => {
    if (isFunction(callback)) {
      const result = callback()
      if (result instanceof Promise) {
        return result
          .then(() => {
            setInnerVisible?.(false)
          })
          .catch(noop)
      }
    }

    setInnerVisible?.(false)
  }

  const handleItemClick = useEvent((itemProps: ShareSheetItemProps) => {
    perhapsClose(() => {
      return onSelect?.(itemProps)
    })
  })

  const handleMaskClick = useEvent((event: ITouchEvent) => {
    onMaskClick?.(event)

    if (maskClosable) {
      perhapsClose(onClose)
    }
  })

  const handleCancelClick = useEvent(() => {
    perhapsClose(onCancel)
  })

  const rowList = useMemo(() => {
    if (itemList) {
      if (itemList.length && !Array.isArray(itemList[0])) {
        return [itemList]
      }
      return itemList
    }
  }, [itemList])

  return (
    <Popup
      {...restProps}
      visible={innerVisible}
      effect="slide-bottom"
      className={bem.e('popup')}
      style={style}
      contentClass={classNames(bem.b(), className)}
      onMaskClick={handleMaskClick}
    >
      {(!isNullish(title) || !isNullish(description)) && (
        <View className={bem.e('header')}>
          {!isNullish(title) && <View className={bem.e('title')}>{title}</View>}
          {!isNullish(description) && (
            <View
              className={classNames(
                bem.e('description'),
                bem.em('description', 'titled', !isNullish(title)),
              )}
            >
              {description}
            </View>
          )}

          <Halfline direction="bottom" />
        </View>
      )}
      <View className={bem.e('body')}>
        {rowList
          ? rowList.map((itemList, index) => (
              <ShareSheetRow
                key={index}
                itemList={itemList}
                className={classNames(
                  bem.em(
                    'row',
                    'headless-first',
                    isNullish(title) && isNullish(description) && index === 0,
                  ),
                )}
                _onItemClick={(itemProps) => {
                  handleItemClick(itemProps)
                }}
                _later={index > 0}
              />
            ))
          : Children.map(
              children,
              (element: ReactElement<ShareSheetRowProps>, index) => {
                return cloneElement(element, {
                  _later: index > 0,
                  _onItemClick: (itemProps) => {
                    handleItemClick(itemProps)
                  },
                })
              },
            )}
      </View>
      {!isNullish(cancel) && (
        <>
          <View className={bem.e('gap')} />
          <Pressable>
            {({ pressed }) => (
              <View
                className={classNames(
                  bem.e('cancel'),
                  bem.em('cancel', 'pressed', pressed),
                )}
                onClick={handleCancelClick}
              >
                {cancel}
              </View>
            )}
          </Pressable>
        </>
      )}

      <SafeArea direction="bottom" />
    </Popup>
  )
}) as ShareSheetFC

ShareSheet.Row = ShareSheetRow
ShareSheet.Item = ShareSheetItem

export default ShareSheet
