// packages/SardDemo/src/packageA/pages/button/demo/Disabled.tsx
import { Button, Space } from 'sard'

export default () => {
  return (
    <Space>
      <Button disabled>default</Button>
      <Button disabled type="pale">
        pale
      </Button>
      <Button disabled type="mild">
        mild
      </Button>
      <Button disabled type="outline">
        outline
      </Button>
      <Button disabled type="text">
        text
      </Button>
      <Button disabled type="pale-text">
        pale-text
      </Button>
    </Space>
  )
}

// src/views/components/button/demo/Disabled.vue
<template>
  <s-space wrap>
    <s-button disabled variant="solid">Solid</s-button>
    <s-button disabled variant="outlined">Outlined</s-button>
    <s-button disabled variant="dashed">Dashed</s-button>
    <s-button disabled variant="filled">Filled</s-button>
    <s-button disabled variant="text">Text</s-button>
    <s-button disabled variant="link">Link</s-button>
  </s-space>
</template>
