// src/views/components/upload/demo/Video.vue
<template>
  <s-upload
    media-type="video"
    :model-value="[
      {
        url: 'https://fastly.jsdelivr.net/npm/@sard/assets/video/video1.mp4',
      },
      {
        url: 'https://fastly.jsdelivr.net/npm/@sard/assets/video/video1.mp4',
      },
      {
        url: 'https://fastly.jsdelivr.net/npm/@sard/assets/video/video1.mp4',
      },
    ]"
  />
</template>

// packages/SardDemo/src/packageA/pages/upload/demo/Video.tsx
import { Upload } from 'sard'

export default () => {
  return (
    <Upload
      accept="video"
      defaultFileList={[
        {
          url: 'https://unpkg.com/@sard/assets@1.2.0/video/video1.mp4',
        },
        {
          url: 'https://unpkg.com/@sard/assets@1.2.0/video/video1.mp4',
        },
        {
          url: 'https://unpkg.com/@sard/assets@1.2.0/video/video1.mp4',
        },
      ]}
    />
  )
}
