// packages/sard-taro-demo/src/packageA/pages/steps/demo/Center.tsx
import { useState } from 'react'
import { List, Steps } from 'sard-taro'

export default () => {
  const [current, setCurrent] = useState(1)
  const prevStep = () => {
    setCurrent(current <= 0 ? 3 : current - 1)
  }

  const nextStep = () => {
    setCurrent(current >= 3 ? 0 : current + 1)
  }

  return (
    <List card>
      <List.Item title="上一步" onClick={prevStep} linkable />
      <List.Item title="下一步" onClick={nextStep} linkable />
      <List.Item>
        <Steps current={current} center>
          <Steps.Step>步骤1</Steps.Step>
          <Steps.Step>步骤2</Steps.Step>
          <Steps.Step>步骤3</Steps.Step>
        </Steps>
      </List.Item>
    </List>
  )
}

// src/views/components/steps/demo/Center.vue
<template>
  <s-list card>
    <s-list-item title="上一步" @click="prevStep" arrow hover />
    <s-list-item title="下一步" @click="nextStep" arrow hover />
    <s-list-item>
      <s-steps :current="current" center :item-list="itemList" />
    </s-list-item>
  </s-list>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { type StepsItem } from 'sard'

const current = ref(1)

const itemList: StepsItem[] = [{ name: '步骤1' }, { name: '步骤2' }, { name: '步骤3' }]

const prevStep = () => {
  current.value = current.value <= 0 ? 3 : current.value - 1
}

const nextStep = () => {
  current.value = current.value >= 3 ? 0 : current.value + 1
}
</script>
