// packages/sard/src/components/steps/demo/Center.tsx
/*
### 居中
*/

import { Steps, Button } from 'sard'
import { useState } from 'react'

export default function () {
  const [current, setCurrent] = useState(1)

  return (
    <>
      <Steps current={current} center>
        <Steps.Step>步骤1</Steps.Step>
        <Steps.Step>步骤2</Steps.Step>
        <Steps.Step>步骤3</Steps.Step>
      </Steps>
      <Button onClick={() => setCurrent(current === 0 ? 3 : current - 1)}>
        上一步
      </Button>{' '}
      <Button onClick={() => setCurrent(current === 3 ? 0 : current + 1)}>
        下一步
      </Button>
    </>
  )
}

// src/views/components/steps/demo/Center.vue
<template>
  <s-list card>
    <s-list-item title="上一步" @click="prevStep" arrow hover />
    <s-list-item title="下一步" @click="nextStep" arrow hover />
    <s-list-item>
      <s-steps :current="current" center :item-list="itemList" />
    </s-list-item>
  </s-list>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { type StepsItem } from 'sard'

const current = ref(1)

const itemList: StepsItem[] = [{ name: '步骤1' }, { name: '步骤2' }, { name: '步骤3' }]

const prevStep = () => {
  current.value = current.value <= 0 ? 3 : current.value - 1
}

const nextStep = () => {
  current.value = current.value >= 3 ? 0 : current.value + 1
}
</script>
