// packages/SardDemo/src/packageA/pages/steps/demo/StepStatus.tsx
import { View } from '@tarojs/components'
import { List, Steps } from 'sard'

import '../index.scss'

export default () => {
  return (
    <List card>
      <List.Item>
        <Steps direction="vertical" lineColor="#ddd">
          <Steps.Step status="finish">
            <View>第1节</View>
            <View className="demo-steps-small">已学习</View>
          </Steps.Step>
          <Steps.Step status="process">
            <View>第2节</View>
            <View className="demo-steps-small">学习中</View>
          </Steps.Step>
          <Steps.Step status="wait">
            <View>第3节</View>
            <View className="demo-steps-small">未学习</View>
          </Steps.Step>
          <Steps.Step status="finish">
            <View>第4节</View>
            <View className="demo-steps-small">已学习</View>
          </Steps.Step>
          <Steps.Step status="error">
            <View>第5节</View>
            <View className="demo-steps-small">出错了</View>
          </Steps.Step>
        </Steps>
      </List.Item>
    </List>
  )
}

// src/views/components/steps/demo/StepStatus.vue
<template>
  <s-list card>
    <s-list-item>
      <s-steps :item-list="itemList" direction="vertical" />
    </s-list-item>
  </s-list>
</template>

<script setup lang="ts">
import { type StepsItem } from 'sard'

const itemList: StepsItem[] = [
  { name: '第1节', description: '已学习', status: 'finish' },
  { name: '第2节', description: '学习中', status: 'process' },
  { name: '第3节', description: '未学习', status: 'wait' },
  { name: '第4节', description: '已学习', status: 'finish' },
  { name: '第5节', description: '出错了', status: 'error' },
]
</script>
