// packages/sard/src/components/steps/demo/Vertical.tsx
/*
### 垂直步骤条
*/

import { Steps, Button } from 'sard'
import { useState } from 'react'

export default function () {
  const [current, setCurrent] = useState(1)

  return (
    <>
      <Steps vertical current={current}>
        <Steps.Step>
          <div>步骤1</div>
          <div>这是描述</div>
        </Steps.Step>
        <Steps.Step>
          <div>步骤2</div>
          <div>这是描述</div>
        </Steps.Step>
        <Steps.Step>
          <div>步骤3</div>
          <div>这是描述</div>
        </Steps.Step>
      </Steps>
      <Button onClick={() => setCurrent(current === 0 ? 3 : current - 1)}>
        上一步
      </Button>{' '}
      <Button onClick={() => setCurrent(current === 3 ? 0 : current + 1)}>
        下一步
      </Button>
    </>
  )
}

// src/views/components/steps/demo/Vertical.vue
<template>
  <s-list card>
    <s-list-item title="上一步" @click="prevStep" arrow hover />
    <s-list-item title="下一步" @click="nextStep" arrow hover />
    <s-list-item>
      <s-steps :current="current" :item-list="itemList" direction="vertical" />
    </s-list-item>
  </s-list>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { type StepsItem } from 'sard'

const current = ref(1)

const itemList: StepsItem[] = [
  { name: '步骤1', description: '这是描述' },
  { name: '步骤2', description: '这是描述' },
  { name: '步骤3', description: '这是描述' },
]

const prevStep = () => {
  current.value = current.value <= 0 ? 3 : current.value - 1
}

const nextStep = () => {
  current.value = current.value >= 3 ? 0 : current.value + 1
}
</script>
