// packages/sard-taro/src/pagination/index.tsx
import { FC, ReactNode } from 'react'
import { View } from '@tarojs/components'
import classNames from 'classnames'
import { useBem, useControllableValue } from '../use'
import { getPageRange, minmax } from '../utils'
import useTranslate from '../locale/useTranslate'
import { BaseProps } from '../base'

export interface PaginationProps extends BaseProps {
  total?: number
  pageSize?: number
  current?: number
  defaultCurrent?: number
  pageCount?: number
  pageItemCount?: number
  hideOnSinglePage?: boolean
  type?: 'simple' | 'multi'
  ellipsis?: boolean
  prev?: ReactNode
  next?: ReactNode
  page?: (page: number, active: boolean) => ReactNode
  onChange?: (page: number) => void
}

export const Pagination: FC<PaginationProps> = (props) => {
  const [t] = useTranslate('pagination')

  const {
    className,
    total = 0,
    pageSize = 10,
    current,
    defaultCurrent,
    pageCount,
    pageItemCount = 5,
    hideOnSinglePage = false,
    type = 'multi',
    ellipsis,
    prev,
    next,
    page: pageSlot,
    onChange,
    ...restProps
  } = props

  const [bem] = useBem('pagination')

  const innerPageCount = (pageCount ?? Math.ceil(total / pageSize)) || 1

  const [innerCurrent, setInnerCurrent] = useControllableValue({
    value: current,
    defaultValue: defaultCurrent,
    trigger: onChange,
    initialValue: 1,
    postValue: (value) => minmax(value, 1, innerPageCount),
  })

  const [min, max] = getPageRange(innerCurrent, innerPageCount, pageItemCount)

  const handlePrevClick = () => {
    if (innerCurrent > 1) {
      changeTo(innerCurrent - 1)
    }
  }
  const handleNextClick = () => {
    if (innerCurrent < innerPageCount) {
      changeTo(innerCurrent + 1)
    }
  }
  const handleItemClick = (page: number) => {
    changeTo(page)
  }

  const changeTo = (page: number) => {
    if (page !== innerCurrent) {
      setInnerCurrent(page)
    }
  }

  const renderMulti = () => {
    const length = max - min + 1
    return Array(length)
      .fill(0)
      .map((_, i) => {
        const page = i + min
        return (
          <View
            key={page}
            data-page={page}
            className={classNames(
              bem.e('item'),
              bem.em('item', 'later'),
              bem.em('item', 'current', innerCurrent === page),
            )}
            onClick={() => handleItemClick(page)}
          >
            {ellipsis &&
            ((i === 0 && page !== 1) ||
              (i === length - 1 && page !== innerPageCount))
              ? '...'
              : pageSlot
              ? pageSlot(page, innerCurrent === page)
              : page}
          </View>
        )
      })
  }

  const renderSimple = () => {
    return (
      <View className={bem.e('ratio')}>
        {innerCurrent}/{innerPageCount}
      </View>
    )
  }

  return (
    <>
      {(!hideOnSinglePage || innerPageCount > 1) && (
        <View
          {...restProps}
          className={classNames(bem.b(), bem.m(type), className)}
        >
          <View
            className={classNames(
              bem.e('item'),
              bem.em('item', 'disabled', innerCurrent === 1),
              bem.em('item', 'interactive', innerCurrent !== 1),
              bem.em('item', 'first'),
              bem.e('prev'),
              bem.em('prev', type),
            )}
            onClick={handlePrevClick}
          >
            {prev ?? t('previous')}
          </View>
          {type === 'simple' ? renderSimple() : renderMulti()}
          <View
            className={classNames(
              bem.e('item'),
              bem.em('item', 'disabled', innerCurrent === innerPageCount),
              bem.em('item', 'interactive', innerCurrent !== innerPageCount),
              bem.em('item', 'later'),
              bem.em('item', 'last'),
              bem.e('next'),
              bem.em('next', type),
            )}
            onClick={handleNextClick}
          >
            {next ?? t('next')}
          </View>
        </View>
      )}
    </>
  )
}

export default Pagination

// packages/sard/components/pagination/pagination.vue
<template>
  <div :class="paginationClass">
    <div
      :class="[bem.e('item'), bem.is('disabled', innerCurrent === 1), bem.e('prev')]"
      @click="onPrevClick"
    >
      <slot name="prev">
        {{ t('previous') }}
      </slot>
    </div>
    <div v-if="type === 'simple'" :class="bem.e('ratio')">
      {{ innerCurrent }}/{{ innerPageCount }}
    </div>
    <template v-else>
      <div
        v-for="item in multiItems"
        :key="item.key"
        :class="[bem.e('item'), bem.is('current', item.active)]"
        @click="onItemClick(item.page)"
      >
        {{ item.text }}
      </div>
    </template>
    <div
      :class="[bem.e('item'), bem.is('disabled', innerCurrent === innerPageCount), bem.e('next')]"
      @click="onNextClick"
    >
      <slot name="next">
        {{ t('next') }}
      </slot>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import { createBem, clamp } from '../../utils'
import { useTranslateWithPrefix } from '../../locale'
import {
  type PaginationProps,
  type PaginationSlots,
  type PaginationEmits,
  getPageRange,
  defaultPaginationProps,
} from './common'

const { t } = useTranslateWithPrefix('pagination')

const props = withDefaults(defineProps<PaginationProps>(), defaultPaginationProps)

defineSlots<PaginationSlots>()

const emit = defineEmits<PaginationEmits>()

const bem = createBem('pagination')

const innerPageCount = computed(() => {
  return (props.pageCount ?? Math.ceil(props.total / props.pageSize)) || 1
})

const innerCurrent = ref(props.current)

watch(
  () => props.current,
  () => {
    innerCurrent.value = props.current
  },
)

const range = computed(() => {
  return getPageRange(innerCurrent.value, innerPageCount.value, props.pageButtonCount)
})

const onPrevClick = () => {
  if (innerCurrent.value > 1) {
    changeTo(innerCurrent.value - 1)
  }
}

const onNextClick = () => {
  if (innerCurrent.value < innerPageCount.value) {
    changeTo(innerCurrent.value + 1)
  }
}

const onItemClick = (page: number) => {
  changeTo(page)
}

const changeTo = (page: number) => {
  if (page !== innerCurrent.value) {
    innerCurrent.value = page
    emit('update:current', page)
    emit('change', page)
  }
}

const multiItems = computed(() => {
  if (props.type === 'simple') {
    return []
  }

  const length = range.value[1] - range.value[0] + 1

  return Array(length)
    .fill(0)
    .map((_, i) => {
      let page = i + range.value[0]
      const isPrevMulti = i === 0 && page !== 1
      const isNextMulti = i === length - 1 && page !== innerPageCount.value
      const type = isPrevMulti ? -1 : isNextMulti ? 1 : 0

      page =
        type === 0
          ? page
          : clamp(innerCurrent.value + type * props.multiCount, 1, innerPageCount.value)

      return {
        active: innerCurrent.value === page,
        page,
        key: i,
        text: props.ellipsis && (isPrevMulti || isNextMulti) ? '...' : page,
      }
    })
})

// ============================ style ============================
const paginationClass = computed(() => {
  return [bem.b(), bem.m(props.type)]
})
</script>
