// src/views/components/popover/demo/Dark.vue
<template>
  <s-popover v-model:visible="visible" theme="dark">
    <template #reference>
      <s-button>显示气泡弹出框</s-button>
    </template>
    <s-menu theme="dark" @select="onSelect">
      <s-menu-item :value="1" label="选项1" />
      <s-menu-item :value="2" label="选项2" />
      <s-menu-item :value="3" label="选项3" />
    </s-menu>
  </s-popover>
</template>

<script setup lang="ts">
import { toast, type MenuItemProps } from 'sard'
import { ref } from 'vue'

const visible = ref(false)

const onSelect = (props: MenuItemProps) => {
  visible.value = false
  toast(props.label!)
}
</script>

// packages/sard-taro-demo/src/packageA/pages/popover/demo/Dark.tsx
import { Button, Popover, Toast } from 'sard-taro'

export default () => {
  return (
    <Popover
      theme="dark"
      options={[
        {
          text: '选项1',
        },
        {
          text: '选项2',
        },
        {
          text: '选项3',
        },
      ]}
      reference={<Button>自定义颜色</Button>}
      onSelect={({ text }) => Toast.show(text)}
    />
  )
}
