// src/views/components/dialog/demo/Round.vue
<template>
  <s-list card>
    <s-list-item arrow hover title="显示提示框" @click="showAlert" />
    <s-list-item arrow hover title="显示确定框" @click="showConfirm" />
  </s-list>
</template>

<script setup lang="ts">
import { dialog } from 'sard'

const showAlert = () => {
  dialog.alert({
    title: '提示',
    message: '此功能暂时无法使用',
    buttonType: 'round',
  })
}

const showConfirm = () => {
  dialog.confirm({
    title: '提示',
    message: '确定删除？',
    buttonType: 'round',
  })
}
</script>

// packages/sard/src/components/dialog/demo/Round.tsx
/*
### 圆角按钮
*/

import { Dialog, Button } from 'sard'

export default function () {
  const showAlert = () => {
    Dialog.alert({
      title: '提示',
      message: '此功能暂时无法使用',
      buttonType: 'round',
    })
  }

  const showConfirm = () => {
    Dialog.confirm({
      title: '提示',
      message: '确定删除？',
      buttonType: 'round',
    })
  }

  return (
    <>
      <Button onClick={showAlert}>显示提示框</Button>{' '}
      <Button onClick={showConfirm}>显示确定框</Button>
    </>
  )
}
