// src/views/components/checkbox/index.vue
<template>
  <doc-page gray title="Checkbox 复选框">
    <doc-demo title="基础使用">
      <Basic />
    </doc-demo>

    <doc-demo title="只读和禁用">
      <DisabledReadOnly />
    </doc-demo>

    <doc-demo title="图标大小">
      <Size />
    </doc-demo>

    <doc-demo title="图标颜色">
      <Color />
    </doc-demo>

    <doc-demo title="图标类型">
      <Type />
    </doc-demo>

    <doc-demo title="自定义图标">
      <Icon />
    </doc-demo>

    <doc-demo title="复选框组">
      <Group />
    </doc-demo>

    <doc-demo title="排列方向">
      <Direction />
    </doc-demo>

    <doc-demo title="自动渲染复选框">
      <GroupOptions />
    </doc-demo>

    <doc-demo title="自定义">
      <Custom />
    </doc-demo>

    <doc-demo title="不确定状态">
      <Indeterminate />
    </doc-demo>
  </doc-page>
</template>

<script setup lang="ts">
import Basic from './demo/Basic.vue'
import DisabledReadOnly from './demo/DisabledReadOnly.vue'
import Size from './demo/Size.vue'
import Color from './demo/Color.vue'
import Type from './demo/Type.vue'
import Icon from './demo/Icon.vue'
import Group from './demo/Group.vue'
import Direction from './demo/Direction.vue'
import GroupOptions from './demo/GroupOptions.vue'
import Custom from './demo/Custom.vue'
import Indeterminate from './demo/Indeterminate.vue'
</script>

// packages/sard-taro-demo/src/packageA/pages/checkbox/index.tsx
import Demo from '@/components/demo'
import Page from '@/components/page'

import Basic from './demo/Basic'
import Controllable from './demo/Controllable'
import Disabled from './demo/Disabled'
import Group from './demo/Group'
import Size from './demo/Size'
import Color from './demo/Color'
import Type from './demo/Type'
import Icon from './demo/Icon'

export default () => {
  return (
    <Page className="page-checkbox">
      <Demo title="基础使用">
        <Basic />
      </Demo>

      <Demo title="受控">
        <Controllable />
      </Demo>

      <Demo title="禁用">
        <Disabled />
      </Demo>

      <Demo title="复选框组">
        <Group />
      </Demo>

      <Demo title="图标大小">
        <Size />
      </Demo>

      <Demo title="自定义颜色">
        <Color />
      </Demo>

      <Demo title="图标类型">
        <Type />
      </Demo>

      <Demo title="自定义图标">
        <Icon />
      </Demo>
    </Page>
  )
}
