// packages/sard-taro/src/stepper/index.tsx
import { FC, useRef, useState } from 'react'
import { ITouchEvent, InputProps, View } from '@tarojs/components'
import classNames from 'classnames'
import {
  useBem,
  useControllableValue,
  useEvent,
  useLayoutUpdateEffect,
} from '../use'
import { isNullish, minmax } from '../utils'
import { Icon } from '../icon'
import { Input } from '../input'
import { BaseProps } from '../base'

export interface StepperProps extends Omit<BaseProps, 'children'> {
  inputWidth?: number | string
  value?: number | string
  defaultValue?: number | string
  min?: number
  max?: number
  valueOnClear?: number | null | 'min' | 'max'
  step?: number
  precision?: number
  inputType?: 'number' | 'digit'
  placeholder?: string
  disabled?: boolean
  readOnly?: boolean
  press?: boolean
  pressTime?: number
  interval?: number
  onChange?: (value: number | string) => void
  onBlur?: InputProps['onBlur']
  onFocus?: InputProps['onFocus']
}

export const Stepper: FC<StepperProps> = (props) => {
  const {
    className,
    inputWidth,
    value,
    defaultValue,
    min = Number.MIN_SAFE_INTEGER,
    max = Number.MAX_SAFE_INTEGER,
    valueOnClear = null,
    step = 1,
    precision,
    inputType = 'number',
    placeholder,
    disabled,
    readOnly,
    press = true,
    pressTime = 350,
    interval = 150,
    onChange,
    onBlur,
    onFocus,
    ...restProps
  } = props

  const [bem] = useBem('stepper')

  const [innerValue, setInnerValue] = useControllableValue({
    value,
    defaultValue,
    trigger: onChange,
  })

  const [inputValue, setInputValue] = useState(innerValue)

  const isMin = !isNullish(innerValue) && Number(innerValue) <= min
  const isMax = !isNullish(innerValue) && Number(innerValue) >= max

  useLayoutUpdateEffect(() => {
    const nextInputValue = Number(value)
    setInputValue(isNaN(nextInputValue) ? '' : nextInputValue)
  }, [value])

  const setValueEnsureSafe = (val: number) => {
    setInnerValue(val)
    setInputValue(val)
  }

  const normalizedValue = (value: number) => {
    value = minmax(value, min, max)
    if (precision !== undefined) {
      value = +value.toFixed(precision)
    }
    return value
  }

  // # 输入框
  const getValueOnClear = () => {
    return valueOnClear === 'min'
      ? min
      : valueOnClear === 'max'
      ? max
      : valueOnClear
  }
  const handleInputChange = (value: string) => {
    setInputValue(value)
    if (value === '') {
      setInnerValue(getValueOnClear())
    }
  }
  const handleBlur = (event) => {
    if (inputValue !== '') {
      const nextValue = Number(inputValue)
      if (isNaN(nextValue)) {
        setInputValue('')
        setInnerValue(getValueOnClear())
      } else {
        setValueEnsureSafe(normalizedValue(nextValue))
      }
    }

    onBlur?.(event)
  }

  // # 按钮
  const setByStep = useEvent((delta: number) => {
    setValueEnsureSafe(
      normalizedValue((Number(innerValue) || 0) + step * delta),
    )
  })

  const handleClick = (delta: number, reach: boolean) => {
    if (!disabled && !readOnly && !reach) {
      setByStep(delta)
    }
  }

  const pressTimer = useRef(null)
  const isPressing = useRef(false)

  const handleLongPress = (delta: number) => {
    setTimeout(() => {
      if (isPressing.current) {
        setByStep(delta)
        handleLongPress(delta)
      }
    }, interval)
  }

  const handleTouchStart = useEvent((delta: number) => {
    if (
      !press ||
      disabled ||
      readOnly ||
      (delta === -1 && isMin) ||
      (delta === 1 && isMax)
    ) {
      return
    }

    isPressing.current = false
    clearTimeout(pressTimer.current)

    pressTimer.current = setTimeout(() => {
      isPressing.current = true
      handleLongPress(delta)
    }, pressTime)
  })

  const handleTouchEnd = useEvent((event: ITouchEvent) => {
    clearTimeout(pressTimer.current)

    if (isPressing.current) {
      isPressing.current = false
      event.preventDefault()
    }
  })

  const StepperClass = classNames(
    bem.b(),
    bem.m('disabled', disabled),
    bem.m('readonly', readOnly),
    className,
  )

  const renderButton = (
    delta: number,
    icon: string,
    reach: boolean,
    cls: string,
  ) => {
    return (
      <View
        className={classNames(
          bem.e('button'),
          bem.e(cls),
          bem.em('button', 'disabled', disabled || reach),
          bem.em('button', 'interactive', !reach && !disabled && !readOnly),
        )}
        onClick={() => handleClick(delta, reach)}
        onTouchStart={() => handleTouchStart(delta)}
        onTouchEnd={handleTouchEnd}
        onTouchCancel={handleTouchEnd}
      >
        <Icon name={icon}></Icon>
      </View>
    )
  }

  return (
    <View {...restProps} className={StepperClass}>
      {renderButton(-1, 'minus', isMin, 'decrease')}
      <Input
        type={inputType}
        className={bem.e('input')}
        placeholder={placeholder}
        style={{ width: inputWidth }}
        value={String(inputValue ?? '')}
        onChange={handleInputChange}
        onBlur={handleBlur}
        onFocus={onFocus}
        disabled={disabled}
        readOnly={readOnly}
      />
      {renderButton(1, 'plus', isMax, 'increase')}
    </View>
  )
}

export default Stepper

// packages/sard/components/stepper/stepper.vue
<template>
  <div :class="stepperClass">
    <div
      :class="[
        bem.e('button'),
        bem.is('disabled', isDisabled || isMin),
        bem.is('readonly', isReadonly),
        bem.em('button', 'decrease'),
      ]"
      @click="onButtonClick(-1, isMin)"
      @touchstart="onDecTouchStart"
      @touchmove="onDecTouchMove"
      @touchend="onDecTouchEnd"
      @touchcancel="onDecTouchEnd"
      @pointerdown="onDecPointerDown"
    >
      <Minus />
    </div>
    <Input
      v-model="inputValue"
      :class="bem.e('input')"
      :type="inputType"
      :placeholder="placeholder"
      :disabled="isDisabled || isReadonly"
      :validate-event="validateEvent"
      :precision="precision"
      :min="min"
      :max="max"
      @change="onChange"
      @blur="onBlur"
      @focus="onFocus"
    />
    <div
      :class="[
        bem.e('button'),
        bem.is('disabled', isDisabled || isMax),
        bem.is('readonly', isReadonly),
        bem.em('button', 'increase'),
      ]"
      @click="onButtonClick(1, isMax)"
      @touchstart="onIncTouchStart"
      @touchmove="onIncTouchMove"
      @touchend="onIncTouchEnd"
      @touchcancel="onIncTouchEnd"
      @pointerdown="onIncPointerDown"
    >
      <Plus />
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, ref, useModel, watch } from 'vue'
import { createBem, isNullish, clamp } from '../../utils'
import Input from '../input/input.vue'
import { useFormContext } from '../form/common'
import { type StepperProps, type StepperEmits, defaultStepperProps } from './common'
import { usePointerDown, useSimulatedPress } from '../../use'
import { Minus, Plus } from '@sard/icons'

const props = withDefaults(defineProps<StepperProps>(), defaultStepperProps)

const emit = defineEmits<StepperEmits>()

const bem = createBem('stepper')

const formContext = useFormContext()

const isDisabled = computed(() => {
  return formContext?.disabled || props.disabled
})

const isReadonly = computed(() => {
  return formContext?.readonly || props.readonly
})

// ============================ 输入框 ============================
const inputValue = ref(props.modelValue)

watch(
  () => props.modelValue,
  () => {
    inputValue.value = props.modelValue
  },
)

const innerValue = useModel(props, 'modelValue')

const setValue = (value: string | number) => {
  inputValue.value = value
  innerValue.value = value
  emit('change', value)
}

const normalizedValue = (value: number) => {
  if (isNaN(value)) return 0
  value = clamp(value, props.min, props.max)
  if (props.precision !== undefined) {
    value = +value.toFixed(props.precision)
  }
  return value
}

const setValueByStep = (delta: number) => {
  setValue(normalizedValue((Number(innerValue.value) || 0) + props.step * delta))
}

const onChange = (value: string | number) => {
  if (value === '') {
    setValue(getValueOnClear())
  } else {
    setValue(normalizedValue(Number(value)))
  }
}

const getValueOnClear = () => {
  return props.valueOnClear === 'min'
    ? props.min
    : props.valueOnClear === 'max'
      ? props.max
      : props.valueOnClear
}

const onBlur = (event: FocusEvent) => {
  emit('blur', event)
}

const onFocus = (event: FocusEvent) => {
  emit('focus', event)
}

// ============================ 按钮 ============================
const isMin = computed(() => {
  return !isNullish(innerValue.value) && Number(innerValue.value) <= props.min
})
const isMax = computed(() => {
  return !isNullish(innerValue.value) && Number(innerValue.value) >= props.max
})

const onButtonClick = (delta: number, arrived: boolean) => {
  if (!isDisabled.value && !isReadonly.value && !arrived) {
    setValueByStep(delta)
  }
}

// ============================ 长按 ============================

let pressDelta: -1 | 0 | 1 = 0

const tick = () => {
  if (pressDelta) {
    setValueByStep(pressDelta)
    setTimeout(() => {
      tick()
    }, props.interval)
  }
}

const onPressStart = (delta: -1 | 1) => {
  if (
    !!pressDelta ||
    !props.press ||
    isDisabled.value ||
    isReadonly.value ||
    (delta === -1 && isMin.value) ||
    (delta === 1 && isMax.value)
  ) {
    return
  }
  pressDelta = delta
  tick()
}

const onPressEnd = () => {
  pressDelta = 0
}

// ============================ decrease ============================
const onDecTouchStart = (event: TouchEvent) => {
  onDecSimulatedPressTouchStart(event)
}

const onDecTouchMove = (event: TouchEvent) => {
  onDecSimulatedPressTouchMove(event)
}

const onDecTouchEnd = () => {
  onDecSimulatedPressTouchEnd()
}

const onDecPointerDown = usePointerDown(onDecTouchStart, onDecTouchMove, onDecTouchEnd)

const [onDecSimulatedPressTouchStart, onDecSimulatedPressTouchMove, onDecSimulatedPressTouchEnd] =
  useSimulatedPress({
    start: () => {
      onPressStart(-1)
    },
    end: onPressEnd,
    duration: props.pressTime,
  })

// ============================ increase ============================
const onIncTouchStart = (event: TouchEvent) => {
  onIncSimulatedPressTouchStart(event)
}

const onIncTouchMove = (event: TouchEvent) => {
  onIncSimulatedPressTouchMove(event)
}

const onIncTouchEnd = () => {
  onIncSimulatedPressTouchEnd()
}

const onIncPointerDown = usePointerDown(onIncTouchStart, onIncTouchMove, onIncTouchEnd)

const [onIncSimulatedPressTouchStart, onIncSimulatedPressTouchMove, onIncSimulatedPressTouchEnd] =
  useSimulatedPress({
    start: () => {
      onPressStart(1)
    },
    end: onPressEnd,
    duration: props.pressTime,
  })

// ============================ style ============================
const stepperClass = computed(() => {
  return [
    bem.b(),
    bem.m(props.size),
    bem.m('disabled', isDisabled.value),
    bem.m('readonly', isReadonly.value),
    bem.m(props.variant),
  ]
})
</script>
