// src/views/components/dialog/index.vue
<template>
  <doc-page gray title="Dialog 对话框">
    <doc-demo title="基础使用">
      <Basic />
    </doc-demo>

    <doc-demo title="异步关闭">
      <AsyncClose />
    </doc-demo>

    <doc-demo title="圆角按钮">
      <Round />
    </doc-demo>

    <doc-demo title="有头部的">
      <Headed />
    </doc-demo>

    <doc-demo title="自定义内容">
      <Content />
    </doc-demo>

    <doc-demo title="内容中包含弹出框">
      <PopupContent />
    </doc-demo>

    <doc-demo title="自定义按钮属性">
      <ButtonProps />
    </doc-demo>
  </doc-page>
</template>

<script setup lang="ts">
import Basic from './demo/Basic.vue'
import AsyncClose from './demo/AsyncClose.vue'
import Round from './demo/Round.vue'
import Headed from './demo/Headed.vue'
import Content from './demo/Content.vue'
import ButtonProps from './demo/ButtonProps.vue'
import PopupContent from './demo/PopupContent.vue'
</script>

// packages/sard-taro-demo/src/packageA/pages/dialog/index.tsx
import Demo from '@/components/demo'
import Page from '@/components/page'

import Basic from './demo/Basic'
import Imperative from './demo/Imperative'
import AsyncClose from './demo/AsyncClose'
import Round from './demo/Round'
import Headed from './demo/Headed'
import Content from './demo/Content'

export default () => {
  return (
    <Page className="page-dialog">
      <Demo title="基础使用" full>
        <Basic />
      </Demo>

      <Demo title="命令式" full>
        <Imperative />
      </Demo>

      <Demo title="异步关闭" full>
        <AsyncClose />
      </Demo>

      <Demo title="圆角按钮" full>
        <Round />
      </Demo>

      <Demo title="有头部的" full>
        <Headed />
      </Demo>

      <Demo title="自定义内容" full>
        <Content />
      </Demo>
    </Page>
  )
}
