// src/views/components/avatar/demo/Extra.vue
<template>
  <s-avatar shape="square">
    <template #extra>
      <s-badge fixed :value="5" />
    </template>
  </s-avatar>

  <s-avatar style="margin-top: 10px">
    <template #extra>
      <s-badge fixed :value="5" style="top: 14.6447%; right: 14.6447%" />
    </template>
  </s-avatar>
</template>

// packages/sard-taro-demo/src/packageA/pages/avatar/demo/Extra.tsx
import { Avatar, Badge, Space } from 'sard-taro'

export default () => {
  return (
    <Space>
      <Avatar shape="square" extra={<Badge fixed value={5} />} />

      <Avatar
        extra={
          <Badge
            fixed
            value={5}
            style={{ top: '14.6447%', right: '14.6447%' }}
          />
        }
      />
    </Space>
  )
}
