// packages/SardDemo/src/sard/popout/index.tsx
import { FC, ReactNode, useState } from 'react'
import classNames from 'classnames'
import { ITouchEvent, View } from '@tarojs/components'
import { Popup, PopupProps } from '../popup'
import { Button, ButtonProps } from '../button'
import { isFunction, isNullish, noop } from '../utils'
import { useEvent, useControllableValue, useBem } from '../use'
import useTranslate from '../locale/useTranslate'
import Ellipsis from '../ellipsis'
import SafeArea from '../safe-area'

const CLOSE = 'close'
const CANCEL = 'cancel'
const CONFIRM = 'confirm'

export type PopoutCloseType = 'close' | 'cancel' | 'confirm'

export interface PopoutProps extends PopupProps {
  title?: ReactNode
  showCancel?: boolean
  cancelText?: ReactNode
  cancelProps?: ButtonProps
  showConfirm?: boolean
  confirmText?: ReactNode
  confirmProps?: ButtonProps
  showClose?: boolean
  showFooter?: boolean
  type?: 'compact' | 'loose'
  visible?: boolean
  defaultVisible?: boolean
  onVisible?: (visible: boolean) => void
  maskClosable?: boolean
  onClose?: () => void | Promise<any>
  onCancel?: () => void | Promise<any>
  onConfirm?: () => void | Promise<any>
}

export const Popout: FC<PopoutProps> = (props) => {
  const { t } = useTranslate('popout')

  const {
    className,
    style,
    children,

    contentClass,
    contentStyle,
    onMaskClick,

    title,
    showCancel = false,
    cancelText = t('cancel'),
    cancelProps,
    showConfirm = true,
    confirmText = t('confirm'),
    confirmProps,
    showClose = true,
    showFooter = true,
    type = 'loose',
    visible,
    defaultVisible,
    onVisible,
    maskClosable = true,
    onClose,
    onCancel,
    onConfirm,
    ...restProps
  } = props

  const [bem] = useBem('popout')

  const [innerVisible, setInnerVisible] = useControllableValue({
    value: visible,
    defaultValue: defaultVisible,
    trigger: onVisible,
    initialValue: false,
  })

  const [loading, setLoading] = useState({
    cancel: false,
    confirm: false,
  })

  const perhapsClose = (
    type: PopoutCloseType,
    callback?: () => void | Promise<any>,
  ) => {
    function toggleLoading(play: boolean) {
      setLoading((loading) => ({
        ...loading,
        [type]: play,
      }))
    }

    if (isFunction(callback)) {
      const result = callback()
      if (result instanceof Promise) {
        toggleLoading(true)

        return result
          .then(() => {
            setInnerVisible(false)
          })
          .catch(noop)
          .finally(() => {
            toggleLoading(false)
          })
      }
    }

    setInnerVisible(false)
  }

  const handleRequestClose = useEvent(() => {
    setInnerVisible(false)
  })

  const handleMaskClick = useEvent((event: ITouchEvent) => {
    onMaskClick?.(event)

    if (maskClosable) {
      perhapsClose(CLOSE, onClose)
    }
  })

  const handleClose = useEvent(() => {
    perhapsClose(CLOSE, onClose)
  })

  const handleCancel = useEvent(() => {
    perhapsClose(CANCEL, onCancel)
  })

  const handleConfirm = useEvent(() => {
    perhapsClose(CONFIRM, onConfirm)
  })

  const renderCancelButton = (
    type: ButtonProps['type'],
    theme: ButtonProps['theme'],
    round: boolean,
    placement: string,
  ) => {
    return (
      <Button
        className={classNames(
          bem.e(`${placement}-cancel`),
          bem.e(`${placement}-button`),
        )}
        type={type}
        theme={theme}
        round={round}
        loading={loading.cancel}
        {...cancelProps}
        onClick={handleCancel}
      >
        {cancelText}
      </Button>
    )
  }

  const renderConfirmButton = (
    type: ButtonProps['type'],
    round: boolean,
    placement: string,
  ) => {
    return (
      <Button
        className={classNames(
          bem.e(`${placement}-confirm`),
          bem.e(`${placement}-button`),
        )}
        type={type}
        theme="primary"
        round={round}
        loading={loading.confirm}
        {...confirmProps}
        onClick={handleConfirm}
      >
        {confirmText}
      </Button>
    )
  }

  const renderHeader = () => {
    return (
      <View className={classNames(bem.e('header'), bem.em('header', type))}>
        {type === 'compact' && (
          <View className={bem.e('button-wrap')}>
            {renderCancelButton('pale-text', 'secondary', false, 'header')}
          </View>
        )}

        {!isNullish(title) && (
          <Ellipsis className={bem.e('title')}>{title}</Ellipsis>
        )}

        {type === 'compact' && (
          <View className={bem.e('button-wrap')}>
            {renderConfirmButton('pale-text', false, 'header')}
          </View>
        )}

        {type === 'loose' && showClose && (
          <Button
            className={bem.e('close')}
            type="pale-text"
            theme="secondary"
            size="large"
            onClick={handleClose}
            iconProps={{
              name: 'close',
            }}
          />
        )}
      </View>
    )
  }

  const renderFooter = () => {
    return (
      showFooter &&
      type === 'loose' && (
        <View className={bem.e('footer')}>
          {showCancel && renderCancelButton('pale', 'primary', true, 'footer')}
          {showConfirm && renderConfirmButton('default', true, 'footer')}
        </View>
      )
    )
  }

  return (
    <Popup
      {...restProps}
      effect="slide-bottom"
      visible={innerVisible}
      className={classNames(bem.e('popup'), className)}
      style={style}
      contentClass={classNames(bem.b(), contentClass)}
      contentStyle={contentStyle}
      onMaskClick={handleMaskClick}
      onRequestClose={handleRequestClose}
    >
      {renderHeader()}
      {children}
      {renderFooter()}
      <SafeArea direction="bottom" />
    </Popup>
  )
}

export default Popout

// packages/sard/components/popout/popout.vue
<template>
  <Popup
    effect="slide-bottom"
    :visible="visible"
    :overlay="overlay"
    :overlay-class="overlayClass"
    :overlay-style="overlayStyle"
    :background="background"
    :transparent="transparent"
    :destroy-on-close="destroyOnClose"
    :lazy="lazy"
    @overlay-click="onOverlayClick"
    @visible-hook="onVisibleHook"
  >
    <div :class="popoutClass" @transitionend.stop>
      <div :class="[bem.e('header'), bem.em('header', props.type)]">
        <div
          v-if="type === 'compact' && mergedShowCancel"
          :class="[bem.e('button-wrap'), bem.em('button-wrap', 'start')]"
        >
          <slot
            name="cancel"
            :on-click="onCancel"
            :loading="loading.cancel"
            :text="mergedCancelText"
          >
            <Button
              variant="link"
              color="secondary"
              :loading="loading.cancel"
              block
              @click="onCancel"
            >
              {{ mergedCancelText }}
            </Button>
          </slot>
        </div>
        <slot name="title-prepend"></slot>
        <div :class="bem.e('title')">
          <slot name="title">
            <span :class="bem.e('title-text')">{{ title }}</span>
          </slot>
        </div>
        <div
          v-if="type === 'compact' && showConfirm"
          :class="[bem.e('button-wrap'), bem.em('button-wrap', 'end')]"
        >
          <slot
            name="confirm"
            :on-click="onConfirm"
            :disabled="confirmDisabled"
            :loading="loading.confirm"
            :text="mergedConfirmText"
          >
            <Button
              variant="link"
              color="primary"
              :loading="loading.confirm"
              :disabled="confirmDisabled"
              block
              @click="onConfirm"
            >
              {{ mergedConfirmText }}
            </Button>
          </slot>
        </div>
        <div v-if="type === 'loose' && showClose" :class="bem.e('close')" @click="onCloseClick">
          <Button variant="link" color="secondary" size="large" block>
            <Close />
          </Button>
        </div>
      </div>
      <slot></slot>
      <div v-if="showFooter && type === 'loose'" :class="bem.e('footer')">
        <slot
          v-if="mergedShowCancel"
          name="cancel"
          :on-click="onCancel"
          :loading="loading.cancel"
          :text="mergedCancelText"
        >
          <Button
            variant="filled"
            color="primary"
            round
            :loading="loading.cancel"
            block
            @click="onCancel"
          >
            {{ mergedCancelText }}
          </Button>
        </slot>
        <slot
          v-if="showConfirm"
          name="confirm"
          :on-click="onConfirm"
          :disabled="confirmDisabled"
          :loading="loading.confirm"
          :text="mergedConfirmText"
        >
          <Button
            variant="solid"
            color="primary"
            round
            :loading="loading.confirm"
            :disabled="confirmDisabled"
            block
            @click="onConfirm"
          >
            {{ mergedConfirmText }}
          </Button>
        </slot>
      </div>
    </div>
  </Popup>
</template>

<script setup lang="ts">
import { computed, reactive, readonly, ref, useModel, watch } from 'vue'
import { createBem, noop, isFunction, isBoolean } from '../../utils'
import Popup from '../popup/popup.vue'
import Button from '../button/button.vue'
import { usePopupVisibleHookProvide } from '../popup/common'
import { useTranslateWithPrefix } from '../../locale'
import { type PopoutProps, type PopoutSlots, type PopoutEmits, defaultPopoutProps } from './common'
import { Close } from '@sard/icons'
import type { MotionHookName } from '../motion/common'

const props = withDefaults(defineProps<PopoutProps>(), defaultPopoutProps)

defineSlots<PopoutSlots>()

const emit = defineEmits<PopoutEmits>()

const bem = createBem('popout')

const { t } = useTranslateWithPrefix('popout')

const mergedShowCancel = computed(() => {
  return isBoolean(props.showCancel) ? props.showCancel : props.type === 'loose' ? false : true
})

// ============================ visible ============================
const innerVisible = useModel(props, 'visible')

const callVisibleHook = usePopupVisibleHookProvide()

const onVisibleHook = (name: MotionHookName, el: Element) => {
  callVisibleHook(name)
  emit('visible-hook', name, el)
  emit(name as any, el)
}

const loading = reactive({
  cancel: false,
  confirm: false,
  close: false,
})

const readonlyLoading = readonly(loading)

const asyncSet = new Set<{ valid: boolean }>()

watch(
  innerVisible,
  () => {
    if (innerVisible.value === false) {
      asyncSet.forEach((obj) => {
        obj.valid = false
      })
      Object.assign(loading, {
        cancel: false,
        confirm: false,
        close: false,
      })
    }
  },
  {
    flush: 'sync',
  },
)

const perhapsClose = (type: 'close' | 'cancel' | 'confirm') => {
  emit(type as any)
  if (isFunction(props.beforeClose)) {
    const result = props.beforeClose(type, readonlyLoading)
    if (result instanceof Promise) {
      loading[type] = true

      const obj = {
        valid: true,
      }
      asyncSet.add(obj)

      return result
        .then(() => {
          if (obj.valid) {
            innerVisible.value = false
          }
        })
        .catch(noop)
        .finally(() => {
          loading[type] = false
          asyncSet.delete(obj)
        })
    } else if (result === false) {
      return
    }
  }

  innerVisible.value = false
}

const onOverlayClick = () => {
  if (props.overlayClosable) {
    perhapsClose('close')
  }
}

const onCloseClick = () => {
  perhapsClose('close')
}

const onConfirm = () => {
  perhapsClose('confirm')
}

const onCancel = () => {
  perhapsClose('cancel')
}

const mergedConfirmText = computed(() => {
  return props.confirmText || t('confirm')
})

const mergedCancelText = computed(() => {
  return props.cancelText || t('cancel')
})

// ============================ style ============================
const popoutClass = computed(() => {
  return [bem.b(), bem.m('divided', props.showShadow)]
})
</script>
