// packages/sard/src/components/accordion/demo/Multiple.tsx
/*
### 展开多个
*/

import { Accordion } from 'sard'

export default function () {
  return (
    <>
      <Accordion multiple defaultActiveKey={[0, 1]}>
        <Accordion.Item title="标题1">内容1</Accordion.Item>
        <Accordion.Item title="标题2">内容2</Accordion.Item>
        <Accordion.Item title="标题3">内容3</Accordion.Item>
      </Accordion>
    </>
  )
}

// src/views/components/accordion/demo/Multiple.vue
<template>
  <s-accordion v-model="value" multiple>
    <s-accordion-item title="标题1" name="1">内容1</s-accordion-item>
    <s-accordion-item title="标题2" name="2">内容2</s-accordion-item>
    <s-accordion-item title="标题3" name="3">内容3</s-accordion-item>
  </s-accordion>
</template>

<script setup lang="ts">
import { ref } from 'vue'

const value = ref(['1'])
</script>
