// packages/sard-taro/src/steps/Step.tsx
import { FC, ReactNode } from 'react'
import { ITouchEvent, View } from '@tarojs/components'
import classNames from 'classnames'

import { StepsStatus } from './index'
import { Icon } from '../icon'
import { BaseProps } from '../base'
import { useBem } from '../use'

export interface StepsStepProps extends Omit<BaseProps, 'children'> {
  children?: ReactNode | ((status: StepsStatus) => ReactNode)
  status?: StepsStatus
  lineColor?: string
  disabled?: boolean
  icon?: ReactNode | ((status: StepsStatus) => ReactNode)
  onClick?: (event: ITouchEvent) => void
  _position?: number
  first?: boolean
  last?: boolean
  center?: boolean
  vertical?: boolean
  clickable?: boolean
}

const mapStatusIcon = {
  finish: 'check-circle-fill',
  process: 'circle',
  wait: 'circle',
  error: 'x-circle',
}

function getPosition(num: number) {
  return num < 0 ? 'behind' : num === 0 ? 'self' : 'front'
}

export const StepsStep: FC<StepsStepProps> = (props) => {
  const {
    className,
    children,
    icon,
    status = 'wait',
    lineColor,
    disabled = false,
    onClick,
    _position,
    first,
    last,
    center,
    vertical,
    clickable,
    ...restProps
  } = props

  const [bem] = useBem('steps')

  const position = getPosition(_position)

  const handleClick = (event: ITouchEvent) => {
    if (!disabled) {
      onClick?.(event)
    }
  }

  const stepClass = classNames(
    bem.e('step'),
    bem.em('step', 'last', last),
    bem.m(status),
    bem.m(`position-${position}`),
    bem.em('step', 'center', center),
    bem.em('step', 'center-last', center && last),
    bem.em('step', 'vertical', vertical),
    bem.em('step', 'vertical-last', vertical && last),
    bem.em('step', 'vertical-center', vertical && center),
    bem.em('step', 'vertical-center-last', vertical && center && last),
    bem.em('step', 'interactive', clickable && !disabled),
    bem.em('step', 'disabled', disabled),
    className,
  )

  const lineStyle = {
    backgroundColor: lineColor,
  }

  const lineClass = classNames(
    bem.e('line'),
    bem.em('line', 'behind', position === 'behind'),
    bem.em('line', 'last', last),
    bem.em('line', 'center-last', center && last),
    bem.em('line', 'vertical', vertical),
    bem.em('line', 'vertical-center-last', vertical && center && last),
  )

  return (
    <View {...restProps} className={stepClass} onClick={handleClick}>
      <View
        className={classNames(
          bem.e('header'),
          bem.em('header', 'vertical', vertical),
          bem.em('header', 'vertical-center', vertical && center),
        )}
      >
        <View
          className={classNames(
            lineClass,
            bem.e('line-before'),
            bem.em('line-before', 'self', position === 'self'),
            bem.em('line-before', 'first', first),
            bem.em('line-before', 'center', center),
            bem.em('line-before', 'vertical-center', vertical && center),
          )}
          style={lineStyle}
        ></View>
        <View className={classNames(bem.e('icon'), bem.em('icon', status))}>
          {typeof icon === 'function'
            ? icon(status)
            : icon ?? <Icon name={mapStatusIcon[status]}></Icon>}
        </View>
        <View
          className={classNames(
            lineClass,
            bem.e('line-after'),
            bem.em('line-after', 'last', last),
            bem.em('line-after', 'center', center),
            bem.em('line-after', 'vertical-center', vertical && center),
          )}
          style={lineStyle}
        ></View>
      </View>
      <View
        className={classNames(
          bem.e('body'),
          bem.em('body', 'vertical', vertical),
        )}
      >
        {typeof children === 'function' ? children(status) : children}
      </View>
    </View>
  )
}

export default StepsStep

// packages/sard/components/steps/step.vue
<template>
  <div :class="stepClass">
    <div :class="bem.e('header')">
      <div :class="[bem.e('line'), bem.e('line-before')]"></div>
      <div :class="bem.e('icon')">
        <slot name="icon" :status="currentStatus">
          <CheckCircleFill v-if="currentStatus === 'finish'" />
          <Circle v-else-if="currentStatus === 'process'" />
          <Circle v-else-if="currentStatus === 'wait'" />
          <XCircle v-else-if="currentStatus === 'error'" />
        </slot>
      </div>
      <div :class="[bem.e('line'), bem.e('line-after')]"></div>
    </div>
    <div :class="bem.e('body')">
      <slot :status="currentStatus">
        <div :class="bem.e('name')">{{ name }}</div>
        <div v-if="description" :class="bem.e('description')">
          {{ description }}
        </div>
      </slot>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, inject } from 'vue'
import { createBem } from '../../utils'
import { type StepProps, type StepSlots, type StepEmits, type StepExpose } from './common'
import { stepsContextKey } from './common'
import { CheckCircleFill, Circle, XCircle } from '@sard/icons'

const props = withDefaults(defineProps<StepProps>(), {})

defineSlots<StepSlots>()

defineEmits<StepEmits>()

const bem = createBem('step')

const context = inject(stepsContextKey)!

if (!context) {
  throw new Error('Step must be included in Steps.')
}

const currentStatus = computed(() => {
  return (
    props.status ??
    (props.index < context.current
      ? 'finish'
      : props.index === context.current
        ? (context.status ?? 'process')
        : 'wait')
  )
})

const position = computed(() => {
  return props.index < context.current
    ? 'behind'
    : context.current === props.index
      ? 'self'
      : 'front'
})

// ============================ style ============================
const stepClass = computed(() => {
  return [
    bem.b(),
    bem.m('center', context.center),
    bem.m(currentStatus.value),
    bem.m(position.value),
    bem.m(context.direction),
    bem.m('reverse', context.reverse),
  ]
})

defineExpose<StepExpose>({})
</script>
