// src/views/components/cascader/demo/OptionTop.vue
<template>
  <s-list card>
    <s-list-item>
      <s-cascader
        :options="regionData"
        :field-keys="{ label: 'name', value: 'code' }"
        @update:modelValue="onChange"
      >
        <template #top="{ tabIndex }">
          <div
            :style="{
              padding: '8px 16px',
              backgroundColor: 'rgba(var(--s-color-primary-rgb), 0.1)',
              color: 'var(--s-color-primary)',
            }"
          >
            当前为第{{ tabIndex + 1 }}级
          </div>
        </template>
      </s-cascader>
    </s-list-item>
  </s-list>
</template>

<script setup lang="ts">
import { getRegionData, type Node } from 'region-data'
import { toast } from 'sard'

const regionData = getRegionData()

const onChange = (_: any, selectedOptions: Node[]) => {
  toast(selectedOptions.map((option) => option.name).join('/'))
}
</script>

// packages/sard-taro-demo/src/packageA/pages/cascader/demo/OptionTop.tsx
import { Cascader, Cell, PopoutInput } from 'sard-taro'
import { getRegionData } from 'region-data'
import { View } from '@tarojs/components'

const regionData = getRegionData()

export default () => {
  return (
    <Cell.Group card>
      <Cell>
        <PopoutInput title="请选择" inputProps={{ placeholder: '请选择' }}>
          <Cascader
            options={regionData}
            fieldNames={{ label: 'name', value: 'code' }}
            optionTop={(columnIndex) => (
              <View
                style={{
                  padding: '8px var(--sar-cascader-option-padding-x)',
                  backgroundColor: 'rgba(var(--sar-warning-rgb), 0.1)',
                  color: 'var(--sar-warning-text)',
                }}
              >
                当前为第{columnIndex + 1}级
              </View>
            )}
          />
        </PopoutInput>
      </Cell>
    </Cell.Group>
  )
}
