// packages/sard/src/components/action-sheet/demo/Cancel.tsx
/*
### 取消按钮
*/

import { ActionSheet, ActionSheetItemProps, Button } from 'sard'
import { useState } from 'react'

export default function () {
  const [visible, setVisible] = useState(false)
  const itemList = [
    {
      title: '动作1',
    },
    {
      title: '动作2',
    },
    {
      title: '动作3',
    },
  ]

  const handleSelect = (item: ActionSheetItemProps, index: number) => {
    console.log(item, index)
  }

  return (
    <>
      <Button onClick={() => setVisible(true)}>显示动作面板</Button>
      <ActionSheet
        visible={visible}
        itemList={itemList}
        cancel="取消"
        actionClosable
        onSelect={handleSelect}
        onClose={setVisible}
      />
    </>
  )
}

// src/views/components/action-sheet/demo/Cancel.vue
<template>
  <s-button @click="visible = true">显示</s-button>
  <s-action-sheet v-model:visible="visible" show-cancel :item-list="itemList" @select="onSelect" />
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { toast, type ActionSheetItemProps } from 'sard'

const visible = ref(false)

const itemList = ref([{ label: '选项1' }, { label: '选项2' }, { label: '选项3' }])

const onSelect = (item: ActionSheetItemProps) => {
  toast(item.label)
}
</script>
