// packages/sard/src/components/action-sheet/demo/Status.tsx
/*
### 状态
*/

import { ActionSheet, ActionSheetItemProps, Button } from 'sard'
import { useState } from 'react'

export default function () {
  const [visible, setVisible] = useState(false)
  const itemList = [
    {
      title: '动作1',
      color: 'red',
    },
    {
      title: '动作2',
      disabled: true,
    },
    {
      title: '动作3',
      loading: true,
    },
  ]

  const handleSelect = (item: ActionSheetItemProps, index: number) => {
    console.log(item, index)
  }

  return (
    <>
      <Button onClick={() => setVisible(true)}>显示动作面板</Button>
      <ActionSheet
        visible={visible}
        itemList={itemList}
        cancel="取消"
        actionClosable
        onSelect={handleSelect}
        onClose={setVisible}
      />
    </>
  )
}

// src/views/components/action-sheet/demo/Status.vue
<template>
  <s-button @click="visible = true">显示</s-button>
  <s-action-sheet
    v-model:visible="visible"
    cancel="取消"
    :item-list="itemList"
    @select="onSelect"
  />
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { toast, type ActionSheetItemProps } from 'sard'

const visible = ref(false)
const itemList = ref([
  { label: '选项1', color: 'var(--s-color-danger)' },
  { label: '选项2', disabled: true },
  { label: '选项3', loading: true },
])

const onSelect = (item: ActionSheetItemProps) => {
  toast(item.label)
}
</script>
