// src/views/components/list/demo/Slot.vue
<template>
  <s-list>
    <s-list-item title="标题">
      <template #value>
        <s-switch :model-value="true" />
      </template>
    </s-list-item>
    <s-list-item arrow hover title="标题">
      <template #value>
        <s-badge :value="20" />
      </template>
    </s-list-item>
    <s-list-item title="音量">
      <template #value>
        <s-slider style="width: 260px" :value="50" />
      </template>
    </s-list-item>

    <s-list-item>
      <div
        style="display: flex; flex-direction: column; align-items: center; padding: 20; gap: 5px"
      >
        <img :src="logo" style="width: 48px; height: 48px" />
        <div style="font-size: 20px">这是标题</div>
        <div>
          这是一段很长的描述这是一段很长的描述这是一段很长的描述这是一段很长的描述这是一段很长的描述这是一段很长的描述...
        </div>
      </div>
    </s-list-item>
    <s-list-item>
      <s-input v-model="name" inlaid placeholder="请输入用户名" />
    </s-list-item>
    <s-list-item>
      <s-input v-model="pwd" inlaid type="password" placeholder="请输入密码" />
    </s-list-item>
  </s-list>
</template>

<script setup lang="ts">
import logo from '@/assets/logo.svg'
import { ref } from 'vue'

const name = ref('')
const pwd = ref('')
</script>

// packages/sard-taro-demo/src/packageA/pages/cell/demo/Slot.tsx
import { Image, View } from '@tarojs/components'
import { Cell, Input, Slider, Switch } from 'sard-taro'

import logo from '@/static/logo.svg'

export default () => {
  return (
    <Cell.Group>
      <Cell title="无线局域网" value={<Switch defaultChecked></Switch>} />
      <Cell
        title="音量"
        bodyStyle={{ maxWidth: 40 }}
        footer={<Slider style={{ width: '100%' }} defaultValue={50}></Slider>}
      />
      <Cell>
        <View style={{ padding: 20 }}>
          <View style={{ textAlign: 'center' }}>
            <Image src={logo} style={{ width: 48 }}></Image>
            <View style={{ fontSize: 20 }}>这是一句简洁</View>
          </View>
          <View
            style={{
              fontSize: 14,
              marginTop: 10,
              color: 'var(--sar-secondary-color)',
            }}
          >
            这是一段很长的描述这是一段很长的描述这是一段很长的描述这是一段很长的描述这是一段很长的描述这是一段很长的描述...
          </View>
        </View>
      </Cell>
      <Cell
        bodyStyle={{ maxWidth: 80 }}
        title="用户名"
        footer={<Input inlaid placeholder="请输入用户名" />}
      />
      <Cell
        bodyStyle={{ maxWidth: 80 }}
        title="密码"
        footer={<Input inlaid type="password" placeholder="请输入密码" />}
      />
    </Cell.Group>
  )
}
