// src/views/components/count-down/demo/Captcha.vue
<template>
  <s-input v-model="value" placeholder="请输入验证码">
    <template #append>
      <s-button variant="link" compact :loading="loading" :disabled="disabled" @click="onClick">
        <s-count-down
          v-if="disabled"
          :time="1000 * 8"
          format="重发验证码(s)"
          @finish="disabled = false"
        />
        <span v-else-if="loading">正在发送</span>
        <span v-else>发送验证码</span>
      </s-button>
    </template>
  </s-input>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { toast } from 'sard'

const value = ref('')
const loading = ref(false)
const disabled = ref(false)

const sendCaptcha = () => {
  return new Promise((resolve) => setTimeout(resolve, 1000))
}

const onClick = () => {
  loading.value = true
  sendCaptcha()
    .then(() => {
      toast('已发送验证码')
      disabled.value = true
    })
    .finally(() => {
      loading.value = false
    })
}
</script>

// packages/sard-taro-demo/src/packageA/pages/count-down/demo/Captcha.tsx
import { useState } from 'react'
import { Button, CountDown, Input, Toast } from 'sard-taro'

export default () => {
  const [loading, setLoading] = useState(false)
  const [disabled, setDisabled] = useState(false)

  const sendCaptcha = () => {
    return new Promise((resolve) => setTimeout(resolve, 1000))
  }

  const handleClick = () => {
    setLoading(true)
    sendCaptcha()
      .then(() => {
        Toast.show('已发送验证码')
        setDisabled(true)
      })
      .finally(() => {
        setLoading(false)
      })
  }

  return (
    <Input
      placeholder="请输入验证码"
      append={
        <Button
          size="small"
          loading={loading}
          disabled={disabled}
          onClick={handleClick}
          style={{ minWidth: 90 }}
        >
          {disabled ? (
            <CountDown
              time={1000 * 8}
              format="重发验证码(s)"
              onFinish={() => setDisabled(false)}
            />
          ) : loading ? (
            '正在发送'
          ) : (
            '发送验证码'
          )}
        </Button>
      }
    />
  )
}
