// src/views/components/count-down/demo/Control.vue
<template>
  <s-list card>
    <s-list-item>
      <s-count-down
        ref="elRef"
        class="font-mono mx-auto"
        :time="1000 * 10"
        format="ss:SS"
        millisecond
        :auto-start="false"
        @finish="toast('到时了!')"
      />
    </s-list-item>
    <s-list-item>
      <s-grid clickable :columns="3">
        <s-grid-item text="开始" @click="() => elRef?.start()" #icon>
          <demo-icon name="play-circle" />
        </s-grid-item>
        <s-grid-item text="暂停" @click="() => elRef?.pause()" #icon>
          <demo-icon name="pause-circle" />
        </s-grid-item>
        <s-grid-item text="重置" @click="() => elRef?.reset()" #icon>
          <demo-icon name="arrow-clockwise" />
        </s-grid-item>
      </s-grid>
    </s-list-item>
  </s-list>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { toast, type CountDownExpose } from 'sard'

const elRef = ref<CountDownExpose>()
</script>

// packages/sard-taro-demo/src/packageA/pages/count-down/demo/Control.tsx
import { useRef } from 'react'
import { CountDown, CountDownRef, Mesh, Space } from 'sard-taro'

export default () => {
  const ref = useRef<CountDownRef>(null)

  return (
    <Space vertical>
      <Mesh clickable columns={3}>
        <Mesh.Item
          onClick={() => ref.current?.start()}
          iconProps={{ prefix: 'demo-icon', name: 'play-circle' }}
          text="开始"
        />
        <Mesh.Item
          onClick={() => ref.current?.pause()}
          iconProps={{ prefix: 'demo-icon', name: 'pause-circle' }}
          text="暂停"
        />
        <Mesh.Item
          onClick={() => ref.current?.reset()}
          iconProps={{ prefix: 'demo-icon', name: 'arrow-clockwise' }}
          text="重置"
        />
      </Mesh>

      <CountDown
        ref={ref}
        time={1000 * 10}
        format="ss:SSS"
        interval={60}
        autoStart={false}
      />
    </Space>
  )
}
