// packages/SardDemo/src/packageA/pages/skeleton/demo/Contain.tsx
import { View } from '@tarojs/components'
import { useState } from 'react'
import { Icon, Skeleton, Space, Switch } from 'sard'

export default () => {
  const [loading, setLoading] = useState(true)

  return (
    <Space>
      <Switch
        defaultChecked={!loading}
        onChange={(check) => setLoading(!check)}
      />

      <Skeleton avatar title animated loading={loading}>
        <Space direction="horizontal" gap={15}>
          <View style={{ flexGrow: 0 }}>
            <Icon name="person" size={32} />
          </View>
          <Space style={{ flex: 1 }}>
            <View style={{ fontSize: 16 }}>我是一个标题</View>
            <View>
              我是一个段落我是一个段落我是一个段落我是一个段落我是一个段落我是一个段落我是一个段落我是一个段落
            </View>
          </Space>
        </Space>
      </Skeleton>
    </Space>
  )
}

// src/views/components/skeleton/demo/Contain.vue
<template>
  <s-switch v-model="loading" style="margin-bottom: 10px" />

  <s-skeleton avatar title animated :loading="loading">
    <div style="display: flex; gap: 15px">
      <demo-icon name="person" size="32px" />
      <div style="flex: 1">
        <div style="font-size: var(--s-font-size-lg); margin-bottom: 10px">我是一个标题</div>
        <div>
          我是一个段落我是一个段落我是一个段落我是一个段落我是一个段落我是一个段落我是一个段落我是一个段落
        </div>
      </div>
    </div>
  </s-skeleton>
</template>

<script setup lang="ts">
import { ref } from 'vue'

const loading = ref(false)
</script>
