// src/views/components/dropdown/demo/Label.vue
<template>
  <s-dropdown>
    <s-dropdown-item label="排序" :options="options1" model-value="1" />
    <s-dropdown-item label="速度" :options="options2" model-value="2" />
  </s-dropdown>
</template>

<script setup lang="ts">
const options1 = [
  {
    label: '距离优先',
    value: '1',
  },
  {
    label: '速度优先',
    value: '2',
  },
  {
    label: '评分优先',
    value: '3',
  },
]
const options2 = [
  {
    label: '30分钟内',
    value: '1',
  },
  {
    label: '40分钟内',
    value: '2',
  },
  {
    label: '50分钟内',
    value: '3',
  },
]
</script>

// packages/sard/src/components/dropdown/demo/Label.tsx
/*
### 添加 label
*/

import { Dropdown } from 'sard'

export default function () {
  const options1 = [
    {
      label: '距离优先',
      value: '1',
    },
    {
      label: '速度优先',
      value: '2',
    },
    {
      label: '评分优先',
      value: '3',
    },
  ]
  const options2 = [
    {
      label: '30分钟内',
      value: '1',
    },
    {
      label: '40分钟内',
      value: '2',
    },
    {
      label: '50分钟内',
      value: '3',
    },
  ]

  return (
    <>
      <Dropdown>
        <Dropdown.Item label="排序" options={options1}></Dropdown.Item>
        <Dropdown.Item
          label="速度"
          options={options2}
          defaultValue="2"
        ></Dropdown.Item>
      </Dropdown>
    </>
  )
}
