// packages/sard-taro-demo/src/packageA/pages/count-down/demo/Style.tsx
import { View } from '@tarojs/components'
import { CountDown, Space, Tag } from 'sard-taro'

export default () => {
  return (
    <CountDown time={1000 * 60 * 60 * 2} interval={93}>
      {(time) => (
        <Space>
          <Tag theme="primary" size="large">
            {String(time.hours).padStart(2, '0')}
          </Tag>
          <View>:</View>
          <Tag theme="primary" size="large">
            {String(time.minutes).padStart(2, '0')}
          </Tag>
          <View>:</View>
          <Tag theme="primary" size="large">
            {String(time.seconds).padStart(2, '0')}
          </Tag>
        </Space>
      )}
    </CountDown>
  )
}

// src/views/components/count-down/demo/Style.vue
<template>
  <s-count-down :time="30 * 60 * 60 * 1000" #default="{ time }">
    <div class="flex items-center">
      <s-button size="xs">
        {{ String(time.hours).padStart(2, '0') }}
      </s-button>
      <div class="mx-2 leading-0">:</div>
      <s-button size="xs">
        {{ String(time.minutes).padStart(2, '0') }}
      </s-button>
      <div class="mx-2 leading-0">:</div>
      <s-button size="xs">
        {{ String(time.seconds).padStart(2, '0') }}
      </s-button>
    </div>
  </s-count-down>
</template>
