// packages/sard/src/components/count-down/demo/Style.tsx
/*
### 自定义样式
*/

import { CountDown, CurrentTime } from 'sard'

export default function () {
  return (
    <>
      <style>
        {`
          .time-wrap {
            display: flex;
            align-items: center;
          }
          .time {
            padding: 5px;
            background: orange;
            border-radius: 4px;
            color: #000;
          }
          .colon {
            margin: 0 5px;
          }
        `}
      </style>
      <CountDown time={1000 * 60 * 60 * 2} interval={93}>
        {(time: CurrentTime) => (
          <div className="time-wrap">
            <div className="time">{String(time.hours).padStart(2, '0')}</div>
            <div className="colon">:</div>
            <div className="time">{String(time.minutes).padStart(2, '0')}</div>
            <div className="colon">:</div>
            <div className="time">{String(time.seconds).padStart(2, '0')}</div>
          </div>
        )}
      </CountDown>
    </>
  )
}

// src/views/components/count-down/demo/Style.vue
<template>
  <s-count-down :time="30 * 60 * 60 * 1000" #default="{ time }">
    <div class="flex items-center">
      <s-button size="xs">
        {{ String(time.hours).padStart(2, '0') }}
      </s-button>
      <div class="mx-2 leading-0">:</div>
      <s-button size="xs">
        {{ String(time.minutes).padStart(2, '0') }}
      </s-button>
      <div class="mx-2 leading-0">:</div>
      <s-button size="xs">
        {{ String(time.seconds).padStart(2, '0') }}
      </s-button>
    </div>
  </s-count-down>
</template>
