// packages/sard/components/badge/badge.vue
<template>
  <div v-if="slots.default" :class="bem.e('wrapper')">
    <slot></slot>
    <div :class="badgeClass" :style="badgeStyle">
      <slot name="value">
        {{ innerValue }}
      </slot>
    </div>
  </div>
  <div v-else :class="badgeClass" :style="badgeStyle">
    <slot name="value">
      {{ innerValue }}
    </slot>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { createBem } from '../../utils'
import { type BadgeProps, type BadgeSlots, defaultBadgeProps } from './common'

const props = withDefaults(defineProps<BadgeProps>(), defaultBadgeProps)

const slots = defineSlots<BadgeSlots>()

const bem = createBem('badge')

const zeroHide = computed(() => {
  return !props.dot && props.value === 0 && !props.showZero && !slots.value
})

const innerValue = computed(() => {
  return props.dot
    ? ''
    : typeof props.value === 'number' && props.value > props.max
      ? `${props.max}+`
      : props.value === 0 && !props.showZero
        ? ''
        : props.value
})

// ============================ style ============================
const badgeClass = computed(() => {
  return [
    bem.b(),
    bem.m('fixed', props.fixed || !!slots.default),
    bem.m('zero-hide', zeroHide.value),
    bem.m('dot', props.dot),
  ]
})

const badgeStyle = computed(() => {
  return {
    background: props.color,
    color: props.textColor,
  }
})
</script>

// packages/sard/src/components/badge/index.tsx
import { CSSProperties, ReactNode, memo, NamedExoticComponent } from 'react'
import classNames from 'classnames'
import { isVisibleEmpty } from '../../utils'

export interface BadgeProps {
  className?: string
  style?: CSSProperties
  children?: ReactNode
  value?: number | ReactNode
  max?: number
  showZero?: boolean
  color?: string
  textColor?: string
  isDot?: boolean
  fixed?: boolean
}

export const Badge: NamedExoticComponent<BadgeProps> = memo((props) => {
  const {
    className,
    children,
    value = 0,
    max = 99,
    showZero = false,
    color,
    textColor,
    isDot,
    fixed,
    ...restProps
  } = props

  const zeroHide = !isDot && value === 0 && !showZero

  const badgeClass = classNames(
    's-badge',
    {
      's-badge-fixed': fixed,
      's-badge-is-dot': isDot,
      's-badge-zero-hide': zeroHide,
    },
    className,
  )

  const contentClass = classNames('s-badge-content', {
    's-badge-fixed': !fixed && !isVisibleEmpty(children),
  })

  const contentStyle = {
    backgroundColor: color,
    color: textColor,
  }

  return (
    <div {...restProps} className={badgeClass}>
      {children}
      <div className={contentClass} style={contentStyle}>
        {isDot
          ? ''
          : typeof value === 'number' && value > max
          ? `${max}+`
          : value}
      </div>
    </div>
  )
})

export default Badge
