// packages/sard-taro-demo/src/packageA/pages/navbar/demo/Content.tsx
import { View } from '@tarojs/components'
import { Icon, Input, Navbar } from 'sard-taro'

export default () => {
  return (
    <Navbar
      flow
      left={
        <Navbar.Item>
          <View style={{ marginRight: 2 }}>城市</View>
          <Icon name="down" size={16}></Icon>
        </Navbar.Item>
      }
      right={<Navbar.Item>搜索</Navbar.Item>}
    >
      <Input placeholder="请输入关键词" />
    </Navbar>
  )
}

// src/views/components/navbar/demo/Content.vue
<template>
  <s-navbar flow>
    <template #start>
      <s-navbar-item reverse>
        <template #icon>
          <Down />
        </template>
        城市
      </s-navbar-item>
    </template>
    <s-input placeholder="请输入关键词" style="border-radius: 9999px" />
    <template #end>
      <s-navbar-item>搜索</s-navbar-item>
    </template>
  </s-navbar>
</template>

<script setup lang="ts">
import { Down } from '@sard/icons'
</script>
