// packages/sard/src/components/navbar/demo/Content.tsx
/*
### 自定义 content
*/

import { Navbar, Icon, Input } from 'sard'
import 'bootstrap-icons/font/bootstrap-icons.css'

export default function () {
  return (
    <Navbar
      flow
      prepend={
        <Navbar.Item>
          <span style={{ marginRight: 2 }}>城市</span>
          <Icon name="bi-chevron-down" size={16}></Icon>
        </Navbar.Item>
      }
      append={<Navbar.Item>搜索</Navbar.Item>}
    >
      <Input placeholder="请输入关键词" />
    </Navbar>
  )
}

// src/views/components/navbar/demo/Content.vue
<template>
  <s-navbar flow>
    <template #start>
      <s-navbar-item reverse>
        <template #icon>
          <Down />
        </template>
        城市
      </s-navbar-item>
    </template>
    <s-input placeholder="请输入关键词" style="border-radius: 9999px" />
    <template #end>
      <s-navbar-item>搜索</s-navbar-item>
    </template>
  </s-navbar>
</template>

<script setup lang="ts">
import { Down } from '@sard/icons'
</script>
