// packages/sard-taro-demo/src/packageA/pages/navbar/demo/Flow.tsx
import { View } from '@tarojs/components'
import { Icon, Navbar } from 'sard-taro'

export default () => {
  return (
    <Navbar
      flow
      left={
        <Navbar.Item>
          <Icon prefix="demo-icon" name="list-task" size={18}></Icon>
        </Navbar.Item>
      }
      title={<View style={{ textAlign: 'left' }}>发现</View>}
      right={
        <>
          <Navbar.Item>
            <Icon prefix="demo-icon" name="share" size={16}></Icon>
          </Navbar.Item>
          <Navbar.Item>
            <Icon prefix="demo-icon" name="star" size={18}></Icon>
          </Navbar.Item>
          <Navbar.Item>
            <Icon prefix="demo-icon" name="heart" size={16}></Icon>
          </Navbar.Item>
        </>
      }
    />
  )
}

// src/views/components/navbar/demo/Flow.vue
<template>
  <s-navbar title="发现" flow>
    <template #start>
      <s-navbar-item #icon>
        <demo-icon name="list-task" />
      </s-navbar-item>
    </template>
    <template #end>
      <s-navbar-item #icon>
        <demo-icon name="share" />
      </s-navbar-item>
      <s-navbar-item #icon>
        <demo-icon name="star" />
      </s-navbar-item>
      <s-navbar-item #icon>
        <demo-icon name="heart" />
      </s-navbar-item>
    </template>
  </s-navbar>
</template>
