// packages/sard-taro-demo/src/packageA/pages/tag/index.tsx
import Demo from '@/components/demo'
import Page from '@/components/page'

import Basic from './demo/Basic'
import Plain from './demo/Plain'
import Round from './demo/Round'
import Mark from './demo/Mark'
import Size from './demo/Size'
import Style from './demo/Style'
import Closable from './demo/Closable'

export default () => {
  return (
    <Page>
      <Demo title="基础使用">
        <Basic />
      </Demo>

      <Demo title="镂空">
        <Plain />
      </Demo>

      <Demo title="圆角">
        <Round />
      </Demo>

      <Demo title="标记样式（半圆角）">
        <Mark />
      </Demo>

      <Demo title="尺寸">
        <Size />
      </Demo>

      <Demo title="自定义样式">
        <Style />
      </Demo>

      <Demo title="可关闭的">
        <Closable />
      </Demo>
    </Page>
  )
}

// src/views/components/tag/index.vue
<template>
  <doc-page title="Tag 标签">
    <doc-demo title="基础使用">
      <ColorVariant />
    </doc-demo>

    <doc-demo title="圆角">
      <Round />
    </doc-demo>

    <doc-demo title="标记样式（半圆角）">
      <Mark />
    </doc-demo>

    <doc-demo title="尺寸">
      <Size />
    </doc-demo>

    <doc-demo title="可关闭的">
      <Closable />
    </doc-demo>
  </doc-page>
</template>

<script setup lang="ts">
import ColorVariant from './demo/ColorVariant.vue'
import Round from './demo/Round.vue'
import Mark from './demo/Mark.vue'
import Size from './demo/Size.vue'
import Closable from './demo/Closable.vue'
</script>
