// src/views/components/toast/demo/Mask.vue
<template>
  <s-list card>
    <s-list-item hover arrow title="显示背景" @click="showOverlayToast" />
    <s-list-item hover arrow title="透明背景" @click="showTransparentOverlayToast" />
  </s-list>
</template>

<script setup lang="ts">
import { toast } from 'sard'

const showOverlayToast = () => {
  toast.loading('加载中', {
    overlay: true,
  })

  setTimeout(() => {
    toast.hide()
  }, 1500)
}

const showTransparentOverlayToast = () => {
  toast.loading('加载中', {
    overlay: true,
    transparent: true,
  })

  setTimeout(() => {
    toast.hide()
  }, 1500)
}
</script>

// packages/SardDemo/src/packageA/pages/toast/demo/Mask.tsx
import { List, Toast } from 'sard'

export default () => {
  return (
    <List card>
      <List.Item
        linkable
        title="显示背景"
        onClick={() => {
          Toast.loading('加载中', {
            mask: true,
          })

          setTimeout(() => {
            Toast.hide()
          }, 1500)
        }}
      />

      <List.Item
        linkable
        title="透明背景"
        onClick={() => {
          Toast.loading('加载中', {
            mask: true,
            transparent: true,
          })

          setTimeout(() => {
            Toast.hide()
          }, 1500)
        }}
      />
    </List>
  )
}
