// src/views/components/tabs/demo/Disabled.vue
<template>
  <s-tabs v-model="value" :options="options"></s-tabs>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { type TabProps } from 'sard'

const value = ref(1)
const options = ref<TabProps[]>([
  { label: '标签1', value: 1 },
  { label: '标签2', value: 2, disabled: true },
  { label: '标签3', value: 3 },
])
</script>

// packages/sard-taro-demo/src/packageA/pages/tabs/demo/Disabled.tsx
import { View } from '@tarojs/components'
import { Tabs, TabsPane } from 'sard-taro'

export default () => {
  return (
    <Tabs>
      <TabsPane label="标签1">
        <View className="demo-pane">内容1</View>
      </TabsPane>
      <TabsPane label="标签2" disabled>
        <View className="demo-pane">内容2</View>
      </TabsPane>
      <TabsPane label="标签3">
        <View className="demo-pane">内容3</View>
      </TabsPane>
    </Tabs>
  )
}
