// packages/SardDemo/src/packageA/pages/notify/demo/Duration.tsx
import { List, Notify } from 'sard'

export default () => {
  return (
    <List card>
      <List.Item
        linkable
        title="显示不会消失的通知"
        onClick={() =>
          Notify.show('这是一条通知', {
            duration: 0,
          })
        }
      />
      <List.Item linkable title="隐藏通知" onClick={() => Notify.hide()} />
    </List>
  )
}

// src/views/components/notify/demo/Duration.vue
<template>
  <s-list card>
    <s-list-item arrow hover title="显示不会消失的通知" @click="showNotice" />
    <s-list-item arrow hover title="隐藏通知" @click="hideNotice" />
  </s-list>
</template>

<script setup lang="ts">
import { notify } from 'sard'

const showNotice = () => {
  notify('这是一条通知', {
    timeout: 0,
  })
}
const hideNotice = () => {
  notify.hide()
}
</script>
