// src/views/components/picker/demo/ObjectMultiple.vue
<template>
  <s-list card>
    <s-list-item>
      <s-picker v-model="value" :columns="columns" />
    </s-list-item>
    <s-list-item title="当前值：" :value="JSON.stringify(value) ?? 'undefined'" />
    <s-list-item title="设置为: 2003年10月" arrow hover @click="value = [2003, 10]" />
    <s-list-item title="清空" arrow hover @click="value = undefined" />
  </s-list>
</template>

<script setup lang="ts">
import { ref } from 'vue'

const columns = [
  Array(10)
    .fill(0)
    .map((_, index) => ({
      value: 2000 + index,
      label: 2000 + index + '年',
    })),
  Array(12)
    .fill(0)
    .map((_, index) => ({
      value: 1 + index,
      label: 1 + index + '月',
    })),
]

const value = ref<number[] | undefined>([2005, 5])
</script>

// packages/sard-taro-demo/src/packageA/pages/picker/demo/ObjectMultiple.tsx
import { useState } from 'react'
import { List, Picker, PopoutInput } from 'sard-taro'

export default () => {
  const columns = [
    Array(10)
      .fill(0)
      .map((_, index) => ({
        value: 2000 + index,
        label: 2000 + index + '年',
      })),
    Array(12)
      .fill(0)
      .map((_, index) => ({
        value: 1 + index,
        label: 1 + index + '月',
      })),
  ]

  const [value, setValue] = useState<number[]>()

  return (
    <List card>
      <List.Item
        linkable
        title="设置为: 2003年10月"
        onClick={() => setValue([2003, 10])}
      />
      <List.Item linkable title="清空" onClick={() => setValue(undefined)} />
      <List.Item>
        <PopoutInput
          title="请选择"
          inputProps={{ placeholder: '请选择' }}
          value={value}
          onChange={setValue}
        >
          <Picker
            columns={columns}
            outletFormatter={(labels) => labels.join('')}
          />
        </PopoutInput>
      </List.Item>
    </List>
  )
}
