// src/views/components/toast/index.vue
<template>
  <doc-page gray title="Toast 轻提示">
    <doc-demo title="基础使用">
      <Basic />
    </doc-demo>

    <doc-demo title="自定义位置">
      <Placement />
    </doc-demo>

    <doc-demo title="加载中的背景">
      <Mask />
    </doc-demo>

    <doc-demo title="自定义图标">
      <Icon />
    </doc-demo>
  </doc-page>
</template>

<script setup lang="ts">
import Basic from './demo/Basic.vue'
import Placement from './demo/Placement.vue'
import Mask from './demo/Mask.vue'
import Icon from './demo/Icon.vue'
</script>

// packages/SardDemo/src/packageA/pages/toast/index.tsx
import Demo from '@/components/demo'
import Page from '@/components/page'

import Basic from './demo/Basic'
import Icon from './demo/Icon'
import Placement from './demo/Placement'
import Mask from './demo/Mask'

export default () => {
  return (
    <Page>
      <Demo title="基础使用">
        <Basic />
      </Demo>

      <Demo title="自定义图标">
        <Icon />
      </Demo>

      <Demo title="自定义位置">
        <Placement />
      </Demo>

      <Demo title="加载中的背景">
        <Mask />
      </Demo>
    </Page>
  )
}
