// packages/sard-taro-demo/src/packageA/pages/list/index.tsx
import Demo from '@/components/demo'
import Page from '@/components/page'

import Basic from './demo/Basic'
import Linkable from './demo/Linkable'
import Icon from './demo/Icon'
import InsetIcon from './demo/InsetIcon'
import Slot from './demo/Slot'
import ListSlot from './demo/ListSlot'
import Card from './demo/Card'

export default () => {
  return (
    <Page>
      <Demo title="基础使用" full>
        <Basic />
      </Demo>

      <Demo title="可点击的" full>
        <Linkable />
      </Demo>

      <Demo title="图标" full>
        <Icon />
      </Demo>

      <Demo title="内嵌的图标" full>
        <InsetIcon />
      </Demo>

      <Demo title="自定义内容" full>
        <Slot />
      </Demo>

      <Demo title="分组" full>
        <ListSlot />
      </Demo>

      <Demo title="卡片风格" full>
        <Card />
      </Demo>
    </Page>
  )
}

// src/views/components/list/index.vue
<template>
  <doc-page gray title="List 列表">
    <doc-demo title="基础使用" full>
      <Basic />
    </doc-demo>

    <doc-demo title="可链接的" full>
      <Linkable />
    </doc-demo>

    <doc-demo title="图标" full>
      <Icon />
    </doc-demo>

    <doc-demo title="自定义内容" full>
      <Slot />
    </doc-demo>

    <doc-demo title="列表标题和描述" full>
      <Group />
    </doc-demo>

    <doc-demo title="卡片风格">
      <Card />
    </doc-demo>

    <doc-demo title="隐藏边框">
      <HideBorder />
    </doc-demo>
  </doc-page>
</template>

<script setup lang="ts">
import Basic from './demo/Basic.vue'
import Linkable from './demo/Linkable.vue'
import Icon from './demo/Icon.vue'
import Slot from './demo/Slot.vue'
import Group from './demo/Group.vue'
import Card from './demo/Card.vue'
import HideBorder from './demo/HideBorder.vue'
</script>
