// packages/sard-taro/src/result/index.tsx
import { FC, ReactNode } from 'react'
import { View } from '@tarojs/components'
import classNames from 'classnames'
import { Icon } from '../icon'
import { BaseProps } from '../base'
import { isNullish } from '../utils'
import { useBem } from '../use'

export interface ResultProps extends BaseProps {
  status?: 'success' | 'info' | 'warning' | 'error' | 'question'
  icon?: ReactNode
  title?: ReactNode
  description?: ReactNode
}

const mapStatusIcon = {
  success: 'check-circle-fill',
  info: 'info-circle-fill',
  warning: 'warning-fill',
  error: 'x-octagon-fill',
  question: 'question-circle-fill',
}

export const Result: FC<ResultProps> = (props) => {
  const {
    className,
    children,
    status = 'info',
    icon,
    title,
    description,
    ...restProps
  } = props

  const [bem] = useBem('result')

  return (
    <View {...restProps} className={classNames(bem.b(), className)}>
      <View className={classNames(bem.e('icon'), bem.em('icon', status))}>
        {icon ?? <Icon name={mapStatusIcon[status]}></Icon>}
      </View>
      {!isNullish(title) && <View className={bem.e('title')}>{title}</View>}
      {!isNullish(description) && (
        <View className={bem.e('description')}>{description}</View>
      )}
      {!isNullish(children) && (
        <View className={bem.e('extra')}>{children}</View>
      )}
    </View>
  )
}

export default Result

// packages/sard/components/result/result.vue
<template>
  <div :class="bem.b()">
    <div :class="iconClass">
      <slot name="icon">
        <CheckCircleFill v-if="status === 'success'" />
        <InfoCircleFill v-else-if="status === 'info'" />
        <WarningFill v-else-if="status === 'warning'" />
        <XOctagonFill v-else-if="status === 'error'" />
        <QuestionCircleFill v-else-if="status === 'question'" />
      </slot>
    </div>

    <div v-if="title" :class="bem.e('title')">
      <slot name="title">{{ title }}</slot>
    </div>

    <div v-if="description" :class="bem.e('description')">
      <slot name="description">{{ description }}</slot>
    </div>

    <div v-if="slots.default" :class="bem.e('extra')"><slot></slot></div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { createBem } from '../../utils'
import { type ResultProps, type ResultSlots, defaultResultProps } from './common'
import {
  CheckCircleFill,
  InfoCircleFill,
  QuestionCircleFill,
  WarningFill,
  XOctagonFill,
} from '@sard/icons'

const props = withDefaults(defineProps<ResultProps>(), defaultResultProps)

const slots = defineSlots<ResultSlots>()

const bem = createBem('result')

const iconClass = computed(() => {
  return [bem.e('icon'), bem.em('icon', props.status)]
})
</script>
