// packages/sard/components/skeleton/skeleton.vue
<template>
  <div v-if="loading" :class="bem.b()">
    <SkeletonAvatar v-if="avatar" :animated="animated" :size="avatarSize" :round="avatarRound" />

    <div :class="bem.e('content')">
      <SkeletonTitle v-if="title" :animated="animated" :round="round" />
      <SkeletonParagraph :rows="rows" :animated="animated" :round="round" />
    </div>
  </div>
  <slot v-else></slot>
</template>

<script setup lang="ts">
import { createBem } from '../../utils'
import SkeletonAvatar from './skeleton-avatar.vue'
import SkeletonTitle from './skeleton-title.vue'
import SkeletonParagraph from './skeleton-paragraph.vue'
import { type SkeletonProps, type SkeletonSlots, defaultSkeletonProps } from './common'

withDefaults(defineProps<SkeletonProps>(), defaultSkeletonProps)

defineSlots<SkeletonSlots>()

const bem = createBem('skeleton')
</script>

// packages/sard-taro/src/skeleton/index.tsx
import { FC } from 'react'
import { View } from '@tarojs/components'
import classNames from 'classnames'
import { SkeletonBlock } from './Block'
import { SkeletonAvatar } from './Avatar'
import { SkeletonTitle } from './Title'
import { SkeletonParagraph } from './Paragraph'
import { BaseProps } from '../base'
import { useBem } from '../use'

export * from './Block'
export * from './Avatar'
export * from './Title'
export * from './Paragraph'

export interface SkeletonProps extends BaseProps {
  rows?: number
  title?: boolean
  avatar?: boolean
  avatarSize?: number | string
  avatarRound?: boolean
  round?: boolean
  loading?: boolean
  animated?: boolean
}

export interface SkeletonFC extends FC<SkeletonProps> {
  Block: typeof SkeletonBlock
  Avatar: typeof SkeletonAvatar
  Title: typeof SkeletonTitle
  Paragraph: typeof SkeletonParagraph
}

export const Skeleton: SkeletonFC = (props) => {
  const {
    className,
    children,
    rows = 3,
    title = false,
    avatar = false,
    avatarSize = 32,
    avatarRound = false,
    round = false,
    loading = true,
    animated = false,
    ...restProps
  } = props

  const [bem] = useBem('skeleton')

  return (
    <>
      {loading ? (
        <View {...restProps} className={classNames(bem.b(), className)}>
          {avatar && (
            <SkeletonAvatar
              size={avatarSize}
              animated={animated}
              round={avatarRound}
              className={bem.em('avatar', 'in-skeleton')}
            />
          )}
          <View className={bem.e('content')}>
            {title && <SkeletonTitle animated={animated} round={round} />}
            <SkeletonParagraph
              rows={rows}
              animated={animated}
              round={round}
              className={bem.em('paragraph', 'in-skeleton')}
            />
          </View>
        </View>
      ) : (
        children
      )}
    </>
  )
}

Skeleton.Block = SkeletonBlock
Skeleton.Avatar = SkeletonAvatar
Skeleton.Title = SkeletonTitle
Skeleton.Paragraph = SkeletonParagraph

export default Skeleton
