// src/views/components/progress-circle/index.vue
<template>
  <doc-page title="ProgressCircle 环形进度条">
    <doc-demo title="基础使用">
      <Basic />
    </doc-demo>

    <doc-demo title="粗细">
      <Thickness />
    </doc-demo>

    <doc-demo title="颜色">
      <Color />
    </doc-demo>

    <doc-demo title="尺寸">
      <Size />
    </doc-demo>

    <doc-demo title="状态">
      <Status />
    </doc-demo>
  </doc-page>
</template>

<script setup lang="ts">
import Basic from './demo/Basic.vue'
import Thickness from './demo/Thickness.vue'
import Color from './demo/Color.vue'
import Size from './demo/Size.vue'
import Status from './demo/Status.vue'
</script>

// packages/SardDemo/src/packageA/pages/progress-circle/index.tsx
import Demo from '@/components/demo'
import Page from '@/components/page'

import Basic from './demo/Basic'
import Thickness from './demo/Thickness'
import Color from './demo/Color'
import Size from './demo/Size'

export default () => {
  return (
    <Page>
      <Demo title="基础使用">
        <Basic />
      </Demo>

      <Demo title="粗细">
        <Thickness />
      </Demo>

      <Demo title="颜色">
        <Color />
      </Demo>

      <Demo title="尺寸">
        <Size />
      </Demo>
    </Page>
  )
}
