// packages/sard-taro-demo/src/packageA/pages/notice-bar/demo/Vertical.tsx
import { Text, View } from '@tarojs/components'
import { NoticeBar, Swiper } from 'sard-taro'

export default () => {
  return (
    <NoticeBar vertical>
      <Swiper
        autoplay
        vertical
        interval={1500}
        circular
        style={{
          height: 40,
        }}
      >
        {Array(3)
          .fill(0)
          .map((_, i) => {
            return (
              <Swiper.Item key={i}>
                <View
                  style={{
                    display: 'flex',
                    width: '100%',
                    height: '100%',
                    flexDirection: 'column',
                    justifyContent: 'center',
                    alignItems: 'flex-start',
                  }}
                >
                  <Text style={{ color: 'black' }}>{`${
                    i + 1
                  }. 这是一条公告！`}</Text>
                </View>
              </Swiper.Item>
            )
          })}
      </Swiper>
    </NoticeBar>
  )
}

// src/views/components/notice-bar/demo/Vertical.vue
<template>
  <s-notice-bar vertical>
    <s-swiper vertical :interval="1500" loop style="height: 40px">
      <s-swiper-item>
        <div class="swipe-item">1. 这是一条公告！</div>
      </s-swiper-item>
      <s-swiper-item>
        <div class="swipe-item">2. 这是一条公告！</div>
      </s-swiper-item>
      <s-swiper-item>
        <div class="swipe-item">3. 这是一条公告！</div>
      </s-swiper-item>
    </s-swiper>
  </s-notice-bar>
</template>

<style lang="scss">
.swipe-item {
  display: flex;
  width: 100%;
  height: 100%;
  flex-direction: column;
  justify-content: center;
  align-items: flex-start;
}
</style>
