// src/views/components/upload/demo/Status.vue
<template>
  <s-upload v-model="fileList" :after-read="afterRead" />
</template>

<script setup lang="ts">
import type { UploadFileItem } from 'sard'
import { ref } from 'vue'

const fileList = ref<UploadFileItem[]>([
  {
    url: 'https://fastly.jsdelivr.net/npm/@sard/assets/pic1.jpg',
  },
  {
    url: 'https://fastly.jsdelivr.net/npm/@sard/assets/pic2.jpg',
    status: 'uploading',
    message: '正在上传',
  },
  {
    url: 'https://fastly.jsdelivr.net/npm/@sard/assets/pic3.jpg',
    status: 'failed',
    message: '上传失败',
  },
])

const afterRead = (fileItem: UploadFileItem) => {
  console.log(fileItem)
  fileItem.status = 'uploading'
  fileItem.message = '正在上传'

  setTimeout(() => {
    fileItem.status = 'done'
  }, 1500)
}
</script>

// packages/sard/src/components/upload/demo/Status.tsx
/*
### 上传状态
*/

import { useState } from 'react'
import { Upload, UploadPreviewProps } from 'sard'

const logoHref = new URL('../../../../public/pic1.jpg', import.meta.url).href

export default function () {
  const [list, setList] = useState<UploadPreviewProps[]>(() => [
    {
      url: logoHref,
    },
    {
      url: logoHref,
      status: 'uploading',
      message: '正在上传',
    },
    {
      url: logoHref,
      status: 'failed',
      message: '上传失败',
    },
  ])

  const handleChange = (previewList: UploadPreviewProps[]) => {
    setList(previewList)
  }

  const handleAfterRead = (fileItem: UploadPreviewProps) => {
    fileItem.status = 'uploading'
    fileItem.message = '正在上传'
    setList((list) => [...list])

    setTimeout(() => {
      fileItem.status = 'failed'
      fileItem.message = '上传失败'
      setList((list) => [...list])
    }, 1500)
  }

  return (
    <>
      <Upload
        previewList={list}
        onChange={handleChange}
        afterRead={handleAfterRead}
      />
    </>
  )
}
