// src/views/components/cascader/demo/OptionTop.vue
<template>
  <s-list card>
    <s-list-item>
      <s-cascader
        :options="regionData"
        :field-keys="{ label: 'name', value: 'code' }"
        @update:modelValue="onChange"
      >
        <template #top="{ tabIndex }">
          <div
            :style="{
              padding: '8px 16px',
              backgroundColor: 'rgba(var(--s-color-primary-rgb), 0.1)',
              color: 'var(--s-color-primary)',
            }"
          >
            当前为第{{ tabIndex + 1 }}级
          </div>
        </template>
      </s-cascader>
    </s-list-item>
  </s-list>
</template>

<script setup lang="ts">
import { getRegionData, type Node } from 'region-data'
import { toast } from 'sard'

const regionData = getRegionData()

const onChange = (_: any, selectedOptions: Node[]) => {
  toast(selectedOptions.map((option) => option.name).join('/'))
}
</script>

// packages/SardDemo/src/packageA/pages/cascader/demo/OptionTop.tsx
import { Cascader, List, PopoutInput } from 'sard'
import { getRegionData } from 'region-data'
import { Text, View } from '@tarojs/components'

const regionData = getRegionData()

export default () => {
  return (
    <List card>
      <List.Item>
        <PopoutInput title="请选择" inputProps={{ placeholder: '请选择' }}>
          <Cascader
            options={regionData}
            fieldNames={{ label: 'name', value: 'code' }}
            optionTop={(columnIndex) => (
              <View
                style={{
                  paddingTop: 8,
                  paddingBottom: 8,
                  paddingLeft: 16,
                  paddingRight: 16,
                  backgroundColor: '#f5f5f5',
                }}
              >
                <Text style={{ color: 'tomato' }}>
                  当前为第{columnIndex + 1}级
                </Text>
              </View>
            )}
          />
        </PopoutInput>
      </List.Item>
    </List>
  )
}
