// src/views/components/button/demo/Round.vue
<template>
  <s-space wrap>
    <s-button round variant="solid">Solid</s-button>
    <s-button round variant="outlined">Outlined</s-button>
    <s-button round variant="dashed">Dashed</s-button>
    <s-button round variant="filled">Filled</s-button>
    <s-button round variant="text">Text</s-button>
    <s-button round variant="link">Link</s-button>
  </s-space>
</template>

// packages/SardDemo/src/packageA/pages/button/demo/Round.tsx
import { Button, Space } from 'sard'

export default () => {
  return (
    <Space>
      <Button round>default</Button>
      <Button round type="pale">
        pale
      </Button>
      <Button round type="mild">
        mild
      </Button>
      <Button round type="outline">
        outline
      </Button>
      <Button round type="text">
        text
      </Button>
      <Button round type="pale-text">
        pale-text
      </Button>
    </Space>
  )
}
