// packages/sard-taro/src/dialog/Dialog.tsx
import {
  forwardRef,
  ReactNode,
  useImperativeHandle,
  useState,
  ForwardRefExoticComponent,
  PropsWithoutRef,
  RefAttributes,
} from 'react'
import { ITouchEvent, View } from '@tarojs/components'
import classNames from 'classnames'
import { Popup, PopupProps } from '../popup'
import { Button, ButtonProps } from '../button'
import { Icon } from '../icon'
import { useBem, useEvent } from '../use'
import useTranslate from '../locale/useTranslate'
import { BaseProps } from '../base'
import { isFunction, isNullish, noop } from '../utils'

const CLOSE = 'close'
const CANCEL = 'cancel'
const CONFIRM = 'confirm'

const buttonProps: {
  [p in DialogButtonType]: {
    [p in 'cancel' | 'confirm']: ButtonProps
  }
} = {
  text: {
    cancel: {
      type: 'text',
      theme: 'secondary',
      size: 'large',
    },
    confirm: {
      type: 'text',
      theme: 'primary',
      size: 'large',
    },
  },
  round: {
    cancel: {
      type: 'pale',
      theme: 'primary',
      round: true,
    },
    confirm: {
      type: 'default',
      theme: 'primary',
      round: true,
    },
  },
}

export type DialogCloseType = 'close' | 'cancel' | 'confirm'

type DialogButtonType = 'round' | 'text'

export interface DialogProps extends BaseProps, PopupProps {
  title?: ReactNode
  message?: ReactNode
  header?: ReactNode
  footer?: ReactNode
  headed?: boolean
  buttonType?: DialogButtonType
  showCancel?: boolean
  cancelText?: ReactNode
  cancelProps?: ButtonProps
  showConfirm?: boolean
  confirmText?: ReactNode
  confirmProps?: ButtonProps
  maskClosable?: boolean
  onClose?: () => void | Promise<unknown>
  onCancel?: () => void | Promise<unknown>
  onConfirm?: () => void | Promise<unknown>
  visible?: boolean
  onVisible?: (visible: boolean) => void
}

// eslint-disable-next-line @typescript-eslint/no-empty-interface
export interface DialogRef {}

export type DialogFC = ForwardRefExoticComponent<
  PropsWithoutRef<DialogProps> & RefAttributes<DialogRef>
>

export const Dialog: DialogFC = forwardRef<DialogRef, DialogProps>(
  (props, ref) => {
    const [t] = useTranslate('dialog')

    const {
      className,
      children,
      title,
      message,
      header,
      headed,
      footer,
      buttonType = 'text',
      showCancel = false,
      cancelText = t('cancel'),
      cancelProps,
      showConfirm = true,
      confirmText = t('confirm'),
      confirmProps,
      maskClosable = false,
      onClose,
      onCancel,
      onConfirm,
      onVisible,

      onMaskClick,
      ...restProps
    } = props

    const [bem] = useBem('dialog')

    const [loading, setLoading] = useState({
      cancel: false,
      confirm: false,
    })

    const perhapsClose = (
      type: DialogCloseType,
      callback?: () => void | Promise<unknown>,
    ) => {
      function toggleLoading(play: boolean) {
        setLoading((loading) => ({
          ...loading,
          [type]: play,
        }))
      }

      if (isFunction(callback)) {
        const result = callback()
        if (result instanceof Promise) {
          toggleLoading(true)

          return result
            .then(() => {
              onVisible?.(false)
            })
            .catch(noop)
            .finally(() => {
              toggleLoading(false)
            })
        }
      }

      onVisible?.(false)
    }

    const handleMaskClick = useEvent((event: ITouchEvent) => {
      onMaskClick?.(event)

      if (maskClosable) {
        perhapsClose(CLOSE, onClose)
      }
    })

    const handleClose = () => {
      perhapsClose(CLOSE, onClose)
    }
    const handleCancel = () => {
      perhapsClose(CANCEL, onCancel)
    }
    const handleConfirm = () => {
      perhapsClose(CONFIRM, onConfirm)
    }

    useImperativeHandle(ref, () => ({}))

    const renderTitle = () => {
      return (
        <View
          className={classNames(
            bem.e('title'),
            bem.em('title', 'headed', headed),
            bem.em('title', 'headless', !headed),
            bem.em('title', 'headless-message', !headed && !isNullish(message)),
          )}
        >
          {title}
        </View>
      )
    }

    return (
      <Popup
        {...restProps}
        effect="zoom"
        mask
        onMaskClick={handleMaskClick}
        className={classNames(bem.b(), bem.m('headed', headed), className)}
      >
        {headed && (
          <View
            className={classNames(
              bem.e('header'),
              bem.em('header', 'titled', !isNullish(title)),
            )}
          >
            {header ?? renderTitle()}

            <Button
              className={bem.e('close')}
              type="pale-text"
              theme="secondary"
              size="large"
              onClick={handleClose}
            >
              <Icon name="close"></Icon>
            </Button>
          </View>
        )}
        <View
          className={classNames(
            bem.e('body'),
            bem.em('body', 'untitled', isNullish(title)),
          )}
        >
          {children ?? (
            <>
              {!headed && !isNullish(title) && renderTitle()}
              {!isNullish(message) && (
                <View
                  className={classNames(
                    bem.e('message'),
                    bem.em(
                      'message',
                      'headless-titled',
                      !headed && !isNullish(title),
                    ),
                    bem.em(
                      'message',
                      'headed-untitled',
                      headed && isNullish(title),
                    ),
                  )}
                >
                  {message}
                </View>
              )}
            </>
          )}
        </View>
        <View
          className={classNames(
            bem.e('footer'),
            bem.em('footer', 'text-button', buttonType === 'text'),
            bem.em('footer', 'round-button', buttonType === 'round'),
          )}
        >
          {footer ?? (
            <>
              {showCancel && (
                <Button
                  {...buttonProps[buttonType].cancel}
                  className={classNames(
                    bem.e('button'),
                    bem.e('cancel'),
                    bem.em('button', 'text', buttonType === 'text'),
                    bem.em('button', 'text-first', buttonType === 'text'),
                    bem.em(
                      'button',
                      'text-last',
                      buttonType === 'text' && !showConfirm,
                    ),
                  )}
                  {...cancelProps}
                  block
                  loading={loading.cancel}
                  onClick={handleCancel}
                >
                  {cancelText}
                </Button>
              )}
              {showCancel && buttonType === 'text' && (
                <View className={bem.e('divider')}></View>
              )}
              {showConfirm && (
                <Button
                  {...buttonProps[buttonType].confirm}
                  className={classNames(
                    bem.e('button'),
                    bem.e('confirm'),
                    bem.em('button', 'text', buttonType === 'text'),
                    bem.em('button', 'text-last', buttonType === 'text'),
                    bem.em(
                      'button',
                      'text-first',
                      buttonType === 'text' && !showCancel,
                    ),
                    bem.em(
                      'button',
                      'round-later',
                      showCancel && buttonType === 'round',
                    ),
                  )}
                  {...confirmProps}
                  block
                  loading={loading.confirm}
                  onClick={handleConfirm}
                >
                  {confirmText}
                </Button>
              )}
            </>
          )}
        </View>
      </Popup>
    )
  },
)

export default Dialog

// packages/sard/components/dialog/dialog.vue
<template>
  <Popup
    effect="zoom"
    :visible="visible"
    :class="bem.e('popup')"
    @overlay-click="onOverlayClick"
    @visible-hook="onVisibleHook"
  >
    <div :class="dialogClass">
      <div v-if="headed" :class="bem.e('header')">
        <div v-if="title" :class="bem.e('title')">
          {{ title }}
        </div>
        <div :class="bem.e('close')">
          <Button variant="link" color="secondary" size="large" block @click="onClose">
            <Close />
          </Button>
        </div>
      </div>

      <div v-if="(!headed && title) || message" :class="bem.e('body')">
        <div v-if="!headed && title" :class="bem.e('title')">
          {{ title }}
        </div>
        <div v-if="message" :class="bem.e('message')">
          <span>{{ message }}</span>
        </div>
      </div>
      <slot></slot>

      <div :class="bem.e('footer')">
        <Button
          v-if="showCancel"
          :class="bem.e('button')"
          :loading="loading.cancel"
          :variant="buttonProps.cancel.variant"
          :color="buttonProps.cancel.color"
          :size="buttonProps.cancel.size"
          :round="buttonProps.cancel.round"
          block
          v-bind="cancelProps"
          @click="onCancel"
        >
          {{ cancelText || t('cancel') }}
        </Button>
        <div v-if="showCancel && buttonType === 'text'" :class="bem.e('divider')" />
        <Button
          v-if="showConfirm"
          :class="bem.e('button')"
          :loading="loading.confirm"
          :variant="buttonProps.confirm.variant"
          :color="buttonProps.confirm.color"
          :size="buttonProps.confirm.size"
          :round="buttonProps.confirm.round"
          block
          v-bind="confirmProps"
          @click="onConfirm"
        >
          {{ confirmText || t('confirm') }}
        </Button>
      </div>
    </div>
  </Popup>
</template>

<script setup lang="ts">
import { computed, ref, watch, readonly, reactive } from 'vue'
import { createBem, noop, isFunction } from '../../utils'
import { useTranslateWithPrefix } from '../../locale'
import Popup from '../popup/popup.vue'
import Button from '../button/button.vue'
import { type DialogProps, type DialogEmits, type DialogSlots, defaultDialogProps } from './common'
import { type ButtonProps } from '../button'
import { Close } from '@sard/icons'
import type { MotionHookName } from '../motion/common'

const props = withDefaults(defineProps<DialogProps>(), defaultDialogProps)

defineSlots<DialogSlots>()

const emit = defineEmits<DialogEmits>()

const bem = createBem('dialog')

const { t } = useTranslateWithPrefix('dialog')

// ============================ visible ============================
const innerVisible = ref(props.visible)

watch(
  () => props.visible,
  () => {
    innerVisible.value = props.visible
  },
)

const loading = reactive({
  cancel: false,
  confirm: false,
  close: false,
})

const readonlyLoading = readonly(loading)

const asyncSet = new Set<{ valid: boolean }>()

watch(
  innerVisible,
  () => {
    if (innerVisible.value === false) {
      asyncSet.forEach((obj) => {
        obj.valid = false
      })
      Object.assign(loading, {
        cancel: false,
        confirm: false,
        close: false,
      })
    }
  },
  {
    flush: 'sync',
  },
)

const perhapsClose = (type: 'close' | 'cancel' | 'confirm') => {
  emit(type as any)
  if (isFunction(props.beforeClose)) {
    const result = props.beforeClose(type, readonlyLoading)
    if (result instanceof Promise) {
      loading[type] = true

      const obj = {
        valid: true,
      }
      asyncSet.add(obj)

      return result
        .then(() => {
          if (obj.valid) {
            innerVisible.value = false
            emit('update:visible', false)
          }
        })
        .catch(noop)
        .finally(() => {
          loading[type] = false
          asyncSet.delete(obj)
        })
    } else if (result === false) {
      return
    }
  }

  innerVisible.value = false
  emit('update:visible', false)
}

const onOverlayClick = () => {
  if (props.overlayClosable) {
    perhapsClose('close')
  }
}

const onClose = () => {
  perhapsClose('close')
}

const onConfirm = () => {
  perhapsClose('confirm')
}

const onCancel = () => {
  perhapsClose('cancel')
}

const onVisibleHook = (name: MotionHookName, el: Element) => {
  emit('visible-hook', name, el)
  emit(name as any, el)
}

const buttonProps = computed(() => {
  const buttonTypes: Record<
    NonNullable<DialogProps['buttonType']>,
    Record<'cancel' | 'confirm', ButtonProps>
  > = {
    text: {
      cancel: {
        variant: 'text',
        color: 'secondary',
        size: 'large',
      },
      confirm: {
        variant: 'text',
        color: 'primary',
        size: 'large',
      },
    },
    round: {
      cancel: {
        variant: 'filled',
        color: 'primary',
        round: true,
      },
      confirm: {
        variant: 'solid',
        color: 'primary',
        round: true,
      },
    },
  }
  return buttonTypes[props.buttonType]
})

// ============================ style ============================

const dialogClass = computed(() => {
  return [
    bem.b(),
    bem.m('headed', props.headed),
    bem.m('untitled', !props.title),
    bem.m(props.buttonType),
  ]
})
</script>
