// packages/SardDemo/src/packageA/pages/space/demo/Align.tsx
import { useState } from 'react'
import { Button, Radio, Space, SpaceAlign } from 'sard'

export default () => {
  const [align, setAlign] = useState<SpaceAlign>('start')

  return (
    <Space>
      <Space direction="horizontal" wrap>
        <Radio.Group value={align} onChange={setAlign}>
          {['start', 'center', 'end', 'stretch', 'baseline'].map((item) => (
            <Radio key={item} value={item}>
              {item}
            </Radio>
          ))}
        </Radio.Group>
      </Space>

      <Space direction="horizontal" align={align}>
        <Space
          align="center"
          style={{
            width: 100,
            padding: 10,
            color: 'white',
            backgroundColor: 'tomato',
          }}
        >
          {align}
        </Space>
        <Button style={{ width: 100, height: 100 }}>按钮</Button>
      </Space>
    </Space>
  )
}

// src/views/components/space/demo/Align.vue
<template>
  <div v-for="item in alignments" :key="item" class="wrapper">
    <s-space :align="item">
      <div>{{ item }}</div>
      <s-button>按钮</s-button>
      <s-avatar />
    </s-space>
  </div>
</template>

<script setup lang="ts">
const alignments = ['start', 'center', 'end', 'baseline'] as const
</script>

<style lang="scss" scoped>
.wrapper {
  border: 1px solid var(--s-color-primary);
  margin-bottom: 10px;
  padding: 10px;
}
</style>
