// packages/sard/components/result/result.vue
<template>
  <div :class="bem.b()">
    <div :class="iconClass">
      <slot name="icon">
        <CheckCircleFill v-if="status === 'success'" />
        <InfoCircleFill v-else-if="status === 'info'" />
        <WarningFill v-else-if="status === 'warning'" />
        <XOctagonFill v-else-if="status === 'error'" />
        <QuestionCircleFill v-else-if="status === 'question'" />
      </slot>
    </div>

    <div v-if="title" :class="bem.e('title')">
      <slot name="title">{{ title }}</slot>
    </div>

    <div v-if="description" :class="bem.e('description')">
      <slot name="description">{{ description }}</slot>
    </div>

    <div v-if="slots.default" :class="bem.e('extra')"><slot></slot></div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { createBem } from '../../utils'
import { type ResultProps, type ResultSlots, defaultResultProps } from './common'
import {
  CheckCircleFill,
  InfoCircleFill,
  QuestionCircleFill,
  WarningFill,
  XOctagonFill,
} from '@sard/icons'

const props = withDefaults(defineProps<ResultProps>(), defaultResultProps)

const slots = defineSlots<ResultSlots>()

const bem = createBem('result')

const iconClass = computed(() => {
  return [bem.e('icon'), bem.em('icon', props.status)]
})
</script>

// packages/sard/src/components/result/index.tsx
import { CSSProperties, FC, ReactNode } from 'react'
import classNames from 'classnames'
import { CommonComponentProps } from '../../utils/types'
import { Icon } from '../icon'

export interface ResultProps extends CommonComponentProps {
  className?: string
  style?: CSSProperties
  children?: ReactNode
  status?: 'success' | 'info' | 'warning' | 'error' | 'question'
  icon?: ReactNode
  title?: ReactNode
  description?: ReactNode
}

const mapStatusIcon = {
  success: 'check-circle-fill',
  info: 'info-circle-fill',
  warning: 'warning-fill',
  error: 'x-octagon-fill',
  question: 'question-circle-fill',
}

export const Result: FC<ResultProps> = (props) => {
  const {
    className,
    children,
    status = 'info',
    icon,
    title,
    description,
    ...restProps
  } = props

  const resultClass = classNames('s-result', `s-result-${status}`, className)

  return (
    <div {...restProps} className={resultClass}>
      <div className="s-result-icon">
        {icon ?? <Icon prefix="si" name={mapStatusIcon[status]}></Icon>}
      </div>
      {title && <div className="s-result-title">{title}</div>}
      {description && <div className="s-result-description">{description}</div>}
      {children && <div className="s-result-extra">{children}</div>}
    </div>
  )
}

export default Result
