// src/views/components/input/demo/Inlaid.vue
<template>
  <s-list>
    <s-list-item>
      <s-input v-model="username" inlaid clearable placeholder="请输入用户名" />
    </s-list-item>
    <s-list-item>
      <s-input v-model="password" inlaid clearable type="password" placeholder="请输入密码" />
    </s-list-item>
  </s-list>
</template>

<script setup lang="ts">
import { ref } from 'vue'

const username = ref('')
const password = ref('')
</script>

// packages/sard-taro-demo/src/packageA/pages/input/demo/Inlaid.tsx
import { List, Input } from 'sard-taro'

export default () => {
  return (
    <List card bodyStyle={{ maxWidth: 80 }}>
      <List.Item
        title="用户名"
        footer={<Input inlaid placeholder="嵌入的" />}
      />
      <List.Item
        title="密码"
        footer={<Input inlaid type="password" placeholder="嵌入的" />}
      />
    </List>
  )
}
