// packages/sard/components/progress-bar/progress-bar.vue
<template>
  <div :class="progressBarClass">
    <div :class="bem.e('track')" :style="trackStyle">
      <div :class="bem.e('fill')" :style="fillStyle">
        <div v-if="showText && inside" :class="bem.e('text')">
          <slot>{{ percent }}%</slot>
        </div>
      </div>
    </div>
    <div v-if="showText && !inside && !status" :class="bem.e('text')">
      <slot>{{ percent }}%</slot>
    </div>
    <div v-if="status" :class="bem.e('status')">
      <CheckCircleFill v-if="status === 'success'" />
      <WarningFill v-else-if="status === 'warning'" />
      <XCircleFill v-else-if="status === 'error'" />
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { createBem } from '../../utils'
import { type ProgressBarProps, type ProgressBarSlots, defaultProgressBarProps } from './common'
import { CheckCircleFill, WarningFill, XCircleFill } from '@sard/icons'

const props = withDefaults(defineProps<ProgressBarProps>(), defaultProgressBarProps)

defineSlots<ProgressBarSlots>()

const bem = createBem('progress-bar')

const progressBarClass = computed(() => {
  return [
    bem.b(),
    bem.m('inside', props.inside),
    bem.m('striped', props.striped),
    bem.m('animated', props.animated),
    bem.m(props.status, props.status),
  ]
})

const trackStyle = computed(() => {
  return {
    height: props.thickness,
    backgroundColor: props.trackColor,
  }
})

const fillStyle = computed(() => {
  return {
    width: `${props.percent}%`,
    backgroundColor: props.color,
  }
})
</script>

// packages/sard-taro/src/progress-bar/index.tsx
import { FC } from 'react'
import { View } from '@tarojs/components'
import classNames from 'classnames'
import { BaseProps } from '../base'
import { useBem } from '../use'

export interface ProgressBarProps extends BaseProps {
  percent?: number
  color?: string
  trackColor?: string
  striped?: boolean
  animated?: boolean
  thickness?: string | number
}

export const ProgressBar: FC<ProgressBarProps> = (props) => {
  const {
    className,
    style,
    children,
    percent = 0,
    color,
    trackColor,
    striped,
    animated,
    thickness,
    ...restProps
  } = props

  const [bem] = useBem('progress-bar')

  return (
    <View
      {...restProps}
      className={classNames(bem.b(), className)}
      style={{
        backgroundColor: trackColor,
        height: thickness,
        ...style,
      }}
    >
      <View
        className={classNames(
          bem.e('trail'),
          bem.em('trail', 'striped', striped),
          bem.em('trail', 'animated', animated),
        )}
        style={{
          width: `${percent}%`,
          backgroundColor: color,
        }}
      >
        {children}
      </View>
    </View>
  )
}

export default ProgressBar
