// packages/sard-taro/src/password-input/index.tsx
import { FC, useLayoutEffect } from 'react'
import classNames from 'classnames'
import {
  BaseEventOrig,
  ITouchEvent,
  Input,
  InputProps,
  View,
} from '@tarojs/components'
import { useBem, useControllableValue } from '../use'
import { BaseProps } from '../base'

export interface PasswordInputProps extends Omit<BaseProps, 'children'> {
  value?: string
  defaultValue?: string
  onChange?: (value: string) => void
  length?: number
  type?: 'border' | 'underline'
  gap?: number | string
  plainText?: boolean
  focused?: boolean
  defaultFocused?: boolean
  onFocused?: (focused: boolean) => void
  onClick?: (event: ITouchEvent) => void
  custom?: boolean
  inputType?: InputProps['type']
  disabled?: boolean
  readOnly?: boolean
}

export const PasswordInput: FC<PasswordInputProps> = (props) => {
  const {
    className,
    style,
    value,
    defaultValue,
    onChange,
    length = 6,
    type = 'border',
    gap,
    plainText,
    focused,
    defaultFocused,
    onFocused,
    onClick,
    custom,
    inputType = 'number',
    disabled,
    readOnly,
    ...restProps
  } = props

  const [bem] = useBem('password-input')

  const [innerValue, setInnerValue] = useControllableValue({
    value,
    defaultValue,
    trigger: onChange,
    initialValue: '',
  })

  const [innerFocused, setInnerFocused] = useControllableValue({
    value: focused,
    defaultValue: defaultFocused,
    trigger: onFocused,
    initialValue: false,
  })

  const handleClick = (event: ITouchEvent) => {
    onClick?.(event)
  }

  const handleChange = (event: BaseEventOrig<InputProps.inputEventDetail>) => {
    setInnerValue(
      (event.target as unknown as { value: string }).value ??
        event.detail.value,
    )
  }

  useLayoutEffect(() => {
    if (innerValue) {
      setInnerValue(String(innerValue).slice(0, length))
    }
  }, [innerValue])

  const handleFocus = () => {
    setInnerFocused(true)
  }

  const handleBlur = () => {
    setInnerFocused(false)
  }

  const passwordInputClass = classNames(
    bem.b(),
    bem.m('readonly', readOnly),
    bem.m('disabled', disabled),
    className,
  )

  const passwordInputStyle = {
    ...style,
    gap,
  }

  return (
    <View
      {...restProps}
      className={passwordInputClass}
      onClick={handleClick}
      style={passwordInputStyle}
    >
      {Array(length)
        .fill(0)
        .map((_, i) => {
          const active =
            innerFocused &&
            (i === innerValue.length ||
              (i === innerValue.length - 1 && i === length - 1))
          return (
            <View
              key={i}
              className={classNames(
                bem.e('item'),
                bem.em('item', type),
                bem.em('item', `${type}-active`, active),
                bem.em('item', 'active', active),
                bem.em('item', 'lapped', gap === 0 && i !== 0),
              )}
            >
              {i < innerValue.length &&
                (plainText ? (
                  <View className={bem.e('plaintext')}>{innerValue[i]}</View>
                ) : (
                  <View className={bem.e('ciphertext')}></View>
                ))}
              {innerFocused && i === innerValue.length && (
                <View className={bem.e('cursor')}></View>
              )}
            </View>
          )
        })}

      {!custom && (
        <Input
          className={bem.e('input')}
          disabled={disabled || readOnly}
          value={innerValue}
          type={inputType}
          maxlength={length}
          onInput={handleChange}
          onFocus={handleFocus}
          onBlur={handleBlur}
        />
      )}
    </View>
  )
}

export default PasswordInput

// packages/sard/components/password-input/password-input.vue
<template>
  <div :class="passwordInputClass" :style="passwordInputStyle">
    <div
      v-for="item in items"
      :key="item.index"
      :class="[bem.e('item'), bem.em('item', 'active', item.active)]"
    >
      <template v-if="item.index < nativeInputValue.length">
        <div v-if="plainText" :class="bem.e('plaintext')">
          {{ nativeInputValue[item.index] }}
        </div>
        <div v-else :class="bem.e('ciphertext')"></div>
      </template>
      <div
        v-if="innerFocused && item.index === nativeInputValue.length"
        :class="bem.e('cursor')"
      ></div>
    </div>

    <div v-if="!customKeyboard" :class="bem.e('input-wrapper')">
      <input
        ref="input"
        type="text"
        inputmode="numeric"
        :class="bem.e('input')"
        :disabled="isDisabled || isReadonly"
        :maxlength="length"
        @input="onInput"
        @focus="onFocus"
        @blur="onBlur"
        @click="toEnd"
        @keyup="toEnd"
        @select="toEnd"
      />
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, nextTick, onMounted, ref, useTemplateRef, watch } from 'vue'
import { createBem, isNullish } from '../../utils'
import { useFormContext, useFormItemContext } from '../form/common'
import {
  type PasswordInputProps,
  type PasswordInputEmits,
  defaultPasswordInputProps,
} from './common'

const props = withDefaults(defineProps<PasswordInputProps>(), defaultPasswordInputProps)

const emit = defineEmits<PasswordInputEmits>()

const bem = createBem('password-input')

const formContext = useFormContext()
const formItemContext = useFormItemContext()

const isDisabled = computed(() => {
  return formContext?.disabled || props.disabled
})

const isReadonly = computed(() => {
  return formContext?.readonly || props.readonly
})

const inputRef = useTemplateRef('input')

const normalizeInputValue = (value: string) => {
  return value.replace(/[^\d]/g, '')
}

const toEnd = () => {
  const el = inputRef.value!
  el.setSelectionRange(el.value.length, el.value.length)
}

// ============================ value ============================
const nativeInputValue = computed(() =>
  isNullish(props.modelValue) ? '' : normalizeInputValue(String(props.modelValue)),
)

const setNativeInputValue = () => {
  const input = inputRef.value
  if (!input || input.value === nativeInputValue.value) return
  input.value = nativeInputValue.value
}

const onInput = (event: InputEvent) => {
  let { value } = event.target as HTMLInputElement

  value = normalizeInputValue(value)

  if (value === nativeInputValue.value) {
    setNativeInputValue()
    return
  }

  emit('update:modelValue', value)
  emit('change', value)

  nextTick(() => {
    setNativeInputValue()
  })
}

onMounted(() => {
  setNativeInputValue()
})

watch(nativeInputValue, () => {
  nextTick(() => {
    setNativeInputValue()
  })
})

watch(
  () => props.modelValue,
  () => {
    if (props.validateEvent) {
      formItemContext?.onChange()
    }
  },
)

// ============================ focus ============================
const innerFocused = ref(props.focused)

watch(
  () => props.focused,
  () => {
    innerFocused.value = props.focused
  },
)

const onFocus = (event: FocusEvent) => {
  toEnd()
  innerFocused.value = true
  emit('update:focused', true)
  emit('focus', event)
}

const onBlur = (event: FocusEvent) => {
  innerFocused.value = false
  emit('update:focused', false)
  emit('blur', event)

  if (props.validateEvent) {
    formItemContext?.onBlur()
  }
}

const items = computed(() => {
  const valueLength = nativeInputValue.value.length

  return Array(props.length)
    .fill(0)
    .map((_, i) => {
      return {
        index: i,
        active:
          innerFocused.value &&
          (i === valueLength || (i === valueLength - 1 && i === props.length - 1)),
      }
    })
})

// ============================ style ============================

const isTight = computed(() => {
  return props.gap === 0 || (typeof props.gap === 'string' && parseInt(props.gap) === 0)
})

const passwordInputClass = computed(() => {
  return [
    bem.b(),
    bem.m('readonly', isReadonly.value),
    bem.m('disabled', isDisabled.value),
    bem.m(props.type, !isTight.value),
    bem.m(`tight-${props.type}`, isTight.value),
  ]
})

const passwordInputStyle = computed(() => {
  return {
    gap: props.gap,
  }
})
</script>
