// packages/sard/components/layout/row.vue
<template>
  <div :class="bem.b()" :style="rowStyle">
    <slot></slot>
  </div>
</template>

<script setup lang="ts">
import { computed, provide, reactive, toRef } from 'vue'
import { splitUnit, createBem } from '../../utils'
import { type RowProps, type RowSlots, rowSymbol, mapJustify, mapAlign } from './common'

const props = withDefaults(defineProps<RowProps>(), {})

defineSlots<RowSlots>()

const bem = createBem('row')

const gutter = computed(() => {
  if (props.gap) {
    const result = splitUnit(props.gap)
    return [result[0] / 2, result[1] || 'px'] as const
  }
  return [0, 'px'] as const
})

provide(
  rowSymbol,
  reactive({
    gap: toRef(() => props.gap),
    gutter,
  }),
)

// ============================ style ============================

const rowStyle = computed(() => {
  return [
    {
      justifyContent: props.justify && mapJustify[props.justify],
      alignItems: props.align && mapAlign[props.align],
    },
    props.gap
      ? {
          marginLeft: -gutter.value[0] + gutter.value[1],
          marginRight: -gutter.value[0] + gutter.value[1],
        }
      : null,
  ]
})
</script>

// packages/sard/src/components/grid/Row.tsx
import { createContext, CSSProperties, FC, ReactNode, useMemo } from 'react'
import classNames from 'classnames'
import { splitUnit } from '../../utils'

const mapJustify = {
  start: 'flex-start',
  center: 'center',
  end: 'flex-end',
  around: 'space-around',
  between: 'space-between',
  evenly: 'space-evenly',
}
const mapAlign = {
  start: 'flex-start',
  center: 'center',
  end: 'flex-end',
  stretch: 'stretch',
}

export interface RowContext {
  gutter: number | string
  gap: [number, string]
}

export const RowContext = createContext<RowContext | null>(null)

export interface RowProps {
  className?: string
  style?: CSSProperties
  children?: ReactNode
  gutter?: number | string
  justify?: 'start' | 'center' | 'end' | 'around' | 'between' | 'evenly'
  align?: 'start' | 'center' | 'end' | 'stretch'
}

export const Row: FC<RowProps> = (props) => {
  const { className, style, children, gutter, justify, align, ...restProps } =
    props

  const gap = useMemo(() => {
    if (gutter) {
      const result = splitUnit(gutter)
      return [result[0] / 2, result[1] || 'px'] as [number, string]
    }
  }, [gutter])

  const rowStyle = Object.assign(
    {
      justifyContent: justify && mapJustify[justify],
      alignItems: align && mapAlign[align],
    },
    gutter
      ? {
          marginLeft: -gap[0] + gap[1],
          marginRight: -gap[0] + gap[1],
        }
      : null,
    style,
  )

  const rowClass = classNames('s-row', className)

  const context = useMemo(
    () => ({
      gutter,
      gap,
    }),
    [gutter],
  )

  return (
    <div {...restProps} className={rowClass} style={rowStyle}>
      <RowContext.Provider value={context}>{children}</RowContext.Provider>
    </div>
  )
}

export default Row
