// src/views/components/layout/demo/Align.vue
<template>
  <div class="layout-align">
    <s-row v-for="item in alignTypes" :align="item">
      <s-col>
        <div class="layout-box">{{ item }}</div>
      </s-col>
      <s-col>
        <div class="layout-box" style="height: 90px">{{ item }}</div>
      </s-col>
    </s-row>
  </div>
</template>

<script setup lang="ts">
const alignTypes = ['start', 'center', 'end', 'stretch'] as const
</script>

// packages/sard-taro-demo/src/packageA/pages/grid/demo/Align.tsx
import { Col, Row, Space } from 'sard-taro'

import GridBox from '../GridBox'

export default () => {
  return (
    <Space gap="large">
      <Row align="start">
        <Col>
          <GridBox>span</GridBox>
        </Col>
        <Col>
          <GridBox higher>span</GridBox>
        </Col>
      </Row>

      <Row align="center">
        <Col>
          <GridBox>span</GridBox>
        </Col>
        <Col>
          <GridBox higher>span</GridBox>
        </Col>
      </Row>

      <Row align="end">
        <Col>
          <GridBox>span</GridBox>
        </Col>
        <Col>
          <GridBox higher>span</GridBox>
        </Col>
      </Row>
    </Space>
  )
}
