// src/views/components/result/index.vue
<template>
  <doc-page title="Result 结果">
    <doc-demo title="基础使用">
      <Basic />
    </doc-demo>

    <doc-demo title="额外内容">
      <Extra />
    </doc-demo>

    <doc-demo title="自定义图标">
      <Icon />
    </doc-demo>
  </doc-page>
</template>

<script setup lang="ts">
import Basic from './demo/Basic.vue'
import Extra from './demo/Extra.vue'
import Icon from './demo/Icon.vue'
</script>

<style lang="scss" scoped>
:deep() {
  .s-result {
    margin-bottom: 30px;
  }
}
</style>

// packages/sard-taro-demo/src/packageA/pages/result/index.tsx
import Demo from '@/components/demo'
import Page from '@/components/page'

import Basic from './demo/Basic'
import Extra from './demo/Extra'
import Icon from './demo/Icon'

export default () => {
  return (
    <Page className="page-result">
      <Demo title="基础使用">
        <Basic />
      </Demo>

      <Demo title="额外内容">
        <Extra />
      </Demo>

      <Demo title="自定义图标">
        <Icon />
      </Demo>
    </Page>
  )
}
