// src/views/components/password-input/index.vue
<template>
  <doc-page title="PasswordInput 密码输入框">
    <doc-demo title="基础使用">
      <Basic />
    </doc-demo>

    <doc-demo title="下划线类型">
      <Underline />
    </doc-demo>

    <doc-demo title="间距">
      <Gap />
    </doc-demo>

    <doc-demo title="明文显示">
      <PlainText />
    </doc-demo>

    <doc-demo title="只读和禁用">
      <DisabledReadOnly />
    </doc-demo>

    <doc-demo title="使用自定义键盘">
      <CustomKeyboard />
    </doc-demo>
  </doc-page>
</template>

<script setup lang="ts">
import Basic from './demo/Basic.vue'
import Underline from './demo/Underline.vue'
import Gap from './demo/Gap.vue'
import PlainText from './demo/PlainText.vue'
import DisabledReadOnly from './demo/DisabledReadOnly.vue'
import CustomKeyboard from './demo/CustomKeyboard.vue'
</script>

// packages/sard-taro-demo/src/packageA/pages/password-input/index.tsx
import Demo from '@/components/demo'
import Page from '@/components/page'

import Basic from './demo/Basic'
import Underline from './demo/Underline'
import PlainText from './demo/PlainText'
import WithNumberKeyboard from './demo/WithNumberKeyboard'
import Gap from './demo/Gap'

export default () => {
  return (
    <Page>
      <Demo title="基础使用">
        <Basic />
      </Demo>

      <Demo title="下划线类型">
        <Underline />
      </Demo>

      <Demo title="间距">
        <Gap />
      </Demo>

      <Demo title="明文显示">
        <PlainText />
      </Demo>

      <Demo title="使用自定义键盘" full>
        <WithNumberKeyboard />
      </Demo>
    </Page>
  )
}
