// packages/SardDemo/src/sard/badge/index.tsx
import { View } from '@tarojs/components'
import { ReactNode, memo, NamedExoticComponent } from 'react'
import classNames from 'classnames'
import { filterNullish, isNullish, isNumber } from '../utils'
import { BaseProps } from '../base'
import { useBem } from '../use'

export interface BadgeProps extends BaseProps {
  value?: ReactNode
  max?: number
  showZero?: boolean
  color?: string
  textColor?: string
  isDot?: boolean
  fixed?: boolean
}

export const Badge: NamedExoticComponent<BadgeProps> = memo((props) => {
  const {
    className,
    style,
    children,

    value = 0,
    max = 99,
    showZero = false,
    color,
    textColor,
    isDot,
    fixed,
    ...restProps
  } = props

  const [bem] = useBem('badge')

  const zeroHide = !isDot && value === 0 && !showZero

  return (
    <View
      {...restProps}
      className={classNames(bem.b(), bem.m('fixed', fixed), className)}
      style={style}
    >
      {children}
      <View
        className={classNames(
          bem.e('content-wrapper'),
          bem.m('fixed', !fixed && !isNullish(children)),
          bem.m('zero-hide', zeroHide),
        )}
      >
        <View
          className={classNames(
            bem.e('content'),
            bem.em('content', 'fixed', fixed || !isNullish(children)),
            bem.m('is-dot', isDot),
          )}
          style={filterNullish({
            backgroundColor: color,
            color: textColor,
          })}
        >
          {isDot ? '' : isNumber(value) && value > max ? `${max}+` : value}
        </View>
      </View>
    </View>
  )
})

export default Badge

// packages/sard/components/badge/badge.vue
<template>
  <div v-if="slots.default" :class="bem.e('wrapper')">
    <slot></slot>
    <div :class="badgeClass" :style="badgeStyle">
      <slot name="value">
        {{ innerValue }}
      </slot>
    </div>
  </div>
  <div v-else :class="badgeClass" :style="badgeStyle">
    <slot name="value">
      {{ innerValue }}
    </slot>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { createBem } from '../../utils'
import { type BadgeProps, type BadgeSlots, defaultBadgeProps } from './common'

const props = withDefaults(defineProps<BadgeProps>(), defaultBadgeProps)

const slots = defineSlots<BadgeSlots>()

const bem = createBem('badge')

const zeroHide = computed(() => {
  return !props.dot && props.value === 0 && !props.showZero && !slots.value
})

const innerValue = computed(() => {
  return props.dot
    ? ''
    : typeof props.value === 'number' && props.value > props.max
      ? `${props.max}+`
      : props.value === 0 && !props.showZero
        ? ''
        : props.value
})

// ============================ style ============================
const badgeClass = computed(() => {
  return [
    bem.b(),
    bem.m('fixed', props.fixed || !!slots.default),
    bem.m('zero-hide', zeroHide.value),
    bem.m('dot', props.dot),
  ]
})

const badgeStyle = computed(() => {
  return {
    background: props.color,
    color: props.textColor,
  }
})
</script>
