// src/views/components/picker/demo/Multiple.vue
<template>
  <s-list card>
    <s-list-item>
      <s-picker v-model="value" :columns="columns" />
    </s-list-item>
    <s-list-item title="当前值：" :value="JSON.stringify(value) ?? 'undefined'" />
    <s-list-item title="设置为: 2003年10月" arrow hover @click="value = ['2003年', '10月']" />
    <s-list-item title="清空" arrow hover @click="value = undefined" />
  </s-list>
</template>

<script setup lang="ts">
import { ref } from 'vue'

const columns = [
  Array(10)
    .fill(0)
    .map((_, index) => 2000 + index + '年'),
  Array(12)
    .fill(0)
    .map((_, index) => 1 + index + '月'),
]

const value = ref<string[] | undefined>(['2005年', '5月'])
</script>

// packages/SardDemo/src/packageA/pages/picker/demo/Multiple.tsx
import { useState } from 'react'
import { List, Picker, PopoutInput } from 'sard'

export default () => {
  const columns = [
    Array(10)
      .fill(0)
      .map((_, index) => 2000 + index + '年'),
    Array(12)
      .fill(0)
      .map((_, index) => 1 + index + '月'),
  ]

  const [value, setValue] = useState<string[]>()

  return (
    <List card>
      <List.Item
        linkable
        title="设置为: 2003年10月"
        onClick={() => setValue(['2003年', '10月'])}
      />
      <List.Item linkable title="清空" onClick={() => setValue(undefined)} />
      <List.Item>
        <PopoutInput
          title="请选择"
          inputProps={{ placeholder: '请选择' }}
          value={value}
          onChange={setValue}
        >
          <Picker
            columns={columns}
            outletFormatter={(labels) => labels.join('')}
          />
        </PopoutInput>
      </List.Item>
    </List>
  )
}
