// src/views/components/grid/demo/Gap.vue
<template>
  <s-grid :columns="4" :gap="10">
    <s-grid-item v-for="i in 8" :key="i" text="文字" #icon>
      <Image />
    </s-grid-item>
  </s-grid>

  <s-grid :columns="3" square :gap="10" class="mt-4">
    <s-grid-item v-for="i in 6" :key="i" text="文字" #icon>
      <Image />
    </s-grid-item>
  </s-grid>
</template>

<script setup lang="ts">
import { Image } from '@sard/icons'
</script>

// packages/SardDemo/src/packageA/pages/mesh/demo/Gap.tsx
import { Mesh, Space } from 'sard'

export default () => {
  return (
    <Space gap="large">
      <Mesh columns={4} gap={10}>
        {Array(8)
          .fill(0)
          .map((_, index) => (
            <Mesh.Item key={index} text="文字" iconProps={{ name: 'image' }} />
          ))}
      </Mesh>

      <Mesh columns={3} square gap={10}>
        {Array(6)
          .fill(0)
          .map((_, index) => (
            <Mesh.Item key={index} text="文字" iconProps={{ name: 'image' }} />
          ))}
      </Mesh>
    </Space>
  )
}
