// src/views/components/upload/demo/DisabledReadOnly.vue
<template>
  <doc-title>只读</doc-title>
  <s-upload
    :model-value="[
      {
        url: 'https://fastly.jsdelivr.net/npm/@sard/assets/pic1.jpg',
      },
    ]"
    readonly
  />

  <doc-title>禁用</doc-title>
  <s-upload
    :model-value="[
      {
        url: 'https://fastly.jsdelivr.net/npm/@sard/assets/pic1.jpg',
      },
    ]"
    disabled
  />
</template>

// packages/sard-taro-demo/src/packageA/pages/upload/demo/DisabledReadOnly.tsx
import { Space, Upload } from 'sard-taro'

import pic1 from '@/static/pic1.jpg'

export default () => {
  return (
    <Space>
      <Upload
        fileList={[
          {
            url: pic1,
          },
        ]}
        readOnly
      />

      <Upload
        fileList={[
          {
            url: pic1,
          },
        ]}
        disabled
      />
    </Space>
  )
}
