// packages/sard-taro-demo/src/packageA/pages/share-sheet/index.tsx
import Demo from '@/components/demo'
import Page from '@/components/page'

import Basic from './demo/Basic'
import MultipleRow from './demo/MultipleRow'
import TitleDescription from './demo/TitleDescription'
import Picture from './demo/Picture'
import Disabled from './demo/Disabled'
import Manual from './demo/Manual'

export default () => {
  return (
    <Page>
      <Demo title="基础使用" full>
        <Basic />
      </Demo>

      <Demo title="多行" full>
        <MultipleRow />
      </Demo>

      <Demo title="标题和描述" full>
        <TitleDescription />
      </Demo>

      <Demo title="图片类型图标" full>
        <Picture />
      </Demo>

      <Demo title="禁用" full>
        <Disabled />
      </Demo>

      <Demo title="手动声明项目组件" full>
        <Manual />
      </Demo>
    </Page>
  )
}

// src/views/components/share-sheet/index.vue
<template>
  <doc-page title="ShareSheet 分享面板">
    <doc-demo title="基础使用">
      <Basic />
    </doc-demo>

    <doc-demo title="取消按钮">
      <Cancel />
    </doc-demo>

    <doc-demo title="多行">
      <MultipleRow />
    </doc-demo>

    <doc-demo title="标题和描述">
      <TitleDescription />
    </doc-demo>

    <doc-demo title="图片类型图标">
      <Picture />
    </doc-demo>

    <doc-demo title="禁用">
      <Disabled />
    </doc-demo>
  </doc-page>
</template>

<script setup lang="ts">
import Basic from './demo/Basic.vue'
import Cancel from './demo/Cancel.vue'
import MultipleRow from './demo/MultipleRow.vue'
import TitleDescription from './demo/TitleDescription.vue'
import Picture from './demo/Picture.vue'
import Disabled from './demo/Disabled.vue'
</script>
