// src/views/components/input/demo/ShowCount.vue
<template>
  <s-input v-model="value" showCount :maxlength="100" clearable placeholder="请输入" />
  <s-input
    v-model="value"
    type="textarea"
    showCount
    :maxlength="100"
    clearable
    placeholder="请输入"
  />
</template>

<script setup lang="ts">
import { ref } from 'vue'

const value = ref('')
</script>

// packages/SardDemo/src/packageA/pages/input/demo/ShowCount.tsx
import { Input, Space } from 'sard'

export default () => {
  return (
    <Space>
      <Input showCount maxLength={20} clearable placeholder="请输入" />
      <Input
        type="textarea"
        showCount
        maxLength={100}
        clearable
        placeholder="请输入"
      />
    </Space>
  )
}
