// packages/SardDemo/src/packageA/pages/pagination/index.tsx
import Demo from '@/components/demo'
import Page from '@/components/page'

import Basic from './demo/Basic'
import Ellipsis from './demo/Ellipsis'
import Simple from './demo/Simple'
import Custom from './demo/Custom'

export default () => {
  return (
    <Page emphasis>
      <Demo title="基础使用">
        <Basic />
      </Demo>

      <Demo title="显示省略号">
        <Ellipsis />
      </Demo>

      <Demo title="简单分页">
        <Simple />
      </Demo>

      <Demo title="自定义">
        <Custom />
      </Demo>
    </Page>
  )
}

// src/views/components/pagination/index.vue
<template>
  <doc-page title="Pagination 分页">
    <doc-demo title="基础使用">
      <Basic />
    </doc-demo>

    <doc-demo title="显示省略号">
      <Ellipsis />
    </doc-demo>

    <doc-demo title="简单分页">
      <Simple />
    </doc-demo>

    <doc-demo title="自定义">
      <Custom />
    </doc-demo>
  </doc-page>
</template>

<script setup lang="ts">
import Basic from './demo/Basic.vue'
import Ellipsis from './demo/Ellipsis.vue'
import Simple from './demo/Simple.vue'
import Custom from './demo/Custom.vue'
</script>
