// src/views/components/dropdown/demo/Content.vue
<template>
  <s-dropdown>
    <s-dropdown-item :options="options1" model-value="1" />
    <s-dropdown-item title="筛选" v-model:visible="visible">
      <s-list inlaid>
        <s-list-item title="包邮">
          <template #value>
            <s-switch :model-value="true" />
          </template>
        </s-list-item>
        <s-list-item title="团购">
          <template #value>
            <s-switch />
          </template>
        </s-list-item>
        <s-list-item>
          <s-button round @click="visible = false">确认</s-button>
        </s-list-item>
      </s-list>
    </s-dropdown-item>
  </s-dropdown>
</template>

<script setup lang="ts">
import { ref } from 'vue'

const options1 = [
  {
    label: '距离优先',
    value: '1',
  },
  {
    label: '速度优先',
    value: '2',
  },
  {
    label: '评分优先',
    value: '3',
  },
]

const visible = ref(false)
</script>

// packages/SardDemo/src/packageA/pages/dropdown/demo/Content.tsx
import { useState } from 'react'
import { Button, List, Dropdown, Switch } from 'sard'

export default () => {
  const options1 = [
    {
      label: '距离优先',
      value: '1',
    },
    {
      label: '速度优先',
      value: '2',
    },
    {
      label: '评分优先',
      value: '3',
    },
  ]

  const [visible, setVisible] = useState(false)

  return (
    <Dropdown direction="up">
      <Dropdown.Item options={options1} defaultValue="1" />
      <Dropdown.Item title="筛选" visible={visible} onVisible={setVisible}>
        <List inlaid>
          <List.Item title="包邮" value={<Switch />} />
          <List.Item title="团购" value={<Switch />} />
          <List.Item>
            <Button onClick={() => setVisible(false)}>确认</Button>
          </List.Item>
        </List>
      </Dropdown.Item>
    </Dropdown>
  )
}
