// src/views/components/dropdown/demo/Placeholder.vue
<template>
  <s-dropdown>
    <s-dropdown-item placeholder="排序" :options="options1" />
    <s-dropdown-item placeholder="配送时间" :options="options2" />
  </s-dropdown>
</template>

<script setup lang="ts">
const options1 = [
  {
    label: '距离优先',
    value: '1',
  },
  {
    label: '速度优先',
    value: '2',
  },
  {
    label: '评分优先',
    value: '3',
  },
]
const options2 = [
  {
    label: '30分钟内',
    value: '1',
  },
  {
    label: '40分钟内',
    value: '2',
  },
  {
    label: '50分钟内',
    value: '3',
  },
]
</script>

// packages/SardDemo/src/packageA/pages/dropdown/demo/Placeholder.tsx
import { Dropdown } from 'sard'

export default () => {
  const options1 = [
    {
      label: '距离优先',
      value: '1',
    },
    {
      label: '速度优先',
      value: '2',
    },
    {
      label: '评分优先',
      value: '3',
    },
  ]
  const options2 = [
    {
      label: '30分钟内',
      value: '1',
    },
    {
      label: '40分钟内',
      value: '2',
    },
    {
      label: '50分钟内',
      value: '3',
    },
  ]

  return (
    <Dropdown>
      <Dropdown.Item options={options1} placeholder="排序" />
      <Dropdown.Item options={options2} defaultValue="2" />
    </Dropdown>
  )
}
