// src/views/components/tabs/demo/Card.vue
<template>
  <s-tabs v-model="value" :options="options" type="card"></s-tabs>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { type TabProps } from 'sard'

const value = ref(1)
const options = ref<TabProps[]>([
  { label: '标签1', value: 1 },
  { label: '标签2', value: 2 },
  { label: '标签3', value: 3 },
])
</script>

// packages/sard/src/components/tabs/demo/Card.tsx
/*
### 卡片标签
*/

import { Tabs, TabPane } from 'sard'

export default function () {
  return (
    <>
      <Tabs
        type="card"
        style={{ padding: 10, background: 'var(--s-secondary-bg)' }}
        bodyStyle={{ background: 'var(--s-emphasis-bg)' }}
      >
        <TabPane label="标签1">内容1</TabPane>
        <TabPane label="标签2">内容2</TabPane>
        <TabPane label="标签3">内容3</TabPane>
      </Tabs>
    </>
  )
}
