// src/views/components/datetime-picker-popout/demo/Filter.vue
<template>
  <s-datetime-picker-popout
    v-model="date"
    v-model:visible="visible"
    title="取15的倍数的分钟数"
    type="hm"
    :filter="filter"
  />

  <s-list card>
    <s-list-item
      title="取15的倍数的分钟数"
      arrow
      hover
      :value="JSON.stringify(date)"
      @click="visible = true"
    />
  </s-list>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { type DatetimeLetter } from 'sard'

const visible = ref(false)
const date = ref<Date>()

const filter = (letter: DatetimeLetter, value: number) => {
  if (letter === 'm') {
    return value % 15 === 0
  }
  return true
}
</script>

// packages/SardDemo/src/packageA/pages/datetime-picker/demo/Filter.tsx
import { List, DatetimeLetter, DatetimePicker, PopoutInput } from 'sard'

const filter = (letter: DatetimeLetter, value: number) => {
  if (letter === 'm') {
    return value % 15 === 0
  }
  return true
}

export default () => {
  return (
    <List card>
      <List.Item title="“分钟”取15的倍数：" />
      <List.Item>
        <PopoutInput title="请选择" inputProps={{ placeholder: '请选择' }}>
          <DatetimePicker type="hm" filter={filter} />
        </PopoutInput>
      </List.Item>
    </List>
  )
}
