// src/views/components/date-strip/demo/MinMax.vue
<template>
  <s-list card>
    <s-list-item>
      <s-date-strip v-model="value" :min="new Date(2024, 0, 5)" :max="new Date(2024, 0, 19)" />
    </s-list-item>
    <s-list-item title="可选范围" value="2024-01-05 至 2024-01-19" />
    <s-list-item title="当前值" :value="value ? formatDate(value, 'YYYY-MM-DD') : 'undefined'" />
  </s-list>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { formatDate } from 'sard'

const value = ref(new Date(2024, 0, 10))
</script>

// packages/SardDemo/src/packageA/pages/datetime-picker/demo/MinMax.tsx
import { List, DatetimePicker, PopoutInput } from 'sard'

export default () => {
  return (
    <List card>
      <List.Item>
        <PopoutInput title="日期" inputProps={{ placeholder: '日期' }}>
          <DatetimePicker
            type="yMd"
            min={new Date(2000, 4, 13)}
            max={new Date(2003, 6, 8)}
          />
        </PopoutInput>
      </List.Item>

      <List.Item>
        <PopoutInput title="时间" inputProps={{ placeholder: '时间' }}>
          <DatetimePicker
            type="hms"
            min={new Date(0, 0, 1, 9, 0, 0)}
            max={new Date(0, 0, 1, 18, 30, 0)}
          />
        </PopoutInput>
      </List.Item>
    </List>
  )
}
