// packages/sard-taro-demo/src/packageA/pages/cascader/demo/Disabled.tsx
import { Cascader, List, PopoutInput } from 'sard-taro'

const disabledOptions = Array(10)
  .fill(0)
  .map((_, i) => {
    return {
      label: `label${i}`,
      value: `${i}`,
      disabled: i < 3,
      children: Array(10)
        .fill(0)
        .map((_, j) => {
          return {
            label: `label${i}-label${j}`,
            value: `${i}-${j}`,
            disabled: j < 3,
          }
        }),
    }
  })

export default () => {
  return (
    <List card>
      <List.Item>
        <PopoutInput title="请选择" inputProps={{ placeholder: '请选择' }}>
          <Cascader options={disabledOptions} />
        </PopoutInput>
      </List.Item>
    </List>
  )
}

// src/views/components/radio-popout/demo/Disabled.vue
<template>
  <s-radio-popout
    v-model="value"
    v-model:visible="visible"
    title="请选择"
    :options="options"
    @change="onChange"
  />

  <s-list card>
    <s-list-item arrow hover @click="visible = true">
      <template #title>
        {{ value ? JSON.stringify(value) : '请选择' }}
      </template>
    </s-list-item>
    <s-list-item title="设置为：'option3'" arrow hover @click="value = 'option3'" />
    <s-list-item title="清空" arrow hover @click="value = undefined" />
  </s-list>
</template>

<script setup lang="ts">
import { ref } from 'vue'

const options = Array(10)
  .fill(0)
  .map((_, i) => {
    return {
      value: `option${i + 1}`,
      label: `选项${i + 1}`,
      disabled: i > 5,
    }
  })

const visible = ref(false)
const value = ref<string>()

const onChange = (value: any) => {
  console.log('change', value)
}
</script>
