// packages/sard-taro-demo/src/packageA/pages/search/demo/Slot.tsx
import { Button, Search, Space } from 'sard-taro'

export default () => {
  return (
    <Space gap="medium">
      <Search
        placeholder="请输入关键词"
        shape="round"
        prepend={
          <Button
            type="pale-text"
            size="small"
            theme="secondary"
            style={{ marginRight: 6 }}
            iconProps={{
              family: 'demo-icons',
              name: 'upc-scan',
              size: 16,
            }}
          />
        }
        inputPrepend={
          <Button
            type="pale-text"
            size="mini"
            theme="secondary"
            iconProps={{
              name: 'caret-down',
              size: 14,
            }}
          />
        }
        inputAppend={
          <Button
            type="pale-text"
            size="mini"
            theme="secondary"
            iconProps={{
              family: 'demo-icons',
              name: 'camera',
              size: 18,
            }}
          />
        }
      />

      <Search
        placeholder="请输入关键词"
        shape="round"
        prepend={
          <Button
            type="pale-text"
            size="small"
            theme="secondary"
            style={{ marginRight: 6 }}
            iconProps={{
              name: 'left',
              size: 16,
            }}
          />
        }
        append={
          <Button
            type="pale-text"
            size="small"
            theme="secondary"
            style={{ marginLeft: 6 }}
            iconProps={{
              family: 'demo-icons',
              name: 'list-task',
              size: 20,
            }}
          />
        }
      />
    </Space>
  )
}

// src/views/components/search/demo/Slot.vue
<template>
  <s-search placeholder="请输入关键词" shape="round" style="padding-inline-start: 4px">
    <template #prepend>
      <s-button variant="link" size="small" color="secondary" style="margin-inline-end: 4px">
        <demo-icon name="upc-scan" size="16px" />
      </s-button>
    </template>

    <template #input-prepend>
      <s-button variant="link" size="xs" color="secondary">
        <CaretDown />
      </s-button>
    </template>

    <template #input-append>
      <s-button variant="link" size="xs" color="secondary">
        <demo-icon name="camera" size="18px" />
      </s-button>
    </template>
  </s-search>

  <s-search
    placeholder="请输入关键词"
    shape="round"
    style="margin-top: 20px; padding-inline-start: 6px; padding-inline-end: 4px"
  >
    <template #prepend>
      <s-button variant="link" size="xs" color="secondary" style="margin-inline-end: 6px">
        <Left class="text-lg" />
      </s-button>
    </template>

    <template #append>
      <s-button variant="link" size="xs" color="secondary" style="margin-inline-start: 6px">
        <demo-icon name="list-task" size="20px" />
      </s-button>
    </template>
  </s-search>
</template>

<script setup lang="ts">
import { CaretDown, Left } from '@sard/icons'
</script>
