// src/views/components/action-sheet/demo/Cancel.vue
<template>
  <s-button @click="visible = true">显示</s-button>
  <s-action-sheet v-model:visible="visible" show-cancel :item-list="itemList" @select="onSelect" />
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { toast, type ActionSheetItemProps } from 'sard'

const visible = ref(false)

const itemList = ref([{ label: '选项1' }, { label: '选项2' }, { label: '选项3' }])

const onSelect = (item: ActionSheetItemProps) => {
  toast(item.label)
}
</script>

// packages/sard-taro-demo/src/packageA/pages/action-sheet/demo/Cancel.tsx
import { useState } from 'react'
import { ActionSheet, List, Toast } from 'sard-taro'

export default () => {
  const [visible, setVisible] = useState(false)

  return (
    <>
      <List card>
        <List.Item
          linkable
          title="显示动作面板"
          onClick={() => setVisible(true)}
        />
      </List>

      <ActionSheet
        visible={visible}
        onVisible={setVisible}
        cancel="取消"
        onSelect={(index) => {
          Toast.show(index)
        }}
      >
        <ActionSheet.Item name="动作1" />
        <ActionSheet.Item name="动作2" />
        <ActionSheet.Item name="动作3" />
      </ActionSheet>
    </>
  )
}
