// src/views/components/action-sheet/demo/Status.vue
<template>
  <s-button @click="visible = true">显示</s-button>
  <s-action-sheet
    v-model:visible="visible"
    cancel="取消"
    :item-list="itemList"
    @select="onSelect"
  />
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { toast, type ActionSheetItemProps } from 'sard'

const visible = ref(false)
const itemList = ref([
  { label: '选项1', color: 'var(--s-color-danger)' },
  { label: '选项2', disabled: true },
  { label: '选项3', loading: true },
])

const onSelect = (item: ActionSheetItemProps) => {
  toast(item.label)
}
</script>

// packages/sard-taro-demo/src/packageA/pages/action-sheet/demo/Status.tsx
import { useState } from 'react'
import { ActionSheet, List, Toast } from 'sard-taro'

export default () => {
  const [visible, setVisible] = useState(false)

  return (
    <>
      <List card>
        <List.Item
          linkable
          title="显示动作面板"
          onClick={() => setVisible(true)}
        />
      </List>

      <ActionSheet
        visible={visible}
        onVisible={setVisible}
        cancel="取消"
        onSelect={(index) => {
          Toast.show(index)
        }}
      >
        <ActionSheet.Item name="动作1" color="red" />
        <ActionSheet.Item name="动作2" disabled />
        <ActionSheet.Item name="动作3" />
      </ActionSheet>
    </>
  )
}
